// Shared decisions only. Each season still owns currency, card pool and rules.
const defense=new Set(['护卫','重装战士','斗士','主宰','岛屿卫士','不屈之心']);
const magic=new Set(['法师','神谕','科学家']);
export function role(d){if(d.range===1||d.traits.some(t=>defense.has(t))&&d.hp>=850)return 'front';if(d.traits.some(t=>magic.has(t)))return 'magic';return 'physical';}
const traits=(u,d)=>[...new Set([...d.traits,...(u.items??[]).filter(n=>n.endsWith('纹章')).map(n=>n.slice(0,-2)),...(u.evolutions??[])])];
export function power(u,d,p={}){const star=u.star??1,hp=[1,1.8,3.24][star-1],ad=[1,1.7,2.8][star-1];return d.hp*hp/180+d.ad*d.as*ad/12+d.cost*3+(u.items?.length??0)*4+(u.hero||p.heroName===u.name?12:0)+(u.permanent?.ap??0)*.1+(u.permanent?.ad??0)*.15+(u.permanent?.hp??0)/180;}
export function focusFor(p,defs,tierMap){const scores=new Map();for(const u of p.units){const d=defs.get(u.name);for(const t of traits(u,d))if((tierMap[t]?.length??0)&&tierMap[t][0]>1)scores.set(t,(scores.get(t)??0)+((u.star??1)>1?3:1)+(u.hero||p.heroName===u.name?4:0));}for(const t of p.aiFocus??[])if(scores.has(t))scores.set(t,scores.get(t)+2);return [...scores].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,2).map(v=>v[0]);}
export function boardScore(board,defs,tierMap,p){const names=new Set(),counts={};let value=0,front=0;for(const u of board){const d=defs.get(u.name);value+=power(u,d,p);if(role(d)==='front')front++;if(names.has(u.name))continue;names.add(u.name);for(const t of traits(u,d))counts[t]=(counts[t]??0)+1;}for(const [t,n]of Object.entries(counts)){const tiers=tierMap[t]??[],q=tiers.filter(v=>n>=v).length;value+=q*9+n*(p.aiFocus?.includes(t)?2.5:1);if(t==='宿敌'&&n>1&&!p.centuryPeace)value-=20;}if(board.length>=3)value+=Math.min(front,Math.max(1,Math.floor(board.length/3)))*8+(front===0?-18:0);return value;}
export function selectBoard(p,catalog,tierMap,capacity){const defs=new Map(catalog.map(d=>[d.name,d])),available=[...p.units],board=[];while(board.length<Math.min(capacity,available.length)){const candidate=available.filter(u=>!board.includes(u)).sort((a,b)=>boardScore([...board,b],defs,tierMap,p)-boardScore([...board,a],defs,tierMap,p)||a.id-b.id)[0];board.push(candidate);}for(let pass=0;pass<3;pass++){let changed=false,current=boardScore(board,defs,tierMap,p);for(let i=0;i<board.length;i++)for(const u of available.filter(u=>!board.includes(u))){const next=[...board];next[i]=u;const score=boardScore(next,defs,tierMap,p);if(score>current+.1){board[i]=u;current=score;changed=true;}}if(!changed)break;}return board.sort((a,b)=>power(b,defs.get(b.name),p)-power(a,defs.get(a.name),p));}
export function purchaseScore(p,d,defs,tierMap){const own=p.units.filter(u=>u.name===d.name),copies=own.reduce((n,u)=>n+3**(u.star-1),0);if(own.some(u=>u.star===3))return -100;const board=p.units.filter(u=>u.location==='board'),present=new Set(board.flatMap(u=>traits(u,defs.get(u.name))));return power({name:d.name,star:1},d,p)+Math.min(8,copies)*3+(copies%3===2?22:0)+d.traits.reduce((n,t)=>n+(p.aiFocus?.includes(t)?8:present.has(t)?3:0),0);}
export function economyPlan(g,p){const fielded=p.units.filter(u=>u.location==='board').length,urgent=p.hp<40||(p.streak??0)<=-3||fielded<Math.min(p.level,4),target=p.units.filter(u=>u.star===2).find(u=>{const d=g.catalog.find(d=>d.name===u.name);return d.cost<=3&&p.units.filter(w=>w.name===u.name).reduce((n,w)=>n+3**(w.star-1),0)>=5;});return {reserve:urgent?0:g.stage<3?10:target?20:g.stage>=5?30:40,targetLevel:Math.min(9,g.stage+3),rerollTarget:target?.name,rolls:urgent?8:target?6:3};}
export function positionBoard(board,catalog,p,opponent=[]){const defs=new Map(catalog.map(d=>[d.name,d])),taken=new Set(),enemyFront=opponent.filter(u=>u.y<=2),danger=enemyFront.length?enemyFront.reduce((n,u)=>n+u.x,0)/enemyFront.length:3,backOrder=danger<=3?[5,4,6,3,2,1,0]:[1,2,0,3,4,5,6];for(const u of p.units)u.location='bench';for(const u of board){const d=defs.get(u.name),front=role(d)==='front',xs=front?[3,2,4,1,5,0,6]:backOrder;for(const y of front?[4,5,6,7]:[7,6,5,4]){const x=xs.find(x=>!taken.has(x+','+y));if(x!==undefined){u.location='board';u.x=x;u.y=y;taken.add(x+','+y);break;}}}for(const u of p.units.filter(u=>u.location!=='board').slice(9))u.location='pending';}
export function gearRole(name,components,items){const item=items.find(i=>i[0]===name),component=components.find(c=>c[1]===name),codes=item?.[1]??component?.[0]??'';if(name.endsWith('纹章'))return 'emblem';if(/战甲|披风|生命铠|甲|壁垒|不沉之旗|救赎|圣杯|熔炉/.test(name))return 'front';if(/大天使|光辉冠|光能杖|光能枪刃|星辉|圣典|罗盘|棱镜|核心/.test(name))return 'magic';if(/狂怒|光弩|长枪|引擎|战刃|佩刀|火铳|巨锤|射矛/.test(name))return 'physical';if(codes.includes('R'))return 'magic';if(codes.includes('A')||codes.includes('C')||codes==='HH')return 'front';return 'utility';}
export function gearScore(name,u,d,p,components,items){const type=gearRole(name,components,items),r=role(d);if(type==='emblem')return traits(u,d).includes(name.slice(0,-2))?-100:15+(p.aiFocus?.includes(name.slice(0,-2))?15:0);return power(u,d,p)*.2+(type===r?25:type==='utility'?12:type==='front'&&r!=='front'?0:r==='front'&&type==='physical'?7:-5)-(u.items?.length??0)*2;}
export function bestCraft(p,catalog,recipe,components,items){const board=p.units.filter(u=>u.location==='board'),defs=new Map(catalog.map(d=>[d.name,d]));let best=null;for(let i=0;i<p.items.length;i++)for(let j=i+1;j<p.items.length;j++){const result=recipe(p.items[i],p.items[j]);if(!result)continue;const score=result==='统帅冠冕'?50:Math.max(0,...board.map(u=>gearScore(result,u,defs.get(u.name),p,components,items)));if(!best||score>best.score)best={i,j,result,score};}return best;}
