import {createBattle,step,summary,distance,stats,traitCounts,traitTiers,supportedTraits,heroNames} from './engine.mjs';
import {mountReference,skillMarkup,equipmentButtons} from './reference-ui.mjs';
import {mountMedia} from './media.mjs';
import {createEffects} from './battle-vfx.mjs';
const $=id=>document.getElementById(id);
const response=await fetch('./data.json');if(!response.ok)throw Error('角色数据加载失败');const data=await response.json();
const reference=mountReference(data);
const media=mountMedia(toast),effects=createEffects();
const names=new Map(data.units.map(u=>[u.name,u]));const runnable=data.units.filter(u=>u.implemented);
const campaignMode=new URLSearchParams(location.search).get('mode')==='match';let campaignAdapter=null,battleCatalog=data.units;
const heroDescriptions={红莲火焰:'无尽连打：每次普攻叠加3%本场攻速；每第三次攻击常驻重拳。',赛罗:'头镖风暴：累计每8次真实击杀增加一枚头镖，最多六枚；可在本体记录中保留。',奈克瑟斯:'红色进化：无蓝条，每第六次普攻释放进化斩击、吸血并永久叠法强。',赛文:'独战之志：不再召唤米克拉斯，强化五次穿透普攻，本体获得额外生命。',武士圣剑:'拔刀一闪：承伤架势后斩击，每次斩击获得本场攻速。',杰克:'手镯武装：三枚独立攻击的悬浮手镯，施法叠加本场攻击力。',阿斯特拉:'流星连踢：无蓝条，每第三次攻击连踢；击杀加攻速并继续追击。',贝利亚:'终极战斗仪：横扫普攻、攻速和吸血，击杀延长形态。'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let side=0,selected=null,placements=[],battle=null,running=false,paused=false,accumulator=0,lastFrame=0,logIndex=0,particles=[],lastResult=false;
let selectedEntity=null,drag=null,hover=null,keyboardCell={x:3,y:6};
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('reduced').checked=reduced;
const palette=['#3e8e7d','#9576ad'];
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('toast').hidden=true,2600);}
function preset(){placements=[
 {name:'红莲火焰',side:0,x:2,y:4,star:2,hero:true},{name:'奈克瑟斯',side:0,x:3,y:4,star:2},{name:'戴拿',side:0,x:4,y:4,star:2},
 {name:'杰克',side:0,x:2,y:6,star:2},{name:'赛文',side:0,x:4,y:6,star:2},{name:'初代',side:0,x:3,y:5,star:2},
 {name:'贝利亚',side:1,x:3,y:3,star:2,hero:true},{name:'武士圣剑',side:1,x:2,y:3,star:2},{name:'机械哥莫拉',side:1,x:4,y:3,star:2},
 {name:'艾斯',side:1,x:2,y:1,star:2},{name:'黑暗洛普斯',side:1,x:4,y:1,star:2},{name:'阿斯特拉',side:1,x:3,y:2,star:2}];reset();save();}
function save(){try{localStorage.setItem('ultra-autochess-prototype-v1',JSON.stringify({version:1,placements,seed:Number($('seed').value)}));}catch{toast('浏览器存储不可用，本次仍可正常演武。');}}
function load(){try{const s=JSON.parse(localStorage.getItem('ultra-autochess-prototype-v1')??'null');if(!s||s.version!==1||!Array.isArray(s.placements))return false;const used=new Set();placements=s.placements.filter(p=>{const k=`${p.x},${p.y}`;if(!names.get(p.name)?.implemented||![0,1].includes(p.side)||!Number.isInteger(p.x)||!Number.isInteger(p.y)||p.x<0||p.x>6||p.y<0||p.y>7||used.has(k)||(p.side===0?p.y<4:p.y>3))return false;used.add(k);return true;});$('seed').value=Number(s.seed)>>>0;return placements.length>1;}catch{return false;}}
function setSide(n){side=n;selected=null;$('player-tab').classList.toggle('selected',n===0);$('enemy-tab').classList.toggle('selected',n===1);$('player-tab').setAttribute('aria-selected',n===0);$('enemy-tab').setAttribute('aria-selected',n===1);renderRoster();updatePanels();}
function renderRoster(){
 if(campaignAdapter)return campaignAdapter.renderShop();
 $('unit-count').textContent=`${runnable.length} / 59`;
 $('roster').innerHTML=runnable.map(u=>`<button class="unit-card ${selected===u.name?'active':''}" data-unit="${esc(u.name)}" style="--unit-color:${data.palette[u.cost]}"><span class="portrait">${esc(u.name.slice(0,2))}</span><span><b>${esc(u.name)}</b><small>${esc(u.traits.slice(0,2).join(' · '))}</small></span><span class="cost">${u.cost}◆</span></button>`).join('');
 for(const b of $('roster').querySelectorAll('button'))b.onclick=()=>{if(battle)return toast('先回到准备阶段再布置棋子。');selected=b.dataset.unit;renderRoster();showDetail({name:selected,star:Number($('star').value),hero:$('hero').checked});$('selection-tip').textContent=`${side===0?'我方':'对手'} · ${selected} · 点击半场落位`;$('selection-tip').hidden=false;};
}
function showDetail(p){selectedEntity=p;const def=p.definition??names.get(p.name)??battleCatalog.find(u=>u.name===p.name);if(!def)return;let actual=p.buffs?p:null;
 if(!actual&&names.has(p.name)){
  try{const ownSide=p.side??0,team=placements.filter(w=>names.has(w.name)&&!w.special&&!w.previewMetal&&w.side===ownSide).map(w=>({...w}));let target=team.find(w=>p.id!=null?w.instanceId===p.id:w.name===p.name&&w.x===p.x&&w.y===p.y);
   if(!target){target={...p,side:ownSide,x:3,y:ownSide===0?6:1,star:p.star??1};team.length=0;team.push(target);}
   const foe={name:'初代',side:1-ownSide,x:3,y:ownSide===0?0:7,star:1};const state=createBattle(data.units,[...team,foe]);actual=state.units[team.indexOf(target)];
  }catch{actual=null;}
 }
 const live=actual?stats(actual):null;
 $('unit-detail').innerHTML=`<span class="eyebrow">${def.cost}费 / ${esc(def.traits.join(' · '))}</span><h3>${esc(p.name)} <span style="color:#b18d47;font-size:12px">${'★'.repeat(p.star)}</span></h3><div class="stat-grid"><div>生命<b>${Math.round(actual?.maxHp??p.maxHp??(def.hp*[1,1.8,3.24][p.star-1]+(def.cost===5&&p.star===3?4000:0)))}</b></div><div>攻击<b>${Math.round(live?.ad??def.ad*[1,1.5,2.25][p.star-1])}</b></div><div>攻速<b>${(live?.as??def.as).toFixed(2)}</b></div><div>法强<b>${Math.round(live?.ap??100)}</b></div><div>护甲 / 魔抗<b>${Math.round(live?.armor??def.armor)} / ${Math.round(live?.mr??def.mr)}</b></div><div>射程 / 法力<b>${def.range}格 · ${actual?.maxMana?`${Math.round(actual.mana)} / ${actual.maxMana}`:def.mana?def.mana.join(" / "):"无蓝条"}</b></div></div>${skillMarkup(p.name,p.star,p.hero)||`<p>${esc(def.skill)}</p>`}${p.hero&&heroDescriptions[p.name]?`<p class="hero-skill">✦ 英雄强化已生效</p>`:''}${!campaignMode&&!battle&&placements.includes(p)?'<button class="text-btn" id="remove-unit">移出棋盘</button>':''}`;
 if(!campaignMode&&p.items?.length){$('unit-detail').insertAdjacentHTML('beforeend','<h4>装备</h4>'+equipmentButtons(p.items));reference.bind($('unit-detail'));}
 if($('remove-unit'))$('remove-unit').onclick=()=>{placements=placements.filter(u=>u!==p);selectedEntity=null;save();updatePanels();$('unit-detail').innerHTML='<h3>棋子已移出</h3>';};
}
function updatePanels(){
 $('player-size').textContent=placements.filter(p=>p.side===0&&!p.special).length;$('enemy-size').textContent=placements.filter(p=>p.side===1&&!p.special).length;
 const preview=placements.filter(p=>p.side===side&&!p.special).map(p=>({...p,traits:[...(names.get(p.name)?.traits??[]),...(p.items??[]).filter(n=>n.endsWith('纹章')).map(n=>n.slice(0,-2))]}));if((traitCounts(preview)['宿敌']??0)>=1)for(const u of preview)if(u.name==='赛罗')u.traits=[...new Set([...u.traits,...(u.evolutions??[])])];const counts=battle?battle.traits[side].counts:traitCounts(preview);
 $('traits').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([name,n])=>{const t=traitTiers[name]??[1],on=t.some(v=>n>=v);return '<button class="trait-chip '+(on?'on':'')+'" data-trait-info="'+esc(name)+'">'+esc(name)+' '+n+' / '+(t.find(v=>v>n)??t.at(-1))+'</button>';}).join('');
 for(const b of $('traits').querySelectorAll('button'))b.onclick=()=>reference.showTrait(b.dataset.traitInfo,counts[b.dataset.traitInfo]);
}
function reset(){effects.clear();selected=null;selectedEntity=null;drag=null;hover=null;$('unit-detail').innerHTML='<h3>棋子详情</h3>';running=false;paused=false;battle=null;lastResult=false;particles=[];logIndex=0;accumulator=0;$('start').disabled=false;$('pause').disabled=true;$('pause').textContent='暂停';$('battle-clock').textContent='准备阶段';$('status').textContent='准备阶段';$('log').innerHTML='<p class="empty">战斗尚未开始</p>';$('selection-tip').hidden=true;updatePanels();}
function start(){try{if(!placements.some(p=>p.side===0)||!placements.some(p=>p.side===1))return toast('双方至少各放一名棋子。');battle=createBattle(battleCatalog,structuredClone(placements),Number($('seed').value));running=true;paused=false;logIndex=0;accumulator=0;lastResult=false;selected=null;$('selection-tip').hidden=true;$('start').disabled=true;$('pause').disabled=false;$('pause').textContent='暂停';$('status').textContent='战斗进行中';renderRoster();updatePanels();if(!campaignMode)save();}catch(e){toast(e.message);}}
function tone(type){media.sound(type);}
function processEvents(){
 const fresh=battle.events.slice(logIndex);logIndex=battle.events.length;
 const byId=new Map(battle.units.map(u=>[u.id,u]));const filtered=fresh.filter(e=>['cast','death','revive','beam','growth','end','blades'].includes(e.type));
 for(const e of fresh){if(['cast','death','revive','beam'].includes(e.type)){const target=byId.get(e.type==='death'?e.target:e.source);effects.add(e.type,target,e.type==='beam'||target?.definition?.cost===5?2:1);if(e.type==='death')tone('death');}if(!reduced&&e.type==='hit'){const u=byId.get(e.source),v=byId.get(e.target);if(v)particles.push({type:'hit',x:v.x,y:v.y,from:u?{x:u.x,y:u.y}:null,text:String(e.amount),life:.6,maxLife:.6,color:e.crit?'#b2872e':e.kind==='magic'?'#967ac4':'#4f8071'});}if(e.type==='loot-drop'){const labels=[...e.loot.filter(d=>d.item).map(d=>d.item),...(e.loot.some(d=>d.gold)?[e.loot.reduce((n,d)=>n+(d.gold??0),0)+'金币']:[])];particles.push({type:'loot',x:e.x,y:e.y,text:'✦ '+labels.join(' · '),life:2.5,maxLife:2.5,color:'#a67620'});tone('loot');effects.add('loot',e);const row=document.createElement('p');row.textContent='掉落：'+labels.join(' · ');$('log').prepend(row);}if(e.type==='cast')tone('cast');}
 if(fresh.some(e=>e.type==='attack'))tone('attack');particles=particles.slice(-80);
 for(const e of filtered){const u=byId.get(e.source),v=byId.get(e.target);let text=e.type==='cast'?`${u?.name} 释放技能${e.second?' · 双重施法':''}`:e.type==='death'?`${v?.name} 阵亡`:e.type==='revive'?`${u?.name} 不屈复活`:e.type==='growth'?`${u?.name} 法强 +${e.amount}`:e.type==='beam'?'银河警备队 · 集结光线':e.type==='blades'?`${u?.name} · ${e.count}枚头镖`:'战斗结束';const p=document.createElement('p');p.innerHTML=`<strong>${e.time.toFixed(1)}s</strong> ${esc(text)}`;$('log').prepend(p);}
 while($('log').children.length>70)$('log').lastElementChild.remove();
}
function finish(){tone(battle.winner===0?'victory':'defeat');effects.add(battle.winner===0?'victory':'death',{x:3,y:4},2);running=false;$('pause').disabled=true;$('status').textContent='战斗已结束';if(lastResult)return;lastResult=true;const winner=battle.winner;$('result-title').textContent=winner===0?'演武胜利':winner===1?'演武落败':'势均力敌';$('result-symbol').style.color=winner===0?'#478874':winner===1?'#9477a4':'#af8f49';$('result-description').textContent=`${battle.time.toFixed(1)}秒 · 种子 ${battle.seed} · 可以重放同一场战斗或调整阵容。`;
 const list=battle.units.filter(u=>!u.special).sort((a,b)=>b.damageDone-a.damageDone).slice(0,6),max=Math.max(1,...list.map(u=>u.damageDone));$('damage-list').innerHTML=list.map(u=>`<div class="damage-row"><span>${esc(u.name)}</span><div class="damage-bar"><i style="width:${u.damageDone/max*100}%;background:${palette[u.side]}"></i></div><b>${Math.round(u.damageDone)}</b></div>`).join('');if(campaignAdapter)campaignAdapter.onFinish(battle);$('result').showModal();}
const canvas=$('arena'),ctx=canvas.getContext('2d');let size={w:0,h:0,r:0,ox:0,oy:0};
function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio);canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const r=Math.min((box.width-36)/(Math.sqrt(3)*7.5),(box.height-28)/(1.5*7+2));size={w:box.width,h:box.height,r,ox:(box.width-Math.sqrt(3)*7.5*r)/2+Math.sqrt(3)*r/2,oy:(box.height-12.5*r)/2+r};}
function center(p){return {x:size.ox+(p.x+.5*(p.y&1))*Math.sqrt(3)*size.r,y:size.oy+p.y*1.5*size.r};}
function hex(p,r,fill,stroke){ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/180*(60*i-30),x=p.x+r*Math.cos(a),y=p.y+r*Math.sin(a);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function cellAt(event){const box=canvas.getBoundingClientRect(),p={x:event.clientX-box.left,y:event.clientY-box.top};let best=null,dist=Infinity;for(let y=0;y<8;y++)for(let x=0;x<7;x++){const c=center({x,y}),d=Math.hypot(c.x-p.x,c.y-p.y);if(d<dist){dist=d;best={x,y};}}return dist<=size.r?best:null;}
function drawUnit(u){const c=center(u),r=size.r*.56,isDead=u.dead&&(!u.reviveAt||u.reviveAt<=battle?.time),tint=palette[u.side];ctx.save();ctx.globalAlpha=isDead?.25:1;
 const shadow=ctx.createRadialGradient(c.x,c.y+r*.6,1,c.x,c.y+r*.6,r*1.2);shadow.addColorStop(0,'#3d352b35');shadow.addColorStop(1,'#3d352b00');ctx.fillStyle=shadow;ctx.beginPath();ctx.ellipse(c.x,c.y+r*.65,r*1.15,r*.5,0,0,Math.PI*2);ctx.fill();
 ctx.beginPath();ctx.arc(c.x,c.y,r,0,Math.PI*2);const grad=ctx.createLinearGradient(c.x-r,c.y-r,c.x+r,c.y+r);grad.addColorStop(0,u.side===0?'#d6f0e2':'#e6d8f0');grad.addColorStop(1,tint);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=u.hero?'#b68b39':'#f8f4e7';ctx.lineWidth=u.hero?3:2;ctx.stroke();
 if(u.booster){ctx.strokeStyle='#a68b3f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(c.x,c.y,r+4,0,Math.PI*2);ctx.stroke();}
 if(u.neutral){ctx.fillStyle='#755840';ctx.beginPath();ctx.moveTo(c.x-r*.6,c.y-r*.6);ctx.lineTo(c.x-r*.4,c.y-r*1.05);ctx.lineTo(c.x-r*.15,c.y-r*.55);ctx.lineTo(c.x+r*.15,c.y-r*.55);ctx.lineTo(c.x+r*.4,c.y-r*1.05);ctx.lineTo(c.x+r*.6,c.y-r*.6);ctx.lineTo(c.x+r*.6,c.y+r*.5);ctx.lineTo(c.x-r*.6,c.y+r*.5);ctx.closePath();ctx.fill();ctx.fillStyle='#f2c16c';ctx.fillRect(c.x-r*.4,c.y-r*.2,r*.25,r*.14);ctx.fillRect(c.x+r*.15,c.y-r*.2,r*.25,r*.14);}else {
 // Original code-drawn insignia: a silver mask, eye slits and chest crystal.
 ctx.fillStyle='#faf5e8';ctx.beginPath();ctx.moveTo(c.x,c.y-r*.76);ctx.lineTo(c.x+r*.52,c.y-r*.26);ctx.lineTo(c.x+r*.33,c.y+r*.36);ctx.lineTo(c.x,c.y+r*.62);ctx.lineTo(c.x-r*.33,c.y+r*.36);ctx.lineTo(c.x-r*.52,c.y-r*.26);ctx.closePath();ctx.fill();ctx.fillStyle=u.side===0?'#6b987c':'#9a81b2';ctx.beginPath();ctx.ellipse(c.x-r*.23,c.y-r*.12,r*.18,r*.09,-.25,0,Math.PI*2);ctx.ellipse(c.x+r*.23,c.y-r*.12,r*.18,r*.09,.25,0,Math.PI*2);ctx.fill();ctx.fillStyle=data.palette[names.get(u.name)?.cost??1];ctx.beginPath();ctx.arc(c.x,c.y+r*.3,r*.13,0,Math.PI*2);ctx.fill();}
 ctx.textAlign='center';ctx.font=`600 ${Math.max(9,size.r*.26)}px Microsoft YaHei`;ctx.fillStyle='#344138';ctx.fillText(u.name+(u.booster?' ↑':''),c.x,c.y+r+size.r*.38);ctx.font=`${Math.max(8,size.r*.2)}px sans-serif`;ctx.fillStyle='#ae843b';ctx.fillText('★'.repeat(u.star),c.x,c.y-r-size.r*.13);
 const bw=size.r*1.15,bh=Math.max(3,size.r*.09),by=c.y+r+3;ctx.fillStyle='#a79c8745';ctx.fillRect(c.x-bw/2,by,bw,bh);const hp=u.hp!==undefined?u.hp/u.maxHp:1;ctx.fillStyle=tint;ctx.fillRect(c.x-bw/2,by,bw*Math.max(0,hp),bh);
 if(u.maxMana){ctx.fillStyle='#559fc6';ctx.fillRect(c.x-bw/2,by+bh+2,bw*u.mana/u.maxMana,2);}if(u.shields?.length){const amount=u.shields.reduce((n,s)=>n+s.amount,0);ctx.fillStyle='#c1a65c';ctx.fillRect(c.x-bw/2,by-3,bw*Math.min(1,amount/u.maxHp),2);}
 if(u.belialUntil>battle?.time||u.flameUntil>battle?.time){ctx.strokeStyle=u.name==='贝利亚'?'#a077bb':'#d58a43';ctx.lineWidth=2;ctx.beginPath();ctx.arc(c.x,c.y,r+4,0,Math.PI*2);ctx.stroke();}
 if(u.bladesUntil>battle?.time)for(let i=0;i<3;i++){const a=i*Math.PI*2/3+(reduced?0:battle.time);ctx.strokeStyle='#c9a65a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(c.x+Math.cos(a)*(r+6),c.y+Math.sin(a)*(r+6),4,0,Math.PI*2);ctx.stroke();}
 ctx.restore();
}
function render(dt){const {w,h,r}=size;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#e6ddee');bg.addColorStop(.48,'#f3edda');bg.addColorStop(1,'#dce7d5');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
 for(let y=0;y<8;y++)for(let x=0;x<7;x++){const p={x,y},c=center(p),own=side===0?y>=4:y<4;hex(c,r*.97,(x+y)%2?'#fffcf238':'#d0c4a528','#ac9b7240');if(selected&&!battle&&own)hex(c,r*.93,'#75a88712','#7e9a6f55');if(hover&&hover.x===x&&hover.y===y&&!battle)hex(c,r*.94,'#fef9df90','#ac8b4a');}
 const lineY=(center({x:0,y:3}).y+center({x:0,y:4}).y)/2;ctx.setLineDash([3,7]);ctx.beginPath();ctx.moveTo(20,lineY);ctx.lineTo(w-20,lineY);ctx.strokeStyle='#b4966150';ctx.stroke();ctx.setLineDash([]);
 ctx.textAlign='center';ctx.fillStyle='#b0935860';ctx.font=`${r*1.1}px Georgia`;ctx.fillText('✦',w/2,lineY+r*.4);
 const list=battle?battle.units:placements;for(const u of list.filter(u=>u.name==='托雷基亚')){const c=center(u.eye??u.eyePosition??u);hex(c,r*.78,'#ad87b422','#9c72b399');ctx.strokeStyle='#8865a6';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(c.x,c.y,r*.29,r*.15,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#bd9dc6';ctx.beginPath();ctx.arc(c.x,c.y,r*.09,0,Math.PI*2);ctx.fill();}for(const u of [...list].sort((a,b)=>a.y-b.y))drawUnit(u);
 for(const p of particles){p.life-=dt;const c=center(p);ctx.globalAlpha=Math.max(0,p.life/p.maxLife);if(p.from&&p.life/p.maxLife>.55){const f=center(p.from),t=Math.min(1,(1-p.life/p.maxLife)/.45),dx=c.x-f.x,dy=c.y-f.y,head={x:f.x+dx*t,y:f.y+dy*t},tail={x:f.x+dx*Math.max(0,t-.18),y:f.y+dy*Math.max(0,t-.18)};ctx.save();ctx.shadowColor=p.color;ctx.shadowBlur=7;ctx.strokeStyle=p.color;ctx.lineWidth=p.color==='#b2872e'?3:1.8;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(head.x,head.y);ctx.stroke();ctx.fillStyle='#fff7dc';ctx.beginPath();ctx.arc(head.x,head.y,2,0,Math.PI*2);ctx.fill();ctx.restore();}if(p.type==='loot'){ctx.save();ctx.translate(c.x,c.y-8);ctx.shadowColor='#edc773';ctx.shadowBlur=14;ctx.fillStyle='#e9c26a';ctx.strokeStyle='#fff4d0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(10,0);ctx.lineTo(0,12);ctx.lineTo(-10,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}ctx.fillStyle=p.color;ctx.textAlign='center';ctx.font=`bold ${Math.max(11,r*.3)}px sans-serif`;ctx.fillText(p.text,c.x,c.y-r-(1-p.life/p.maxLife)*18);ctx.globalAlpha=1;}particles=particles.filter(p=>p.life>0);effects.draw(ctx,dt,center,r,reduced);
}
function frame(now){const dt=Math.min(.15,(now-lastFrame)/1000||0);lastFrame=now;if(running&&!paused&&!document.hidden){accumulator+=dt*Number($('speed').value);while(accumulator>=.05&&running){step(battle);accumulator-=.05;if(battle.finished)finish();}processEvents();$('battle-clock').textContent=`${battle.time.toFixed(1)}s${battle.time>=30?' · 加时':''}`;if(selectedEntity?.id){const current=battle.units.find(u=>u.id===selectedEntity.id);if(current)showDetail(current);}}render(dt);requestAnimationFrame(frame);}
canvas.addEventListener('pointerdown',e=>{if(battle)return;const p=cellAt(e);if(!p)return;const u=placements.find(u=>u.x===p.x&&u.y===p.y);drag={unit:u,startX:e.clientX,startY:e.clientY};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>hover=cellAt(e));
canvas.addEventListener('pointercancel',()=>drag=null);
canvas.addEventListener('pointerup',e=>{if(battle){const p=cellAt(e),u=battle.units.find(u=>u.x===p?.x&&u.y===p?.y);if(u)showDetail(u);return;}const p=cellAt(e);if(!p){drag=null;return;}
 const moved=drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>8;
 if(moved&&drag.unit){if(campaignAdapter){campaignAdapter.move(drag.unit,p);drag=null;return;}const u=drag.unit;if((u.side===0?p.y<4:p.y>3)){toast('棋子只能布置在自己的半场。');drag=null;return;}const other=placements.find(w=>w!==u&&w.x===p.x&&w.y===p.y);if(other){other.x=u.x;other.y=u.y;}u.x=p.x;u.y=p.y;save();updatePanels();drag=null;return;}
 if(campaignAdapter?.placingEye()){campaignAdapter.place(p);drag=null;return;}
 const placed=placements.find(u=>u.x===p.x&&u.y===p.y);if(placed){selected=null;$('selection-tip').hidden=true;if(campaignAdapter)campaignAdapter.inspect(placed);else{showDetail(placed);renderRoster();}}else place(p);drag=null;
});
function place(p){if(campaignAdapter)return campaignAdapter.place(p);if(!selected)return;if((side===0?p.y<4:p.y>3))return toast('请放到所选阵营的半场。');if(placements.filter(u=>u.side===side).length>=11)return toast('实验场每方最多11名真实棋子。');const hero=$('hero').checked&&heroNames.includes(selected);if(hero)for(const u of placements.filter(u=>u.side===side))u.hero=false;const u={name:selected,side,x:p.x,y:p.y,star:Number($('star').value),hero};placements.push(u);showDetail(u);save();updatePanels();}
canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(battle)return;const p=cellAt(e);if(campaignAdapter)return campaignAdapter.remove(p);placements=placements.filter(u=>u.x!==p?.x||u.y!==p?.y);save();updatePanels();});
canvas.tabIndex=0;canvas.addEventListener('keydown',e=>{if(battle)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Delete'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')keyboardCell.x=Math.max(0,keyboardCell.x-1);if(e.key==='ArrowRight')keyboardCell.x=Math.min(6,keyboardCell.x+1);if(e.key==='ArrowUp')keyboardCell.y=Math.max(0,keyboardCell.y-1);if(e.key==='ArrowDown')keyboardCell.y=Math.min(7,keyboardCell.y+1);hover=keyboardCell;if(e.key==='Enter'&&(campaignAdapter?.placingEye()||!placements.some(u=>u.x===hover.x&&u.y===hover.y)))place(hover);if(e.key==='Delete'){if(campaignAdapter)return campaignAdapter.remove(hover);placements=placements.filter(u=>u.x!==hover.x||u.y!==hover.y);save();updatePanels();}});
$('player-tab').onclick=()=>setSide(0);$('enemy-tab').onclick=()=>setSide(1);$('start').onclick=start;$('reset').onclick=reset;$('preset').onclick=preset;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'继续':'暂停';};$('random-seed').onclick=()=>{if(battle)return toast('回到准备后可更换种子。');const a=new Uint32Array(1);crypto.getRandomValues(a);$('seed').value=a[0];save();};$('clear-side').onclick=()=>{if(battle)return toast('回到准备后再清空阵容。');placements=placements.filter(u=>u.side!==side);save();updatePanels();};$('return').onclick=()=>{$('result').close();reset();};$('replay').onclick=()=>{$('result').close();start();};
$('export').onclick=()=>{if(!battle)return toast('开始战斗后可导出记录。');const blob=new Blob([JSON.stringify(summary(battle),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`autochess-${battle.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('settings-open').onclick=()=>$('settings').showModal();for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();$('reduced').onchange=()=>{reduced=$('reduced').checked;if(reduced)particles=[];};
document.addEventListener('visibilitychange',()=>{accumulator=0;lastFrame=performance.now();if(document.hidden&&running&&!paused){paused=true;$('pause').textContent='继续';}});
if(campaignMode){
 const {mountMatch}=await import('./match-ui.mjs');
 campaignAdapter=mountMatch(data,{cellAt,setPlacements(p,viewSide=0){side=viewSide;placements=structuredClone(p);reset();},startCombat(p,catalog,seed){side=0;battleCatalog=catalog;placements=structuredClone(p);$('seed').value=seed;start();},feedback(kind,unit){tone(kind);effects.add(kind,unit??{x:3,y:5},kind==='upgrade'?2:1);const panel=document.querySelector(kind==='purchase'?'.roster-panel':'.arena-shell');if(panel&&!reduced){panel.classList.remove('feedback-pulse');void panel.offsetWidth;panel.classList.add('feedback-pulse');}},showDetail,showItem:reference.showItem,bindInfo:reference.bind,toast,closeResult(){$('result').close();},reset});
}else{if(!load())preset();renderRoster();updatePanels();}
new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
