import {revealPick,carouselState} from './carousel-rules.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountCarousel({getGame,getOffers,choose,finish,save,cost,describe}){
 const dialog=document.createElement('dialog');dialog.className='carousel-dialog';document.body.append(dialog);dialog.addEventListener('cancel',e=>e.preventDefault());let timer=null,key=null,lastRevealed=0;
 function draw(){const g=getGame(),c=g.carousel;if(g.phase!=='draft'){clearTimeout(timer);dialog.close();key=null;return;}if(!c)return;const visible=c.order.slice(0,c.revealed),current=c.order[c.revealed],human=current===0&&!c.receipts.some(r=>r.player===0),done=c.revealed>=c.order.length;dialog.innerHTML=`<header><small>${esc(c.round)} · ${c.type==='initial'?'启程':'选秀'}</small><h2>${done?'领取完毕':human?'轮到你选择':esc(g.players[current]?.name)+' 正在选择'}</h2></header><div class="carousel-queue">${c.order.map(id=>{const r=c.receipts.find(r=>r.player===id),shown=visible.includes(id);return `<div data-carousel-player="${id}" class="${shown?'picked':current===id?'current':''}"><b>${esc(g.players[id].name)}</b><small>${shown?esc(r?.name??'装备奖励'):g.players[id].hp+'♥'}</small>${shown?'<small>'+esc(r?.item)+'</small>':''}</div>`;}).join('')}</div><div class="carousel-offers">${c.offers.map((o,i)=>{const r=c.receipts.find(r=>r.index===i&&visible.includes(r.player)),available=getOffers()?.[i],d=describe(o.item);return `<button data-carousel-pick="${i}" class="carousel-offer ${r?'claimed':''}" ${human&&available&&!r?'':'disabled'}><span class="carousel-portrait">${esc((o.name??'装备').slice(0,2))}</span><b>${esc(o.name??'装备奖励')}</b><small>${o.name?cost(o.name)+'费':''}</small><strong>${esc(o.item)}</strong><small>${esc(d.stats??'')}</small><span>${r?esc(g.players[r.player].name)+' 已领取':''}</span></button>`;}).join('')}</div>${done?'<button class="primary carousel-finish">返回棋盘</button>':''}`;
 for(const b of dialog.querySelectorAll('[data-carousel-pick]'))b.onclick=()=>{try{choose(+b.dataset.carouselPick);revealPick(g);save();draw();schedule();}catch(e){console.error(e);}};
 dialog.querySelector('.carousel-finish')?.addEventListener('click',()=>{clearTimeout(timer);finish();dialog.close();key=null;});if(!dialog.open)dialog.showModal();if(c.revealed>lastRevealed){const id=c.order[c.revealed-1],r=c.receipts.find(r=>r.player===id),from=dialog.querySelector('[data-carousel-pick="'+r?.index+'"]'),to=dialog.querySelector('[data-carousel-player="'+id+'"]');if(from&&to&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),flight=document.createElement('div');flight.className='carousel-flight';flight.textContent=(r.name??'装备')+' · '+r.item;Object.assign(flight.style,{left:a.x+'px',top:a.y+'px',width:a.width+'px'});dialog.append(flight);const animation=flight.animate([{transform:'translate(0,0)',opacity:1},{transform:'translate('+(b.x-a.x)+'px,'+(b.y-a.y)+'px)',opacity:0}],{duration:800,easing:'cubic-bezier(.25,.7,.3,1)'});animation.onfinish=()=>flight.remove();}}lastRevealed=c.revealed;}
 function schedule(){clearTimeout(timer);const g=getGame(),c=g.carousel;if(g.phase!=='draft'||!c)return;const id=c.order[c.revealed];if(id===undefined||id===0&&!c.receipts.some(r=>r.player===0))return;timer=setTimeout(()=>{if(getGame()!==g||g.phase!=='draft')return;if(revealPick(g)){save();draw();schedule();}},950);}
 return {show(){const g=getGame();if(!g.carousel&&g.phase==='draft')g.carousel=carouselState(g,getOffers(),g.stage===1?'initial':'carousel',[0]);const k=g.seed+':'+g.carousel?.round;if(k!==key){key=k;lastRevealed=g.carousel?.revealed??0;draw();schedule();}else draw();},close(){clearTimeout(timer);dialog.close();key=null;}};
}
