import {carouselCosts,carouselItem,carouselState,recordPick} from './carousel-rules.mjs';
import {focusFor,selectBoard,positionBoard,purchaseScore,economyPlan,gearScore,bestCraft,power} from './ai-planner.mjs';
import {components as gearComponents} from './equipment-data.mjs';
import {metalDefinitions,metalDefinition} from './legendary-traits.mjs';
import {rareSelectors,upgradeFor,normalizeRareItems,rarePreparation} from './rare-augments.mjs';
import {radiants,artifacts,rareItem} from './rare-equipment.mjs';
import {openingEncounter} from './encounters.mjs';
import {buildNeutralLoot,settleNeutralLoot,reservedNeutralCopies,neutralBossItem} from './neutral-loot.mjs';
import {gridmanDefinition} from './gridman.mjs';
import {reconcileItems,removeInventoryItem,refundUnitItems,equipmentIdentity} from './item-ledger.mjs';
import {repairAugmentChoice,prepareAugments,chooseAugment,rerollAugment,augmentPrep,augmentSettle,combatAugments,hasAugment,payRefresh,refreshPrice,applyAugmentXP,augmentImmediate,augmentEquipmentUsed,augmentLegacy} from './augments.mjs';
export {rerollAugment,refreshPrice};
import {inventions,empireUpgrades,boosters} from './specials.mjs';
import {recipe,equipmentName,items as regularItems,emblemTraits} from './equipment.mjs';
// Eight-player economy. No DOM, timers, hidden AI income or independent AI pool.
import {createBattle,runBattle,traitCounts,traitTiers} from './engine.mjs';
export const XP=[0,2,2,6,10,20,36,48,80,84,100];
export const ODDS=[[100,0,0,0,0],[100,0,0,0,0],[75,25,0,0,0],[55,30,15,0,0],[45,33,20,2,0],[30,40,25,5,0],[19,30,40,10,1],[18,25,32,22,3],[10,20,25,35,10],[5,10,20,40,25]];
export const COPIES=[0,30,25,18,10,9];
export const COMPONENTS=['战刃','光弩','光能杖','能量晶石','合金甲','屏障披风','生命腰带','格斗护手'];
export const population=p=>p.level+(p.extraPopulation??0)+p.items.filter(n=>n==='统帅冠冕').length;
const raw=u=>3**(u.star-1);
const assert=(v,msg)=>{if(!v)throw Error(msg);};
function random(g){g.rngState=(g.rngState+0x6D2B79F5)>>>0;let t=g.rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}
const pick=(g,a)=>a[Math.floor(random(g)*a.length)];
const player=(g,id)=>g.players[id];
const definition=(g,name)=>g.catalog.find(u=>u.name===name);
function editable(g,id){assert(g.phase==='prepare','现在不是准备阶段');const p=player(g,id);assert(p?.hp>0,'该玩家已被淘汰');return p;}
function log(g,msg){g.log.unshift(`${roundName(g)} · ${msg}`);g.log=g.log.slice(0,60);}
export const roundName=g=>`${g.stage}-${g.round}`;
export const roundKind=g=>g.stage===1?(g.round===1?'initial':'neutral'):g.round===4?'carousel':g.round===7?'neutral':'pvp';
function addXP(p,n){p.xp+=n;while(p.level<10&&p.xp>=XP[p.level]){p.xp-=XP[p.level];p.level++;}if(p.level===10)p.xp=0;}
function returnShop(g,p){for(const name of p.shop)if(name)g.pool[name]++;p.shop=Array(5).fill(null);}
function draw(g,p,cost=null){
 const banned=new Set(p.units.filter(u=>u.star===3).map(u=>u.name));
 const candidates=g.catalog.filter(u=>g.pool[u.name]>0&&!banned.has(u.name)&&(!cost||u.cost===cost));
 if(!candidates.length)return null;
 const odds=ODDS[Math.min(10,p.level+(hasAugment(p,'高端购物')?1:0))-1];const costs=[1,2,3,4,5].filter(c=>candidates.some(u=>u.cost===c)&&odds[c-1]>0);
 if(!cost&&!costs.length)return null;
 let chosen=cost;if(!chosen){let roll=random(g)*costs.reduce((v,c)=>v+odds[c-1],0);chosen=costs.at(-1);for(const c of costs){roll-=odds[c-1];if(roll<0){chosen=c;break;}}}
 const subset=candidates.filter(u=>u.cost===chosen);if(!subset.length)return null;
 let roll=random(g)*subset.reduce((v,u)=>v+g.pool[u.name],0),name=subset.at(-1).name;
 for(const u of subset){roll-=g.pool[u.name];if(roll<0){name=u.name;break;}}
 g.pool[name]--;return name;
}
function generateShop(g,p){returnShop(g,p);p.shop=Array.from({length:5},()=>draw(g,p));}
function component(g,p){const counts=Object.fromEntries(COMPONENTS.map(n=>[n,p.items.filter(i=>i===n).length]));const allowed=COMPONENTS.filter(n=>counts[n]<3);return pick(g,allowed.length?allowed:COMPONENTS);}
function combine(g,p){
 for(let star=1;star<3;star++)for(const name of g.catalog.map(u=>u.name)){
  let set=p.units.filter(u=>u.name===name&&u.star===star);
  while(set.length>=3){set.sort((a,b)=>(a.location==='board'?0:a.location==='bench'?1:2)-(b.location==='board'?0:b.location==='bench'?1:2)||a.id-b.id);const parts=set.slice(0,3),keep=parts[0];
   for(const part of parts)reconcileItems(p);const trainings=parts.flatMap(part=>part.training??[]).sort((a,b)=>a.round-b.round||a.id-b.id);const discardedTraining=trainings.slice(8);keep.training=trainings.slice(0,8);keep.star++;keep.hero=parts.some(u=>u.hero);keep.evolutions=[...new Set(parts.flatMap(u=>u.evolutions??[]))].slice(0,4);if(parts.some(u=>u.id===p.oathCaptain))p.oathCaptain=keep.id;const memories=parts.map(part=>({...part.permanent}));keep.permanent={};for(const memory of memories)for(const [key,value] of Object.entries(memory))keep.permanent[key]=(keep.permanent[key]??0)+value;for(const t of discardedTraining)keep.permanent[t.attr]-=t.value;const allIds=parts.flatMap(u=>u.itemIds??[]);const allItems=parts.flatMap(u=>u.items??[]),limit=keep.name==='新条茜'?4:3;keep.items=allItems.splice(0,limit);keep.itemIds=allIds.splice(0,limit);for(let i=0;i<allItems.length;i++)p.itemLedger.push({name:allItems[i],id:allIds[i]});p.items.push(...allItems);
   const removed=new Set(parts.slice(1).map(u=>u.id));p.units=p.units.filter(u=>!removed.has(u.id));log(g,`${p.name}的${name}升至${keep.star}星`);set=p.units.filter(u=>u.name===name&&u.star===star);
  }
 }
 claimPending(p);
}
function claimPending(p){for(const u of p.units.filter(u=>u.location==='pending'))if(p.units.filter(u=>u.location==='bench').length<9)u.location='bench';}
function grant(g,p,name,reward=false){
 const canMerge=p.units.filter(u=>u.name===name&&u.star===1).length>=2;
 assert(reward||p.units.filter(u=>u.location==='bench').length<9||canMerge,'备战席已满');
 const u={id:++g.counter,name,star:1,location:p.units.filter(u=>u.location==='bench').length<9?'bench':'pending',x:0,y:4,permanent:{ap:0,kills:0},items:[]};p.units.push(u);combine(g,p);return u;
}
export function buy(g,id,index){const p=editable(g,id),name=p.shop[index];assert(name,'商品已售出');const cost=definition(g,name).cost;assert(p.gold>=cost,'金币不足');grant(g,p,name);p.gold-=cost;p.shop[index]=null;syncSpecials(g,id);}
export function sell(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u,'棋子不存在');const c=definition(g,u.name).cost;p.gold+=u.star===1?c:c===1?raw(u):raw(u)*c-1;g.pool[u.name]+=raw(u);refundUnitItems(p,u);p.items.push(...(u.items??[]));p.units=p.units.filter(w=>w.id!==uid);claimPending(p);syncSpecials(g,id);}
export function refresh(g,id){const p=editable(g,id);payRefresh(g,p);generateShop(g,p);applyAugmentXP(g,p,0,augmentAPI);}
export function buyXP(g,id){const p=editable(g,id);assert(!hasAugment(p,'稳步前进'),'该路线不能购买经验');const cap=hasAugment(p,'孤注一掷')?7:hasAugment(p,'升级咯')?11:10;assert(p.level<cap,'已达到本路线等级上限');if(hasAugment(p,'血色契约')){assert(p.hp>5,'支付生命后必须存活');p.hp-=5;}else{assert(p.gold>=4,'购买经验需要4金币');p.gold-=4;}applyAugmentXP(g,p,hasAugment(p,'升级咯')?7:4,augmentAPI);}
export function lockShop(g,id){const p=editable(g,id);p.locked=!p.locked;}
export function deploy(g,id,uid,x,y){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u&&u.location!=='pending','棋子尚未领取');assert(Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<7&&y>=4&&y<8,'请部署到己方半场');const other=p.units.find(w=>w.location==='board'&&w.x===x&&w.y===y&&w.id!==uid);
 if(u.location==='board'){if(other){other.x=u.x;other.y=u.y;}}else if(other){other.location='bench';}else assert(p.units.filter(w=>w.location==='board').length<population(p),'上场人口已满');
 u.location='board';u.x=x;u.y=y;syncSpecials(g,id);
}
export function bench(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u?.location==='board','棋子未上场');assert(p.units.filter(u=>u.location==='bench').length<9,'备战席已满');u.location='bench';claimPending(p);syncSpecials(g,id);}
function initialChoices(g){g.draft={type:'initial',offers:[],chosen:[]};const receipts=[];for(const p of g.players){if(p.id===0)continue;const name=draw(g,p,1);if(name){grant(g,p,name,true);p.units[0].location='board';p.units[0].x=3;p.units[0].y=4;}const item=component(g,p);p.items.push(item);receipts.push({player:p.id,name,item,index:3+p.id-1});}for(let i=0;i<3;i++){const name=draw(g,g.players[0],1);if(name)g.draft.offers.push({name,item:component(g,g.players[0])});}g.carousel=carouselState(g,[...g.draft.offers,...receipts.map(r=>({name:r.name,item:r.item}))],'initial',[0,1,2,3,4,5,6,7],receipts);}
export function createMatch(catalog,seed=4317,options={}){
 const ready=catalog.filter(u=>u.implemented);assert(ready.some(u=>u.cost===1),'需要一费初始棋子');const g={version:1,augmentsEnabled:Boolean(options.augments),catalog:structuredClone(ready),seed:Number(seed)>>>0,rngState:Number(seed)>>>0,stage:1,round:1,phase:'draft',counter:0,pool:Object.fromEntries(ready.map(u=>[u.name,COPIES[u.cost]])),players:Array.from({length:8},(_,id)=>({id,name:id===0?'你':`星庭 ${id}号`,hp:100,gold:0,level:1,xp:0,units:[],items:[],shop:Array(5).fill(null),locked:false,streak:0,history:[],rank:null,lastIncome:null,componentDebt:0,strategy:id%3})),log:[],battles:[],settled:false,tieOrder:[0,1,2,3,4,5,6,7].sort(()=>0)};
 for(let i=7;i>0;i--){const j=Math.floor(random(g)*(i+1));[g.tieOrder[i],g.tieOrder[j]]=[g.tieOrder[j],g.tieOrder[i]];}
 if(options.encounters||options.encounter!==undefined){const e=openingEncounter(seed,options.encounter);g.encounter={...e};g.encounterAcknowledged=false;if(e.sequence)g.augmentSequence=[...e.sequence];for(const p of g.players){if(e.cost)augmentAPI.reward(g,p,null,e.cost,e.star===2?3:1,e.star);if(e.item)p.items.push(e.item);}}initialChoices(g);return g;
}
function chooseOffer(g,p,index){const o=g.draft.offers[index];assert(o,'选项已被领取');if(o.name)grant(g,p,o.name,true);p.items.push(o.item);recordPick(g,p,o,index);g.draft.offers[index]=null;g.draft.chosen.push(p.id);}
export function chooseDraft(g,index,{defer=false}={}){assert(g.phase==='draft','没有选秀');assert(!g.draft.chosen.includes(0),'已领取');const selectedName=g.draft.offers[index]?.name;chooseOffer(g,g.players[0],index);if(g.draft.type==='initial'){const u=g.players[0].units.find(u=>u.name===selectedName);if(u){u.location='board';u.x=3;u.y=4;}}else for(const id of g.draft.after)autoDraft(g,g.players[id]);if(!defer)finishDraft(g);}
export function finishDraft(g){assert(g.phase==='draft'&&g.draft.chosen.includes(0),'请先领取');for(const o of g.draft.offers)if(o?.name)g.pool[o.name]++;g.draft=null;advance(g);}
function autoDraft(g,p){const options=g.draft.offers.map((o,i)=>({o,i})).filter(v=>v.o);if(!options.length)return;options.sort((a,b)=>draftScore(g,p,b.o)-draftScore(g,p,a.o));chooseOffer(g,p,options[0].i);}
function draftScore(g,p,o){return (o.name?definition(g,o.name).cost*2:0)+p.units.filter(u=>u.name===o.name).length*3;}
function carousel(g){const order=g.players.filter(p=>p.hp>0).sort((a,b)=>a.hp-b.hp||g.tieOrder.indexOf(a.id)-g.tieOrder.indexOf(b.id));g.draft={type:'carousel',offers:[],chosen:[],after:[]};const costs=carouselCosts(g.stage);for(let i=0;i<order.length+1;i++){const start=Math.floor(random(g)*costs.length);let name=null;for(let j=0;j<costs.length&&!name;j++)name=draw(g,{...g.players[0],units:[]},costs[(start+j)%costs.length]);g.draft.offers.push({name,item:carouselItem(g.stage,i,()=>random(g),COMPONENTS,regularItems.map(i=>i[0]).filter(n=>n!=='奇袭手套'),radiants.map(i=>i.name),artifacts.map(i=>i.name))});}g.carousel=carouselState(g,g.draft.offers,'carousel',order.map(p=>p.id));let humanSeen=g.players[0].hp<=0;for(const p of order){if(p.id===0){humanSeen=true;continue;}if(humanSeen)g.draft.after.push(p.id);else autoDraft(g,p);}g.phase='draft';if(g.players[0].hp<=0){for(const id of g.draft.after)autoDraft(g,g.players[id]);for(const o of g.draft.offers)if(o?.name)g.pool[o.name]++;g.draft=null;advance(g);}}
export function advance(g){
 assert(g.phase==='settled'||g.phase==='draft','先完成当前回合');if(g.finished)return;
 if(g.stage===1){if(g.round<4)g.round++;else{g.stage=2;g.round=1;}}else if(g.round<7)g.round++;else{g.stage++;g.round=1;}
 g.battles=[];g.settled=false;g.phase='prepare';for(const p of g.players)returnEmpire(g,p);for(const p of g.players)p.sacrificed=false;if(roundKind(g)==='carousel'){carousel(g);return;}
 const alive=g.players.filter(p=>p.hp>0);for(let i=0;i<8;i++){const p=g.players[(i+g.round+g.stage)%8];if(p.hp<=0)continue;if(g.augmentsEnabled){augmentPrep(g,p,augmentAPI);applyAugmentXP(g,p,hasAugment(p,'稳步前进')?5:hasAugment(p,'阶段训练')?3:2,augmentAPI);}else addXP(p,2);if(!p.locked)generateShop(g,p);}
 for(const p of alive)syncSpecials(g,p.id);prepareAugments(g,augmentAPI);
 log(g,`${roundKind(g)==='neutral'?'野怪':'玩家战'}准备 · ${alive.length}人存活`);
}
function unitScore(g,p,u){const d=definition(g,u.name);const all=traitCounts(p.units.map(u=>({...u,traits:definition(g,u.name).traits})));return u.star*20+d.cost*3+d.traits.reduce((v,t)=>v+Math.min(3,all[t]??0),0)+(u.permanent.ap??0)*.05;}
function arrange(g,p){const board=selectBoard(p,g.catalog,traitTiers,population(p));positionBoard(board,g.catalog,p);}
export function aiTurn(g,id){const p=editable(g,id);assert(id!==0,'玩家阵容不由AI操作');
 const defs=new Map(g.catalog.map(d=>[d.name,d]));p.centuryPeace=hasAugment(p,'世纪和解');p.aiFocus=focusFor(p,defs,traitTiers);const plan=economyPlan(g,p),reserve=plan.reserve;let actions=0;
 const targetLevel=Math.min(hasAugment(p,'孤注一掷')?7:9,plan.rerollTarget?Math.max(5,p.level):plan.targetLevel);while(!hasAugment(p,'稳步前进')&&p.level<targetLevel&&(hasAugment(p,'血色契约')?p.hp>35:p.gold>=4+reserve)&&actions++<15)buyXP(g,id);
 arrange(g,p);for(let attempt=0;attempt<=plan.rolls;attempt++){const offers=p.shop.map((name,i)=>({name,i})).filter(o=>o.name).sort((a,b)=>purchaseScore(p,defs.get(b.name),defs,traitTiers)-purchaseScore(p,defs.get(a.name),defs,traitTiers));for(const o of offers){const d=defs.get(o.name),score=purchaseScore(p,d,defs,traitTiers);if(score<0||p.gold<d.cost+reserve)continue;const copy=p.units.some(u=>u.name===o.name),relevant=d.traits.some(t=>p.aiFocus.includes(t));if(!copy&&!relevant&&p.units.length>=population(p)+2&&score<35)continue;const full=p.units.filter(u=>u.location==='bench').length>=9,merge=p.units.filter(u=>u.name===o.name&&u.star===1).length>=2;if(full&&!merge){const spare=p.units.filter(u=>u.location==='bench'&&u.star===1&&!u.items.length&&p.units.filter(w=>w.name===u.name).length===1).sort((a,b)=>purchaseScore(p,defs.get(a.name),defs,traitTiers)-purchaseScore(p,defs.get(b.name),defs,traitTiers))[0];if(!spare||purchaseScore(p,defs.get(spare.name),defs,traitTiers)>=score)continue;sell(g,id,spare.id);}if(p.units.filter(u=>u.location==='bench').length<9||p.units.filter(u=>u.name===o.name&&u.star===1).length>=2)buy(g,id,o.i);}arrange(g,p);if(attempt===plan.rolls||p.gold<reserve+6)break;refresh(g,id);}
 arrange(g,p);for(const u of p.units.filter(u=>u.name==='赛罗'))while(zeroChoices(u).length){chooseEvolution(g,id,u.id,zeroChoices(u)[0]);}const knights=p.units.filter(u=>u.location==='board'&&unitTraits(g,u).includes('骑士之誓')).sort((a,b)=>unitScore(g,p,b)-unitScore(g,p,a));if(knights.length)p.oathCaptain=knights[0].id;syncSpecials(g,id);if(p.scienceOffers?.length)chooseInvention(g,id,0);for(const name of p.inventions??[])if(!(p.activeInventions??[]).includes(name)&&(p.activeInventions??[]).length<(hasAugment(p,'紧急预案')?3:2)){try{toggleInvention(g,id,name);}catch{}}for(let i=0;i<3;i++)if(p.empireShop?.[i]){try{buyEmpire(g,id,i);}catch{}}
 const amplifierUsers=p.units.filter(u=>u.location==='board'&&boosters[u.name]);for(const u of amplifierUsers){try{setBooster(g,id,u.id,boosters[u.name]);}catch{}}
 if(p.itemChoice)chooseItem(g,id,0);for(let i=0;i<p.items.length;i++)if(['神器选择器','神器四选一','光明装备选择器','光明圣物选择器','普通成装选择器','纹章选择器','组件选择器','复制组件选择器'].includes(p.items[i])){openItemSelector(g,id,i);chooseItem(g,id,0);i--;}
 for(let i=0;i<p.items.length;i++)if(['普通复制器','低费复制器'].includes(p.items[i])){const u=p.units.filter(w=>definition(g,w.name).cost<=(p.items[i]==='低费复制器'?3:5)&&w.star<3&&g.pool[w.name]>0).sort((a,b)=>unitScore(g,p,b)-unitScore(g,p,a))[0];if(u){useCopy(g,id,u.id,i);i--;}}
 for(let i=0;i<p.items.length;i++)if(p.items[i]==='光明升级器'){const u=p.units.filter(u=>u.items.some(upgradeFor)).sort((a,b)=>unitScore(g,p,b)-unitScore(g,p,a))[0];if(u){upgradeRadiant(g,id,u.id,i);i--;}}
 for(let n=0;n<8;n++){const craft=bestCraft(p,g.catalog,recipe,gearComponents,regularItems);if(!craft)break;combineInventory(g,id,craft.i,craft.j);}
 for(let index=0;index<p.items.length;){const item=p.items[index];if(!equipmentName(item)){index++;continue;}const targets=p.units.filter(u=>u.location==='board').sort((a,b)=>gearScore(item,b,definition(g,b.name),p,gearComponents,regularItems)-gearScore(item,a,definition(g,a.name),p,gearComponents,regularItems));let equipped=false;for(const u of targets){try{equip(g,id,u.id,index);equipped=true;break;}catch{ /* Try another legal equipment slot. */ }}if(!equipped)index++;}
}
function pair(g){const active=g.players.filter(p=>p.hp>0).map(p=>p.id);for(let i=active.length-1;i>0;i--){const j=Math.floor(random(g)*(i+1));[active[i],active[j]]=[active[j],active[i]];}
 const memo=new Map();function search(ids){if(ids.length<2)return {cost:0,pairs:[],ghost:ids[0]};const key=ids.join(',');if(memo.has(key))return memo.get(key);let best={cost:Infinity};const a=ids[0];for(let i=1;i<ids.length;i++){const b=ids[i],past=g.players[a].history,other=g.players[b].history;const penalty=(past.at(-1)===b||other.at(-1)===a?100:0)+(past.at(-2)===b||other.at(-2)===a?10:0);const rest=search(ids.filter(id=>id!==a&&id!==b));if(penalty+rest.cost<best.cost)best={cost:penalty+rest.cost,pairs:[[a,b],...rest.pairs],ghost:rest.ghost};}memo.set(key,best);return best;}const result=search(active);const plans=result.pairs.map(([a,b])=>({a,b,ghost:false}));if(result.ghost!==undefined){const a=result.ghost,candidates=active.filter(id=>id!==a),recent=g.players[a].history,eligible=candidates.filter(id=>!recent.includes(id));const b=pick(g,eligible.length?eligible:candidates);plans.push({a,b,ghost:true});}return plans;
}
function team(g,id,side){const p=player(g,id),target=p.units.find(u=>u.location==='board'&&u.name==='杰顿'&&u.id===p.zettonTarget)??p.units.find(u=>u.location==='board'&&u.name==='杰顿');return p.units.filter(u=>u.location==='board').map(u=>({name:u.name,star:u.star,hero:u.hero??false,instanceId:u.id,side,x:side===0?u.x:6-u.x,y:side===0?u.y:7-u.y,permanent:{...u.permanent,...(p.cocoonBoost&&u===target?{hp:(u.permanent.hp??0)+definition(g,u.name).hp*[1,1.8,3.24][u.star-1]*.2,adPercent:(u.permanent.adPercent??0)+.2,ap:(u.permanent.ap??0)+20}: {})},cocoonBoost:p.cocoonBoost&&u===target,items:[...(u.items??[])],booster:u.booster??null,evolutions:[...(u.evolutions??[])],oathCaptain:u.id===p.oathCaptain,matchEffects:{augments:combatAugments(p),augmentTargets:p.augmentTargets??[],population:population(p),pilotId:p.pilotId??null,robotPosition:(()=>{const driver=p.units.find(w=>w.id===p.pilotId&&w.location==='board'),pos=p.robotPosition??(driver?{x:driver.x,y:driver.y}:{x:0,y:4});return side===0?pos:{x:6-pos.x,y:7-pos.y};})(),resonanceId:p.resonanceId??null,soloId:p.soloId??null,activeInventions:[...(p.activeInventions??[])],empireUpgrades:{...p.empireUpgrades},metalPositions:Object.fromEntries(previewMetal(g,id,side).map(u=>[u.name,{x:u.x,y:u.y}]))},eyePosition:u.eyePosition?side===0?u.eyePosition:{x:6-u.eyePosition.x,y:7-u.eyePosition.y}:null}));}
export function previewTeam(g,id,side=0){return team(g,id,side);}
export function neutrals(g){const stage=g.stage,n=stage===1?g.round-1:stage===2?3:stage===3?4:stage===4?2:stage===5?1:3;const hp=stage===1?[0,0,250,280,300][g.round]:stage===2?600:stage===3?900:stage===4?1800:stage===5?4500:2500*(1+.1*(stage-6));const ad=stage===1?g.round===4?30:25:stage===2?45:stage===3?60:stage===4?80:stage===5?120:100*(1+.1*(stage-6));return Array.from({length:n},(_,i)=>({name:`${g.stage===1?'异星幼兽':g.stage===2?'岩甲兽':g.stage===3?'暗羽兽':g.stage===4?'异星守卫':g.stage===5?'熔核巨兽':'远古守卫'}${n>1?'·'+(i+1):''}`,cost:0,traits:[],hp,ad,as:stage===1?.55:stage<=4?.6:.65,armor:stage===1?g.round===4?10:0:Math.min(50,stage*10),mr:stage===1?g.round===4?10:0:Math.min(50,stage*10),range:1,mana:null,implemented:true,special:true,neutral:true,npcStage:stage,skill:stage>=4?'定时释放范围攻击；击败后掉落战利品。':'近战野怪；击败后掉落战利品。'}));}
export function beginRound(g){assert(g.phase==='prepare','当前回合不能再次开战');assert(!g.players[0].augmentChoice,'请先选择本轮强化');for(const p of g.players)if(p.hp>0)configureAugmentTargets(g,p);for(const p of g.players)if(p.id>0&&p.hp>0)aiTurn(g,p.id);g.phase='combat';g.settled=false;
 const plans=roundKind(g)==='neutral'?g.players.filter(p=>p.hp>0).map(p=>({a:p.id,b:null,ghost:false})):pair(g);
 g.battles=plans.map((original,index)=>{const plan=original.b===0&&!original.ghost?{...original,a:0,b:original.a}:original;let placements,catalog=g.catalog,loot=null;if(plan.b===null){const npc=neutrals(g);loot=buildNeutralLoot(g,g.players[plan.a],npc,{reserve:(g,p,cost)=>draw(g,p,cost)});catalog=[...catalog,...npc];placements=[...team(g,plan.a,0),...npc.map((u,i)=>({name:u.name,star:1,side:1,x:[3,2,4,1][i],y:2,neutral:true,items:g.stage>=5?[neutralBossItem(g,plan.a)]:[],neutralLoot:loot[i]}))];}else placements=[...team(g,plan.a,0),...team(g,plan.b,1)];const aCount=placements.filter(p=>p.side===0).length,bCount=placements.filter(p=>p.side===1).length;
 return {...plan,neutralLoot:loot,index,seed:Math.floor(random(g)*4294967296),placements,catalog,empty:!aCount||!bCount,winner:!aCount&&!bCount?null:!aCount?1:!bCount?0:undefined,state:null};});
 const human=g.battles.find(b=>b.a===0||b.b===0&&!b.ghost);
 for(const b of g.battles)if(b!==human&&!b.empty)b.state=runBattle(createBattle(b.catalog,b.placements,b.seed));
 return human??null;
}
function income(g,p,outcome,neutral){if(!neutral){p.streak=outcome===null?0:outcome===0?Math.max(0,p.streak)+1:Math.min(0,p.streak)-1;}const win=!neutral&&outcome===0?1:0;p.gold+=win;const interest=Math.min(hasAugment(p,'对冲基金')?10:hasAugment(p,'利滚利')?7:5,Math.floor(p.gold/10)),streak=Math.abs(p.streak),bonus=streak>=6?3:streak>=5?2:streak>=3?1:0,base=g.stage===1?2:g.stage===2&&g.round===1?3:g.stage===2&&g.round===2?4:5;p.gold+=interest+bonus+base;p.lastIncome={win,interest,streak:bonus,base,total:win+interest+bonus+base};}
function persist(g,p,b,side){for(const live of b.state?.units??[]){if(live.side!==side||live.special)continue;const owned=p.units.find(u=>u.id===live.instanceId);if(owned){owned.permanent={...live.permanent};const placement=b.placements.find(u=>u.instanceId===owned.id&&u.side===side);if(placement?.cocoonBoost){owned.permanent.hp-=definition(g,owned.name).hp*[1,1.8,3.24][owned.star-1]*.2;owned.permanent.adPercent-=.2;owned.permanent.ap-=20;}}}}
function boardTraits(g,p){const units=p.units.filter(u=>u.location==='board').map(u=>({...u,traits:unitTraits(g,u),matchEffects:{augments:combatAugments(p)}}));if((traitCounts(units)['宿敌']??0)>=1)for(const u of units)if(u.name==='赛罗')u.traits=[...new Set([...u.traits,...(u.evolutions??[])])];return traitCounts(units);}
function reservedReward(g,p,name){if(g.pool[name]>0){g.pool[name]--;grant(g,p,name,true);return true;}return false;}
function roundRewards(g,p,outcome){
 const counts=boardTraits(g,p);
 if((counts['金属狂潮']??0)>=3){p.metalRounds=(p.metalRounds??0)+1;if(p.metalRounds>=4){p.metalRounds-=4;p.items.push('金属狂潮纹章');log(g,`${p.name}获得金属纹章`);}}
 if(p.units.some(u=>u.location==='board'&&u.name==='镜子骑士')){const target=p.units.find(u=>u.id===p.mirrorTarget&&u.location==='bench');if(target){p.mirrorRounds=(p.mirrorRounds??0)+1;if(p.mirrorRounds>=definition(g,target.name).cost){if(reservedReward(g,p,target.name)){p.mirrorRounds=0;log(g,`${p.name}的镜格复制${target.name}`);}/* A depleted pool waits without creating copies. */}}else{p.mirrorTarget=null;p.mirrorRounds=0;}}
 const zetton=p.units.find(u=>u.location==='board'&&u.id===p.zettonTarget&&u.name==='杰顿')??p.units.find(u=>u.location==='board'&&u.name==='杰顿');
 if(!zetton||outcome===null){p.cocoon=0;return;}p.zettonTarget=zetton.id;
 if(outcome===1){p.cocoon=Math.min(250,(p.cocoon??0)+[10,15,20,25,30][Math.min(4,Math.abs(p.streak)-1)]);return;}
 if(p.cocoon>0){const rank=[30,70,120,180,250].findLastIndex(n=>p.cocoon>=n);p.cocoon=0;if(rank<0)return;p.gold+=[8,15,25,35,50][rank];for(let i=0;i<[1,2,0,0,0][rank];i++)p.items.push(component(g,p));for(let i=0;i<[0,0,1,2,2][rank];i++)p.items.push('普通成装选择器');for(let i=0;i<[0,0,1,2,3][rank];i++)if(!reservedReward(g,p,'杰顿'))p.gold+=3;if(rank===4){if(p.cocoonBoost)p.gold+=15;p.cocoonBoost=true;}log(g,`${p.name}兑现宇宙恐龙之茧`);return;}
 const gain=Math.min(5,p.streak);zetton.permanent.adPercent=(zetton.permanent.adPercent??0)+gain*.01;zetton.permanent.ap+=gain;
}
function survivorDamage(b,side){if(b.empty)return b.placements.filter(u=>u.side===side).length;const alive=(b.state?.units??[]).filter(u=>u.side===side&&u.hp>0);return alive.filter(u=>!u.special).length+(alive.some(u=>u.special)?1:0);}
function damage(g,b,side,outcome){if(b.b===null)return outcome===0?0:2;const base=[0,0,0,3,5,8,10,12][Math.min(7,g.stage)]??15;const scaled=g.stage>=8?15:base;if(outcome===null)return Math.max(1,scaled);return outcome===0?0:scaled+survivorDamage(b,1-side);}
export function settleRound(g,humanState=null){assert(g.phase==='combat'&&!g.settled,'本回合已结算');const human=g.battles.find(b=>b.a===0||b.b===0&&!b.ghost);if(human&&!human.empty){assert(humanState?.finished,'玩家战斗尚未结束');human.state=humanState;}const before=g.players.map(p=>p.hp);const eliminated=[];
 for(const b of g.battles){const winner=b.empty?b.winner:b.state.winner;
  for(const side of [0,1]){if(side===1&&(b.b===null||b.ghost))continue;const p=player(g,side===0?b.a:b.b),outcome=winner===null?null:winner===side?0:1;const loss=damage(g,b,side,outcome);p.eliminationHp=p.hp-loss;p.hp=Math.max(0,p.eliminationHp);p.lastBattle={outcome,loss,opponent:side===0?b.b:b.a,ghost:b.ghost};persist(g,p,b,side);income(g,p,outcome,b.b===null);
   if(b.b!==null){if(p.hp>0){roundRewards(g,p,outcome);settleSpecials(g,p,b,side,outcome);}p.history.push(side===0?b.b:b.a);p.history=p.history.slice(-2);}else {settleNeutralLoot(g,p,b,outcome,{grant:(g,p,name)=>grant(g,p,name,true)});}
   if(g.augmentsEnabled)augmentSettle(g,p,outcome,b.b===null,augmentAPI);if(p.hp===0)eliminated.push(p);log(g,`${p.name}${outcome===0?'获胜':outcome===null?'平局':'落败'}${loss?`，损失${loss}生命`:''}`);
  }
 }
 if(g.augmentsEnabled)augmentLegacy(g,eliminated,augmentAPI);const previouslyRanked=g.players.filter(p=>p.rank!==null).length;eliminated.sort((a,b)=>a.eliminationHp-b.eliminationHp||before[a.id]-before[b.id]||(a.lastBattle?.opponent===b.id?(a.lastBattle.outcome===0?1:a.lastBattle.outcome===1?-1:0):0)||g.tieOrder.indexOf(a.id)-g.tieOrder.indexOf(b.id));for(let i=0;i<eliminated.length;i++){const p=eliminated[i];p.rank=8-previouslyRanked-i;returnShop(g,p);returnEmpire(g,p);for(const u of p.units)g.pool[u.name]+=raw(u);p.units=[];}
 const alive=g.players.filter(p=>p.hp>0);if(alive.length<=1){if(alive[0])alive[0].rank=1;g.finished=true;}g.phase='settled';g.settled=true;
 return g.players[0].lastBattle;
}
export function poolAudit(g){const expected=Object.fromEntries(g.catalog.map(u=>[u.name,COPIES[u.cost]])),actual={...g.pool};for(const p of g.players){for(const name of p.shop)if(name)actual[name]++;for(const o of p.empireShop??[])if(o?.unit)actual[o.unit]++;for(const u of p.units)actual[u.name]+=raw(u);}for(const o of g.draft?.offers??[])if(o?.name)actual[o.name]++;for(const name of reservedNeutralCopies(g))actual[name]++;return Object.keys(expected).every(n=>actual[n]===expected[n]&&g.pool[n]>=0);}
export function restoreMatch(saved,catalog){assert(saved?.version===1&&Array.isArray(saved.players)&&saved.players.length===8,'不支持的存档');const g=structuredClone(saved);g.catalog=structuredClone(catalog.filter(u=>u.implemented));assert(['prepare','draft','settled'].includes(g.phase),'只恢复准备或结算阶段');assert(g.players.every(p=>Number.isFinite(p.gold)&&p.gold>=0&&p.level>=1&&p.level<=11&&(p.level<=10||hasAugment(p,'升级咯'))&&p.units.every(u=>[1,2,3].includes(u.star)&&definition(g,u.name))),'存档属性无效');for(const d of g.catalog)if(!(d.name in g.pool))g.pool[d.name]=COPIES[d.cost];assert(poolAudit(g),'存档卡池损坏');g.battles=[];const legacy={'光刃':'战刃','能量核心':'光能杖','疾风引擎':'光弩','装甲板':'合金甲','防护斗篷':'屏障披风','生命晶核':'生命腰带','能量电池':'能量晶石'};for(const p of g.players){p.componentDebt??=0;p.items=p.items.map(n=>legacy[n]??n);repairAugmentChoice(g,p);}for(const o of g.draft?.offers??[])if(o)o.item=legacy[o.item]??o.item;return g;}

export function equip(g,id,uid,index){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u&&u.location!=='pending','请选择已领取的棋子');const item=p.items[index];if(item==='光明升级器')return upgradeRadiant(g,id,uid,index);assert(equipmentName(item),'该物品暂不能穿戴');u.items??=[];const limit=u.name==='新条茜'?4:3;assert(!u.items.includes('奇袭手套'),'奇袭手套占满装备栏');const componentIndex=u.items.findIndex(n=>recipe(n,item));const combined=componentIndex>=0?recipe(u.items[componentIndex],item):null;const result=combined??item;assert(!['水银护符','夜幕战衣','奇袭手套'].includes(result)||!u.items.includes(result),'该装备每名只能一件');if(result.endsWith('纹章')){const trait=result.slice(0,-2);assert(!definition(g,u.name).traits.includes(trait)&&!u.items.includes(result),'已有该羁绊');}assert(result!=='奇袭手套'||u.items.length===(combined?1:0),'奇袭手套需要空余的全部装备栏');assert(combined||u.items.length<limit,'装备栏已满');const incoming=removeInventoryItem(p,index);p.items.splice(index,1);equipmentIdentity(p,u,componentIndex,incoming,combined);if(combined)u.items.splice(componentIndex,1,result);else u.items.push(item);syncSpecials(g,id);augmentEquipmentUsed(g,p,u,result,augmentAPI);log(g,`${p.name}为${u.name}装备${result}`);}
export function combineInventory(g,id,first,second){const p=editable(g,id);assert(first!==second,'需要两件独立组件');const name=recipe(p.items[first],p.items[second]);assert(name,'这两件物品不能合成');const high=Math.max(first,second),low=Math.min(first,second);removeInventoryItem(p,high);p.items.splice(high,1);removeInventoryItem(p,low);p.items.splice(low,1);p.items.push(name);normalizeRareItems(g,p);return p.items.at(-1);}
export function removeEquipment(g,id,uid,index){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u?.items?.[index],'该装备不存在');const remover=p.items.indexOf('拆卸器');assert(remover>=0,'需要拆卸器');removeInventoryItem(p,remover);p.items.splice(remover,1);refundUnitItems(p,u);p.items.push(...u.items);u.items=[];u.itemIds=[];syncSpecials(g,id);}

const sacrificeRoles={hp:'杰克 哥尔赞 达达 美尔巴 古雷格尔人 机械哥莫拉 艾安隆 雷德王 武士圣剑 杰顿 维克特利 盖亚 乔尼亚斯 金古桥 奥特之父 镜子骑士',ad:'初代 阿斯特拉 红莲火焰 戴拿 赛罗 贝利亚 奈克瑟斯 阿古茹 捷德 雷欧 安奇 梦比优斯 响裕太 泽塔 泰罗',as:'詹伯特 达克戈内 邪恶迪迦 欧布 麦克斯 黑暗洛普斯 新条茜 詹奈',ap:'阿诺西拉斯 庞顿 艾斯 迪迦 佐菲 亚波人 银河 托雷基亚',crit:'马格马星人 基里艾洛德人 艾斯杀手',armor:'皮古蒙 内海将 宝多六花 赛文 爱迪 巴尔坦星人 希卡利 高斯'};
export function sacrifice(g,id,uid,gatanId){const p=editable(g,id),u=p.units.find(u=>u.id===uid),gatan=p.units.find(u=>u.id===gatanId&&u.name==='加坦杰厄'&&u.location==='board');assert(!p.sacrificed,'本准备阶段已献祭');assert(gatan&&u&&u.location==='bench'&&u.name!=='加坦杰厄','需要登场的加坦杰厄及备战席祭品');const role=Object.keys(sacrificeRoles).find(k=>sacrificeRoles[k].split(' ').includes(u.name));assert(role,'祭品定位未注册');const points=[0,5,8,12,16,20][definition(g,u.name).cost]*[1,2.5,8][u.star-1],gain=points*({hp:15,ad:1,as:.005,ap:1,crit:.005,armor:.5}[role]);gatan.permanent[role]=(gatan.permanent[role]??0)+gain;if(role==='armor')gatan.permanent.mr=(gatan.permanent.mr??0)+gain;refundUnitItems(p,u);p.items.push(...(u.items??[]));g.pool[u.name]+=raw(u);p.units=p.units.filter(w=>w!==u);p.sacrificed=true;claimPending(p);log(g,`${p.name}献祭${u.name}强化加坦杰厄`);}
export function setMirror(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u?.location==='bench','镜格目标必须留在备战席');assert(p.units.some(w=>w.name==='镜子骑士'&&w.location==='board'),'需要镜子骑士登场');if(p.mirrorTarget!==uid){p.mirrorTarget=uid;p.mirrorRounds=0;}}
export function moveEye(g,id,uid,x,y){const p=editable(g,id),u=p.units.find(u=>u.id===uid&&u.name==='托雷基亚');assert(u&&Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<7&&y>=4&&y<8,'眼睛必须放在己方半场');u.eyePosition={x,y};}
export function openItemSelector(g,id,index){const p=editable(g,id),name=p.items[index];assert(!p.itemChoice,'先领取当前选择');assert(['神器选择器','神器四选一','光明装备选择器','光明圣物选择器','普通成装选择器','纹章选择器','组件选择器','复制组件选择器'].includes(name),'该物品不是选择器');const available=rareSelectors[name]?(rareSelectors[name].type==='神器'?artifacts:radiants).map(i=>i.name):name.includes('组件')?[...COMPONENTS]:name==='纹章选择器'?emblemTraits.map(t=>t+'纹章'):regularItems.map(i=>i[0]).filter(n=>n!=='奇袭手套'),offers=[];while(offers.length<(rareSelectors[name]?.size??(name==='复制组件选择器'?8:3)))offers.push(available.splice(Math.floor(random(g)*available.length),1)[0]);removeInventoryItem(p,index);p.items.splice(index,1);p.itemChoice=offers;p.itemChoiceKind=name;}
export function chooseItem(g,id,index){const p=editable(g,id);assert(p.itemChoice?.[index],'请选择一件合法奖励');const selected=p.itemChoice[index];p.items.push(selected);if(p.itemChoiceKind==='复制组件选择器'){p.duplicateComponent=selected;p.duplicateRemaining=2;}p.itemChoice=p.itemChoiceQueue?.shift()??null;p.itemChoiceKind=p.itemChoice?'遗产回收':null;normalizeRareItems(g,p);}
export function reforge(g,id,uid,index){const p=editable(g,id),u=p.units.find(u=>u.id===uid),name=u?.items?.[index],tool=p.items.indexOf('重铸器');assert(tool>=0,'需要重铸器');const allowed=rareItem(name)?(rareItem(name).type==='神器'?artifacts:radiants).map(i=>i.name).filter(n=>n!==name):regularItems.some(i=>i[0]===name)?regularItems.map(i=>i[0]).filter(n=>n!==name):name?.endsWith('纹章')?emblemTraits.map(t=>t+'纹章').filter(n=>n!==name&&!definition(g,u.name).traits.includes(n.slice(0,-2))&&!(u.items??[]).includes(n)):[];assert(allowed.length,'只能重铸成装或纹章');assert(!u.items.includes('奇袭手套'),'先拆下奇袭手套');const legal=allowed.filter(n=>(n!=='奇袭手套'||u.items.length===1)&&(!['水银护符','夜幕战衣'].includes(n)||!u.items.includes(n)));assert(legal.length,'没有合法重铸结果');const result=pick(g,legal);removeInventoryItem(p,tool);p.items.splice(tool,1);u.items[index]=result;u.itemIds[index]=null;normalizeRareItems(g,p);reconcileItems(p);return u.items[index];}

function returnEmpire(g,p){for(const offer of p.empireShop??[])if(offer?.unit)g.pool[offer.unit]++;p.empireShop=null;}
export function syncSpecials(g,id){
 if(g.phase!=='prepare')return;const p=player(g,id);rarePreparation(g,p);configureAugmentTargets(g,p);const counts=boardTraits(g,p),knightSlots=(counts['宇宙骑士队']??0)>=2?((counts['宇宙骑士队']??0)>=4?2:1)+(hasAugment(p,'骑士零件库')?1:0):0;
 for(const u of p.units)if(u.location!=='board'||!knightSlots)u.booster=null;
 const active=p.units.filter(u=>u.location==='board'&&u.booster),used=new Set();for(const u of active){if(used.size>=knightSlots||used.has(u.booster))u.booster=null;else used.add(u.booster);}
 const rank=counts['银河帝国']??0;if(rank<2||p.hp<=0){returnEmpire(g,p);return;}
 const key=roundName(g);if(p.empireRound===key)return;p.empireRound=key;returnEmpire(g,p);p.empireShop=[];
 for(let i=0;i<2;i++){const available=g.catalog.filter(d=>d.traits.includes('银河帝国')&&g.pool[d.name]>0&&(d.cost<=3||rank>=4)&&(d.cost<5||p.level>=8));const d=pick(g,available);if(d){g.pool[d.name]--;p.empireShop.push({unit:d.name,price:[0,3,6,9,12,18][d.cost]});}else p.empireShop.push(null);}
 if(hasAugment(p,'帝国的军械库')&&p.empireArmory){p.empireShop.push(random(g)<.5?{item:pick(g,COMPONENTS),price:8}:{item:pick(g,regularItems.map(i=>i[0]).filter(n=>n!=='奇袭手套')),price:16});return;}const upgrades=empireUpgrades.filter(d=>(p.empireUpgrades?.[d.name]??0)<5);p.empireShop.push(upgrades.length?{...pick(g,upgrades)}:{name:'军需补给',price:4});
}
export function buyEmpire(g,id,index){const p=editable(g,id),o=p.empireShop?.[index];assert((boardTraits(g,p)['银河帝国']??0)>=2,'需要银河帝国羁绊');assert(o,'商品已售出');assert((p.empireCoins??0)>=o.price,'帝国币不足');if(o.unit)grant(g,p,o.unit);else if(o.item)p.items.push(o.item);else if(o.name==='军需补给')p.gold+=2;else{p.empireUpgrades??={};assert((p.empireUpgrades[o.name]??0)<5,'该强化已经满级');p.empireUpgrades[o.name]=(p.empireUpgrades[o.name]??0)+1;}normalizeRareItems(g,p);p.empireCoins-=o.price;p.empireShop[index]=null;log(g,`${p.name}购买${o.unit??o.name}`);}
export function chooseInvention(g,id,index){const p=editable(g,id),name=p.scienceOffers?.[index];assert(name,'请选择科学发明');p.inventions??=[];assert(!p.inventions.includes(name),'已拥有该发明');p.inventions.push(name);p.scienceOffers=null;log(g,`${p.name}获得${name}`);}
export function toggleInvention(g,id,name){const p=editable(g,id);assert(p.inventions?.includes(name),'尚未获得该发明');p.activeInventions??=[];if(p.activeInventions.includes(name)){p.activeInventions=p.activeInventions.filter(n=>n!==name);return;}assert(p.activeInventions.length<(hasAugment(p,'紧急预案')&&(boardTraits(g,p)['科学家']??0)>=2?3:2),'已达到发明启用上限');const d=inventions.find(d=>d.name===name);assert(!p.activeInventions.some(n=>inventions.find(d=>d.name===n)?.group===d.group),'同类基础和高级发明不能同时启用');p.activeInventions.push(name);}
export function setBooster(g,id,uid,name){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u?.location==='board','强化器只给登场骑士');if(!name){u.booster=null;return;}assert(boosters[u.name]===name,'该强化器与角色不匹配');const count=boardTraits(g,p)['宇宙骑士队']??0,slots=count>=2?(count>=4?2:1)+(hasAugment(p,'骑士零件库')?1:0):0;assert(slots>0,'需要宇宙骑士队羁绊');const other=p.units.filter(w=>w!==u&&w.location==='board'&&w.booster);assert(!other.some(w=>w.booster===name),'同类强化器最多一个');assert(other.length<slots,'强化器槽位已满');u.booster=name;}
function settleSpecials(g,p,b,side,outcome){const counts=b.state?.traits?.[side]?.counts??boardTraits(g,p),empire=counts['银河帝国']??0;
 if(empire>=2){const kills=(b.state?.units??[]).filter(u=>u.side===side&&!u.special).reduce((n,u)=>n+(u.empireKills??0),0);p.empireCoins=(p.empireCoins??0)+kills*(empire>=4?2:1)+(outcome===null?0:outcome===0?empire>=4?5:3:empire>=4?2:1);}
 const scientists=counts['科学家']??0;if(scientists<2)return;p.scienceRounds=(p.scienceRounds??0)+1;const interval=scientists>=4?3:4;if(p.scienceRounds<interval||p.scienceOffers?.length)return;p.scienceRounds-=interval;const advanced=scientists>=3,available=inventions.filter(d=>d.advanced===advanced&&!(p.inventions??[]).includes(d.name)).map(d=>d.name);if(!available.length){p.gold+=advanced?8:4;return;}p.scienceOffers=[];while(available.length&&p.scienceOffers.length<3)p.scienceOffers.push(available.splice(Math.floor(random(g)*available.length),1)[0]);
}

export const zeroEvolutions=['正义使者','法师','格斗家','狂战士'];
export function zeroChoices(u){return u.name==='赛罗'&&[8,16,32,64].filter(n=>(u.permanent.rivalKills??0)>=n).length>(u.evolutions??[]).length?zeroEvolutions.filter(t=>!u.evolutions?.includes(t)):[];}
export function chooseEvolution(g,id,uid,trait){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u&&zeroChoices(u).includes(trait),'尚未解锁或已经选择该成长羁绊');u.evolutions??=[];u.evolutions.push(trait);log(g,`${p.name}的赛罗获得${trait}`);}
function unitTraits(g,u){return [...definition(g,u.name).traits,...(u.items??[]).filter(n=>n.endsWith('纹章')).map(n=>n.slice(0,-2))];}
export function setCaptain(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u?.location==='board'&&unitTraits(g,u).includes('骑士之誓'),'队长必须是登场的骑士之誓成员');assert((boardTraits(g,p)['骑士之誓']??0)>=2,'需要激活骑士之誓');p.oathCaptain=uid;}
export const metalUnits=metalDefinitions;
export function previewMetal(g,id,side=0){const p=player(g,id),count=boardTraits(g,p)['金属狂潮']??0,occupied=new Set(p.units.filter(u=>u.location==='board').map(u=>`${u.x},${u.y}`)),list=[];if(hasAugment(p,'钢铁驾驭')&&count>=3){const pilot=p.units.find(u=>u.id===p.pilotId&&u.location==='board'),pos=p.robotPosition??(pilot?{x:pilot.x,y:pilot.y}:{x:0,y:4});list.push({name:'驾驭机器人',side,star:1,x:side===0?pos.x:6-pos.x,y:side===0?pos.y:7-pos.y,special:true,previewMetal:true});occupied.add(pos.x+','+pos.y);}const grid=previewGrid(g,id,side,occupied);if(grid){list.push(grid);occupied.add(`${side===0?grid.x:6-grid.x},${side===0?grid.y:7-grid.y}`);}for(const d of metalUnits.filter(d=>count>=d.threshold)){let pos=p.metalPositions?.[d.name];if(!pos||!Number.isInteger(pos.x)||!Number.isInteger(pos.y)||pos.x<0||pos.x>6||pos.y<4||pos.y>7||occupied.has(`${pos.x},${pos.y}`)){pos=null;for(const y of d.range===1?[4,5,6,7]:[7,6,5,4]){const x=[3,2,4,1,5,0,6].find(x=>!occupied.has(`${x},${y}`));if(x!==undefined){pos={x,y};break;}}}if(!pos)continue;occupied.add(`${pos.x},${pos.y}`);const definition=metalDefinition(d,count);list.push({name:d.name,definition,side,star:definition.star,x:side===0?pos.x:6-pos.x,y:side===0?pos.y:7-pos.y,special:true,previewMetal:true});}return list;}
export function moveMetal(g,id,name,x,y){if(name==='驾驭机器人')return moveRobot(g,id,x,y);const p=editable(g,id);assert(previewMetal(g,id).some(u=>u.name===name),'该特殊友军尚未解锁');assert(Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<7&&y>=4&&y<8,'只能放在己方半场');assert(!p.units.some(u=>u.location==='board'&&u.x===x&&u.y===y)&&!previewMetal(g,id).some(u=>u.name!==name&&u.x===x&&u.y===y),'该位置已经占用');p.metalPositions??={};p.metalPositions[name]={x,y};}

const augmentAPI={components:COMPONENTS,items:regularItems.map(i=>i[0]).filter(n=>n!=='奇袭手套'),reward(g,p,name,cost=1,count=1,star=1){const choices=g.catalog.filter(d=>(name?d.name===name:d.cost===cost)&&g.pool[d.name]>=count);const d=pick(g,choices);if(!d){if(count===1)p.gold+=cost;return false;}g.pool[d.name]-=count;if(star===1)return grant(g,p,d.name,true);const u={id:++g.counter,name:d.name,star,location:p.units.filter(u=>u.location==='bench').length<9?'bench':'pending',x:0,y:4,permanent:{ap:0,kills:0},items:[]};p.units.push(u);combine(g,p);return u;},science(g,p){const available=inventions.filter(d=>d.advanced&&!(p.inventions??[]).includes(d.name)).map(d=>d.name);if(!available.length){p.gold+=8;return;}p.scienceOffers=[];while(available.length&&p.scienceOffers.length<3)p.scienceOffers.push(available.splice(Math.floor(random(g)*available.length),1)[0]);}};
export function selectAugment(g,id,index){chooseAugment(g,id,index,augmentAPI);syncSpecials(g,id);}
export function setAugmentTargets(g,id,ids){const p=editable(g,id);assert(ids.length===2&&new Set(ids).size===2&&ids.every(id=>p.units.some(u=>u.id===id&&u.location!=='pending')),'请选择两名不同棋子');p.augmentTargets=[...ids];}
export function assignHero(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u&&p.heroName===u.name&&u.location!=='pending','该棋子没有对应英雄强化');for(const w of p.units)w.hero=false;u.hero=true;}
export function useCopy(g,id,uid,index){const p=editable(g,id),u=p.units.find(u=>u.id===uid),tool=p.items[index];assert(u&&['普通复制器','低费复制器'].includes(tool),'请选择复制器和目标');assert(tool!=='低费复制器'||definition(g,u.name).cost<=3,'低费复制器只复制一至三费');assert(g.pool[u.name]>0,'公共卡池不足，保留复制器');g.pool[u.name]--;removeInventoryItem(p,index);p.items.splice(index,1);grant(g,p,u.name,true);}

export function setTraitAugmentTarget(g,id,kind,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid&&u.location==='board');assert(u,'请选择登场棋子');const conditions={soloId:['独奏时刻','空想乐团'],resonanceId:['一心同体','召唤师'],pilotId:['钢铁驾驭','金属狂潮']},rule=conditions[kind];assert(rule&&hasAugment(p,rule[0])&&unitTraits(g,u).includes(rule[1]),'该棋子不符合强化条件');if(kind==='resonanceId')assert(['赛文','巴尔坦星人','庞顿','佐菲'].includes(u.name)&&!(u.name==='赛文'&&u.hero),'没有对应召唤兽');p[kind]=uid;}
export function setApprentice(g,id,mentorId,uid){const p=editable(g,id),mentor=p.units.find(u=>u.id===mentorId&&u.location==='board'),u=p.units.find(u=>u.id===uid&&u.location==='board');assert(hasAugment(p,'传道授业')&&mentor&&u&&['赛文','雷欧','爱迪','奥特之父'].includes(mentor.name)&&!unitTraits(g,u).includes('导师'),'需要天然导师与非导师徒弟');p.apprentices??={};assert(!Object.entries(p.apprentices).some(([m,t])=>Number(m)!==mentorId&&t===uid),'不同导师不能指定同一徒弟');p.apprentices[mentorId]=uid;}
export function setArmory(g,id,on){const p=editable(g,id);assert(hasAugment(p,'帝国的军械库'),'尚未获得军械库强化');p.empireArmory=Boolean(on);}
export function moveRobot(g,id,x,y){const p=editable(g,id);assert(hasAugment(p,'钢铁驾驭')&&(boardTraits(g,p)['金属狂潮']??0)>=3,'机器人尚未激活');assert(Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<7&&y>=4&&y<8&&!p.units.some(u=>u.location==='board'&&u.id!==p.pilotId&&u.x===x&&u.y===y),'选择己方空格或驾驶员格');p.robotPosition={x,y};const pilot=p.units.find(u=>u.id===p.pilotId&&u.location==='board');if(pilot){pilot.x=x;pilot.y=y;}}
function configureAugmentTargets(g,p){const board=p.units.filter(u=>u.location==='board').sort((x,y)=>unitScore(g,p,y)-unitScore(g,p,x));if(['双核协作','至尊双核'].some(n=>hasAugment(p,n))){p.augmentTargets=(p.augmentTargets??[]).filter(id=>board.some(u=>u.id===id));for(const u of board)if(p.augmentTargets.length<2&&!p.augmentTargets.includes(u.id))p.augmentTargets.push(u.id);}for(const [kind,name,trait] of [['pilotId','钢铁驾驭','金属狂潮'],['soloId','独奏时刻','空想乐团'],['resonanceId','一心同体','召唤师']])if(hasAugment(p,name)){const legal=board.filter(u=>unitTraits(g,u).includes(trait)&&(kind!=='resonanceId'||['赛文','巴尔坦星人','庞顿','佐菲'].includes(u.name)&&!(u.name==='赛文'&&u.hero)));if(!legal.some(u=>u.id===p[kind]))p[kind]=legal[0]?.id??null;}if(hasAugment(p,'传道授业')){p.apprentices??={};const masters=board.filter(u=>['赛文','雷欧','爱迪','奥特之父'].includes(u.name));const used=new Set();for(const m of masters){let student=board.find(u=>u.id===p.apprentices[m.id]&&!unitTraits(g,u).includes('导师')&&!used.has(u.id));student??=board.find(u=>!unitTraits(g,u).includes('导师')&&!used.has(u.id)&&(u.training?.length??0)<8);if(student){p.apprentices[m.id]=student.id;used.add(student.id);}}}}

export function setPandoraSlots(g,id,slots){const p=editable(g,id);assert(hasAugment(p,'潘多拉备战席'),'尚未获得潘多拉备战席');assert(Array.isArray(slots)&&slots.length===3&&new Set(slots).size===3&&slots.every(n=>Number.isInteger(n)&&n>=0&&n<9),'选择三个不同备战席格');p.pandoraSlots=[...slots];}

function previewGrid(g,id,side,occupied){const p=player(g,id),count=boardTraits(g,p)['古利特']??0,tier=count>=7?2:count>=5?1:count>=3?0:-1;if(tier<0)return null;const members=[...new Map(p.units.filter(u=>u.location==='board'&&unitTraits(g,u).includes('古利特')).sort((a,b)=>a.star-b.star).map(u=>[u.name,u])).values()],S=members.reduce((n,u)=>n+u.star,0),def=gridmanDefinition(tier,S,hasAugment(p,'我们的世界'));let pos=p.metalPositions?.['古利特超人'];if(!pos||!Number.isInteger(pos.x)||!Number.isInteger(pos.y)||pos.x<0||pos.x>6||pos.y<4||pos.y>7||occupied.has(pos.x+','+pos.y)){pos=null;for(const y of [4,5,6,7]){const x=[3,2,4,1,5,0,6].find(x=>!occupied.has(x+','+y));if(x!==undefined){pos={x,y};break;}}}if(!pos)return null;return {name:def.name,side,star:def.star,x:side===0?pos.x:6-pos.x,y:side===0?pos.y:7-pos.y,special:true,previewMetal:true,previewGrid:true,definition:def};}
export function previewNeutrals(g){return neutrals(g).map((u,i)=>({name:u.name,side:1,star:1,x:[3,2,4,1][i],y:2,special:true,neutral:true,items:g.stage>=5?[neutralBossItem(g,0)]:[],definition:u}));}

export function upgradeRadiant(g,id,uid,toolIndex,itemIndex){const p=editable(g,id),u=p.units.find(u=>u.id===uid);assert(u&&p.items[toolIndex]==='光明升级器','请选择光明升级器与自己的棋子');const slot=itemIndex??u.items.findIndex(upgradeFor),next=upgradeFor(u.items[slot]);assert(next,'该装备没有光明版本，升级器保留');removeInventoryItem(p,toolIndex);p.items.splice(toolIndex,1);u.items[slot]=next;reconcileItems(p);syncSpecials(g,id);return next;}
