import {boosters,boosterInfo} from './specials.mjs';
import {rareSelectors} from './rare-augments.mjs';
import {rareItems,rareItem} from './rare-equipment.mjs';
import {components,items} from './equipment-data.mjs';
import {traitTiers} from './engine.mjs';
import {traitInfo} from './trait-info.mjs';
import {unitInfo,heroInfo,playerSkill} from './unit-info.mjs';
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const light=['银河警备队','金属狂潮','古利特','人工智能','宇宙骑士队','银河帝国','空想乐团','科学家'],dark=['战士','神枪手','法师','神谕','护卫','重装战士','格斗家','刺客'];
export function equipmentInfo(name){const rare=rareItem(name);if(rare)return {...rare,parts:null};
 const c=components.find(c=>c[1]===name),i=items.find(i=>i[0]===name);
 if(c)return {name,type:'组件',stats:c[3],effect:'可与另一件组件合成为成装。',recipes:[...items.filter(i=>i[1].includes(c[0])).map(i=>({name:i[0],parts:[...i[1]].map(code=>components.find(c=>c[0]===code)[1])})),{name:light[components.indexOf(c)]+'纹章',parts:['光徽',name]},{name:dark[components.indexOf(c)]+'纹章',parts:['暗徽',name]}]};
 if(i)return {name,type:'成装',stats:i[3],effect:i[4],parts:[...i[1]].map(code=>components.find(c=>c[0]===code)[1])};
 if(name.endsWith('纹章')){const trait=name.slice(0,-2),li=light.indexOf(trait),di=dark.indexOf(trait);return {name,type:'纹章',stats:'占用一个装备栏',effect:'持有者获得「'+trait+'」羁绊。已具有该羁绊时不重复计数。',parts:li>=0?['光徽',components[li][1]]:di>=0?['暗徽',components[di][1]]:null};}
 const tools={神器四选一:'从四件不同神器中选择一件。',光明圣物选择器:'从五件不同光明装备中选择一件。',光明升级器:'将棋子的一件适配成装升级为光明版本，保留装备栏位。拖到棋子时升级第一件适配装备；也可在详情选择具体装备。可升级：狂怒刃、战意长枪、光辉冠、光能枪刃、大天使杖、生命铠、龙鳞披风、泰坦战甲。',神器选择器:'从随机提供的三件神器中选择一件。',光明装备选择器:'从随机提供的三件光明装备中选择一件。',光徽:'与普通组件合成光系纹章；与另一个徽章合成统帅冠冕。',暗徽:'与普通组件合成暗系纹章；与另一个徽章合成统帅冠冕。',统帅冠冕:'队伍人口上限+1。无需穿戴。',拆卸器:'取下棋子全部装备并放回库存，消耗此道具。',重铸器:'将一件装备重铸为同类别的随机装备，消耗此道具。',普通复制器:'复制一张指定棋子的一星版本；占用公共卡池。',低费复制器:'复制一张1～3费棋子的一星版本；占用公共卡池。',普通成装选择器:'从随机提供的普通成装中选择一件。',组件选择器:'从随机提供的组件中选择一件。',复制组件选择器:'从提供的组件中选择一项，获得两件相同组件。',纹章选择器:'从随机提供的纹章中选择一件。'};
 return {name,type:'道具',stats:'',effect:tools[name]??'特殊奖励道具。',parts:name==='统帅冠冕'?['光徽或暗徽','光徽或暗徽']:null};
}
export function skillMarkup(name,star=0,hero=false){const d=hero&&heroInfo[name]?heroInfo[name]:unitInfo[name];if(!d)return '';const prose=t=>escape(t).replace(/\d+(?:\.\d+)?(?:\/\d+(?:\.\d+)?){1,2}/g,m=>'<span class="star-values" title="按一星、二星、三星排列">'+m.split('/').map((v,i)=>i===star-1?'<strong>'+v+'</strong>':v).join('/')+'</span>').replace(/魔法伤害|物理伤害|护盾|攻击力|法强|眩晕|减伤/g,m=>'<span class="keyword '+(['魔法伤害','法强'].includes(m)?'magic':['物理伤害','攻击力'].includes(m)?'physical':'defense')+'">'+m+'</span>');return '<section class="skill-section"><h4>技能 · '+escape(d[0])+'</h4><p>'+prose(star===3&&d[3]?d[3]:d[1])+'</p>'+(d[2]?'<h4>被动</h4><p>'+prose(d[2])+'</p>':'')+(d[3]&&star!==3?'<h4 class="five-star">三星效果</h4><p>'+prose(d[3])+'</p>':'')+'</section>';}
export function equipmentButtons(names){return names.map(n=>'<button class="item-info-link" data-item-info="'+escape(n)+'">'+escape(n)+'</button>').join('');}
export function mountReference(data){
 const $=id=>document.getElementById(id);let category='棋子';
 document.body.insertAdjacentHTML('beforeend','<dialog id="reference-detail"><div class="dialog-inner reference-inner"><div class="panel-head"><h2 id="reference-title"></h2><button id="reference-close" aria-label="关闭详情">关闭</button></div><div id="reference-body"></div></div></dialog>');
 $('reference-close').onclick=()=>$('reference-detail').close();
 const open=(title,body)=>{$('reference-title').textContent=title;$('reference-body').innerHTML=body;bind($('reference-body'));if(!$('reference-detail').open)$('reference-detail').showModal();};
 function showItem(name){const d=equipmentInfo(name);open(name,'<span class="reference-type">'+escape(d.type)+'</span>'+(d.stats?'<h4>属性</h4><p>'+escape(d.stats)+'</p>':'')+'<h4>效果</h4><p>'+escape(d.effect)+'</p>'+(d.parts?'<h4>合成配方</h4><div class="recipe">'+d.parts.map(n=>equipmentButtons([n])).join('<span> + </span>')+'</div>':d.type==='纹章'?'<p>通过奖励或强化获得，不能用普通组件合成。</p>':'')+(d.recipes?'<h4>可合成装备</h4>'+d.recipes.map(r=>'<div class="recipe-row">'+r.parts.map(n=>equipmentButtons([n])).join('<span> + </span>')+'<span> → </span>'+equipmentButtons([r.name])+'</div>').join(''):''));}
 function showTrait(name,count=0,prismatic=false){const d=traitInfo[name];if(!d)return;const tiers=traitTiers[name]??[1],members=data.units.filter(u=>u.traits.includes(name));open(name,'<p>'+escape(d[0])+'</p><div class="trait-levels">'+tiers.map((n,i)=>'<section class="trait-level '+(count>=n?(prismatic&&i===tiers.length-1?'active prismatic':'active'):'')+'"><b>('+n+')</b><p>'+escape(d[1][i]??d[1].at(-1))+'</p></section>').join('')+'</div>'+(name==='宇宙骑士队'?'<h4>强化器效果</h4>'+Object.entries(boosterInfo).map(([n,descs])=>'<section class="trait-level booster-effect-card"><b>'+escape(n)+' · '+escape(boosters[n])+'</b><p><strong>2人档：</strong>'+escape(descs[0])+'</p><p><strong>4人档：</strong>'+escape(descs[1])+'</p></section>').join(''):'')+'<h4>羁绊棋子</h4><div class="trait-members">'+members.map(u=>'<button data-unit-info="'+escape(u.name)+'"><b>'+escape(u.name)+'</b><span>'+u.cost+'费</span></button>').join('')+'</div>');}
 function showUnit(name){const u=data.units.find(u=>u.name===name);if(!u)return;open(name,'<p>'+u.cost+'费 · '+escape(u.traits.join(' / '))+'</p><div class="stat-grid"><div>生命<b>'+u.hp+'</b></div><div>攻击力<b>'+u.ad+'</b></div><div>攻速<b>'+u.as+'</b></div><div>护甲 / 魔抗<b>'+u.armor+' / '+u.mr+'</b></div><div>射程<b>'+u.range+'格</b></div><div>法力<b>'+(u.mana?u.mana.join(' / '):'无蓝条')+'</b></div></div>'+skillMarkup(name)+'<div class="traits">'+u.traits.map(t=>'<button data-trait-info="'+escape(t)+'">'+escape(t)+'</button>').join('')+'</div>');}
 function bind(root){for(const b of root.querySelectorAll('[data-item-info]'))b.onclick=()=>showItem(b.dataset.itemInfo);for(const b of root.querySelectorAll('[data-trait-info]'))b.onclick=()=>showTrait(b.dataset.traitInfo);for(const b of root.querySelectorAll('[data-unit-info]'))b.onclick=()=>showUnit(b.dataset.unitInfo);}
 $('catalog-search').insertAdjacentHTML('beforebegin','<nav id="catalog-tabs" class="catalog-tabs" aria-label="图鉴分类">'+['棋子','装备','羁绊'].map(n=>'<button data-category="'+n+'">'+n+'</button>').join('')+'</nav>');
 function renderCatalog(){const q=$('catalog-search').value.trim();for(const b of $('catalog-tabs').children){b.classList.toggle('selected',b.dataset.category===category);b.setAttribute('aria-pressed',String(b.dataset.category===category));}
 if(category==='棋子')$('catalog-list').innerHTML=data.units.filter(u=>(u.name+u.traits.join('')+playerSkill(u.name)).includes(q)).map(u=>'<article><button class="catalog-entry" data-unit-info="'+escape(u.name)+'"><b>'+escape(u.name)+'</b><small>'+u.cost+'费 · '+escape(u.traits.join(' / '))+'</small></button>'+skillMarkup(u.name)+'</article>').join('');
 if(category==='装备')$('catalog-list').innerHTML=[...components.map(c=>c[1]),...items.map(i=>i[0]),...rareItems.map(i=>i.name),...Object.keys(rareSelectors),'光明升级器','光徽','暗徽','统帅冠冕',...Object.keys(traitTiers).map(t=>t+'纹章'),'普通成装选择器','组件选择器','纹章选择器','复制组件选择器','拆卸器','重铸器','普通复制器','低费复制器'].filter(n=>{const d=equipmentInfo(n);return (n+d.stats+d.effect).includes(q);}).map(n=>{const d=equipmentInfo(n);return '<article><button class="catalog-entry" data-item-info="'+escape(n)+'"><b>'+escape(n)+'</b><small>'+escape(d.type)+'</small></button><p>'+escape(d.stats)+'</p><p>'+escape(d.effect)+'</p></article>';}).join('');
 if(category==='羁绊')$('catalog-list').innerHTML=Object.entries(traitInfo).filter(([n,d])=>(n+d[0]+d[1].join('')+data.units.filter(u=>u.traits.includes(n)).map(u=>u.name).join('')).includes(q)).map(([n,d])=>'<article><button class="catalog-entry" data-trait-info="'+escape(n)+'"><b>'+escape(n)+'</b><small>'+escape((traitTiers[n]??[1]).join(' / '))+'</small></button><p>'+escape(d[0])+'</p></article>').join('');bind($('catalog-list'));
 }
 for(const b of $('catalog-tabs').children)b.onclick=()=>{category=b.dataset.category;renderCatalog();};$('catalog-search').oninput=renderCatalog;$('catalog-open').textContent='图鉴';$('catalog-open').onclick=()=>{renderCatalog();$('catalog').showModal();};
 return {showItem,showTrait,showUnit,bind};
}
