import {tiers,catalog} from './content.mjs';
const nodes=['2-1','3-2','4-2'];
const common=[
['战备训练','金','全队生命+150、攻击力+10%。'],['法术研习','银','全队法强+20。'],['先发制人','银','全队初始蓝量+20。'],['持久战','金','全队获得10%全能吸血。'],['铁壁防线','金','全队护甲、魔抗+20。'],['应急储备','银','获得12金币。'],['远航资金','金','获得20金币。'],['黄金宝藏','彩','获得35金币和普通复制器。'],['新兵入队','彩','人口永久+1，获得普通复制器。'],['升级咯','彩','购买经验额外获得2经验。'],['利滚利','金','最大正常利息由5提高至7，获得10金币。'],['组件包','银','获得两个随机组件。'],['装备支援','金','获得普通成装选择器和拆卸器。'],['光明圣物','彩','获得光明装备选择器和拆卸器。'],['神器宝库','金','获得神器选择器。'],['休眠锻炉','银','完成十场玩家战后获得神器选择器。'],['活体锻炉','彩','立即获得神器选择器，之后每九场玩家战再获得一件。'],['光明重构','彩','获得光明升级器与组件选择器。'],['照护者之选','彩','4级获得组件选择器，6级成装选择器，8级光明装备选择器。'],['刷新储备','银','每个准备阶段第一次刷新商店免费。'],['双份复制','彩','获得两个普通复制器。'],['快速训练','金','立即获得12经验和8金币。']
];
const heroes=[['光的传承','奈克瑟斯','累计25/70次参与击杀进化为四/五费；商店同步升级。'],['双星连舞','阿斯特拉','普攻叠加3%本场攻速；每第三击触发连踢，技能不再提供固定攻速。'],['深海猎食者','萨德拉','技能变为两次65%伤害的撕裂，残骸攻击成长+30%；获得15%全能吸血，取消技能吸血。'],['归来的英雄','杰克','手镯改为环绕攻击；护盾存在时附带最大生命物理伤害。'],['远灵圣歌','幽怜','技能变为180%首段伤害的单体攻击，每施加五次灼烧获得额外回响。'],['无尽一刀','扎姆夏','施法不再强化三次普攻，而是增加6%本场攻击力；第四击忽略30%护甲。'],['极寒海域','雷丘巴斯','技能变为2秒持续冰流，总伤害提高40%；连续命中四次冰冻1秒。']];
const trait=[['船长的赌注','金','海盗','仅提供危险任务，声望额外+40%。'],['满载归航','彩','海盗','兑换后保留25%声望，获得海盗纹章与二费海盗。'],['舰队集结','金','皇家海军','炮击后海军下一击追加40魔法伤害，获得中岛洋子。'],['不沉舰队','彩','皇家海军','海军首次低于30%生命获得25%生命护盾，炮击伤害+20%，获得海军纹章。'],['永恒航路','彩','探险家','600能量后每100额外能量，神器战斗数值+5%，最多五次。获得探险家纹章。'],['残骸盛宴','金','食腐者','每场首次击败携带成装的敌人时，食腐者各获得两份残骸。'],['狂热传道','金','远灵教会','狂热时为最近两名友军提供20%攻速，获得幽怜。'],['亡者同行','金','幽灵','附身提供15%生命护盾，宿主死亡可再迁移一次，第二次效果减半。'],['巨灵之潮','彩','海洋巨灵','至高巨灵生命+15%、全能吸血+15%，合体支援效果+50%。获得乔尼亚斯。'],['遗迹复苏','金','遗迹守护者','核心附近友军每5秒获得100护盾，守卫死亡造成200范围魔法伤害。'],['星辰共鸣','彩','星宿','7档开启50%彩色效果，9档恢复完整效果且星宿生命+15%。']];
export const augments=[...common.map(([name,tier,effect])=>({name,tier,effect,nodes})),...heroes.map(([name,hero,effect])=>({name,hero,tier:'金',effect:'获得'+hero+'。'+effect,nodes:['2-1']})),...trait.map(([name,tier,trait,effect])=>({name,tier,trait,effect,nodes:['2-1']})),...Object.keys(tiers).filter(t=>t!=='海怪').flatMap(t=>[['金','之徽'],['彩','之冕']].map(([tier,suffix])=>({name:t+suffix,tier,trait:t,emblem:t,effect:'获得'+t+'纹章、'+(tier==='彩'?'一件普通成装和':'')+'一名该羁绊低费棋子。',nodes:['2-1']})))];
export const has=(p,name)=>p.augments.includes(name);
export function pool(node,tier,owned=[]){return augments.filter(d=>d.nodes.includes(node)&&d.tier===tier&&!owned.includes(d.name));}
export function offer(g,p,node,rand){if(p.augmentNodes.includes(node))return;p.augmentNodes.push(node);const index=nodes.indexOf(node),tier=g.sequence[index],available=pool(node,tier,p.augments);p.augmentChoice={node,tier,offers:[],seen:[],rerolled:[false,false,false]};for(let i=0;i<3;i++){const d=available.splice(Math.floor(rand()*available.length),1)[0];if(d){p.augmentChoice.offers.push(d.name);p.augmentChoice.seen.push(d.name);}}}
export function reroll(g,p,i,rand){const ch=p.augmentChoice;if(!ch||ch.rerolled[i])throw Error('此项已经刷新');const list=pool(ch.node,ch.tier,p.augments).filter(d=>!ch.seen.includes(d.name));if(!list.length)throw Error('没有新的强化');const d=list[Math.floor(rand()*list.length)];ch.offers[i]=d.name;ch.seen.push(d.name);ch.rerolled[i]=true;}
export function accept(g,p,index,reward,random){const d=augments.find(d=>d.name===p.augmentChoice?.offers[index]);if(!d)throw Error('没有该强化');p.augments.push(d.name);p.augmentChoice=null;if(d.hero){p.heroName=d.hero;reward(d.hero);const u=p.units.find(u=>u.name===d.hero);if(u)u.hero=true;if(d.name==='光的传承')p.nexusCost=3;}if(d.emblem){p.items.push(d.emblem+'纹章');reward(catalog.find(u=>u.traits.includes(d.emblem)&&u.cost<=2)?.name);if(d.tier==='彩')p.items.push('普通成装选择器');}const grants={应急储备:12,远航资金:20,黄金宝藏:35,利滚利:10,快速训练:8};p.gold+=grants[d.name]??0;const items={黄金宝藏:['普通复制器'],新兵入队:['普通复制器'],装备支援:['普通成装选择器','拆卸器'],光明圣物:['光明装备选择器','拆卸器'],神器宝库:['神器选择器'],活体锻炉:['神器选择器'],光明重构:['光明升级器','组件选择器'],双份复制:['普通复制器','普通复制器']};p.items.push(...items[d.name]??[]);if(d.name==='新兵入队')p.extraPopulation++;if(d.name==='组件包')for(let i=0;i<2;i++)p.items.push(random());if(d.name==='快速训练')p.pendingXP=(p.pendingXP??0)+12;if(d.name==='满载归航'){p.items.push('海盗纹章');reward('巴尔基星人');}if(d.name==='不沉舰队')p.items.push('皇家海军纹章');if(d.name==='永恒航路')p.items.push('探险家纹章');for(const [name,unit] of [['舰队集结','中岛洋子'],['狂热传道','幽怜'],['巨灵之潮','乔尼亚斯'],['遗迹复苏','诺恩马尔特'],['亡者同行','西博兹'],['残骸盛宴','萨德拉'],['船长的赌注','马格马星人']])if(d.name===name)reward(unit);}
