import {catalog,counts,rank,effectiveDefinition} from './content.mjs';
import {initEquipment,attackEquipment,castEquipment,hitEquipment,damageEquipment,tickEquipment} from '../equipment.mjs';
import {initTraits,tickTraits,attackTraits,deathTraits} from './traits.mjs';
import {castSkill,attackPassive,initPassives,deathPassive,tickPassives} from './skills.mjs';
import {items} from '../equipment-data.mjs';
import {category} from './items.mjs';
export const STEP=.05;
export function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=Math.imul(x^(x>>>15),1|x);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296;};}
const axial=p=>({q:p.x-(p.y-(p.y&1))/2,r:p.y});
export function distance(a,b){a=axial(a);b=axial(b);return(Math.abs(a.q-b.q)+Math.abs(a.r-b.r)+Math.abs(a.q+a.r-b.q-b.r))/2;}
export function neighbors(p){const a=axial(p);return [[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]].map(([q,r])=>({q:a.q+q,r:a.r+r})).map(p=>({x:p.q+(p.r-(p.r&1))/2,y:p.r})).filter(p=>p.x>=0&&p.x<7&&p.y>=0&&p.y<8);}
export const live=u=>!u.dead&&u.hp>0&&!u.fused;
export const enemies=(s,u)=>s.units.filter(v=>v.side!==u.side&&live(v)&&!(v.untargetableUntil>s.time));
export const allies=(s,u)=>s.units.filter(v=>v.side===u.side&&live(v));
const bonus=(u,key)=>u.buffs.reduce((n,b)=>n+(b[key]??0),0);
export function stats(u){const resistance=k=>Math.max(0,(u[k]+bonus(u,k))*(1-Math.max(0,...u.buffs.map(b=>b[k+'Pct']??0))));return {ad:u.baseAd*(1+u.adBonus+bonus(u,'ad')),as:Math.max(.05,Math.min(5,u.baseAs*(1+u.asBonus+bonus(u,'as')))),ap:(u.ap+bonus(u,'ap'))*(u.mageScale??1),armor:resistance('armor'),mr:resistance('mr'),amp:u.amp+bonus(u,'amp'),output:Math.max(0,1+bonus(u,'output')),dr:Math.min(u.terminal?.99:.75,1-(1-u.dr)*u.buffs.reduce((v,b)=>v*(1-(b.dr??0)),1))};}
export const event=(s,type,u,v,extra={})=>s.events.push({tick:s.tick,time:+s.time.toFixed(2),type,source:u?.id??null,target:v?.id??null,...extra});
export function buff(s,u,key,seconds,attrs){u.buffs=u.buffs.filter(b=>b.key!==key);u.buffs.push({key,until:s.time+seconds,...attrs});}
export function shield(s,u,n,seconds,key){if(!live(u))return;u.shields=u.shields.filter(b=>b.key!==key);u.shields.push({key,amount:Math.max(0,n),until:s.time+seconds});event(s,'shield',u,u,{amount:Math.round(n)});}
export function heal(s,u,n){if(!live(u))return 0;const amount=Math.max(0,Math.min(u.maxHp-u.hp,n*(u.woundUntil>s.time?.67:1)));u.hp+=amount;u.healingDone+=amount;return amount;}
export function mana(s,u,n){if(u.maxMana&&s.time>=u.lockUntil)u.mana=Math.max(0,Math.min(u.maxMana,u.mana+n));}
export const nearest=(s,u)=>enemies(s,u).sort((a,b)=>distance(u,a)-distance(u,b)||String(a.id).localeCompare(String(b.id)))[0];
export function stun(s,u,seconds){if(u.immuneUntil>s.time)return;u.stunUntil=Math.max(u.stunUntil,s.time+seconds);if(u.name==='杰斯提斯')mana(s,u,[4,6,10][u.star-1]);}
export function hit(s,u,v,n,kind='physical',opts={}){if(!u||!v||!live(v)||n<=0||v.invulnerableUntil>s.time)return 0;const st=stats(u),vs=stats(v);let amount=n*(opts.artifact?(u.artifactMultiplier??1):1)*(opts.fixedDamage?1:(1+st.amp)*st.output);const sharp=rank(s.traits[u.side].counts,'神枪手');if(sharp>=0&&u.traits.includes('神枪手'))amount*=1+Math.min(5,distance(u,v))*[.03,.05,.08][sharp];const star=s.traits[u.side];if(star.constellation==='罗盘座'&&v.id===star.mark&&(u.traits.includes('星宿')||star.starFull||star.starWeak))amount*=1+(star.starFull?.4:star.starWeak?.2:[.15,.25,.4][Math.min(star.starRank,2)]);if(u.contract===v.id)amount*=1+[.15,.2,.8][u.star-1];amount*=1+(kind==='physical'?bonus(v,'physicalVuln'):0)+bonus(v,'vuln');let crit=false;if(!opts.noCrit&&(opts.attack||u.skillCrit)&&s.random()<Math.min(1,.25+(u.extraCrit??0))){amount*=1.4+(u.extraCritDamage??0);crit=true;}amount=damageEquipment(s,u,v,amount,kind,opts,api);amount*=100/(100+(kind==='physical'?vs.armor*(1-(opts.pen??0)):kind==='magic'?vs.mr:0))*(1-vs.dr);let remaining=amount;for(const sh of v.shields.sort((a,b)=>a.until-b.until)){const n=Math.min(remaining,sh.amount);remaining-=n;sh.amount-=n;}const damage=Math.min(v.hp,remaining)+amount-remaining;v.hp-=Math.min(v.hp,remaining);u.damageDone+=damage;if(damage>0){v.participants??={};v.participants[u.owner??u.id]=s.time;v.hitCount=(v.hitCount??0)+(opts.attack?1:0);if(v.manaReceivedSecond!==Math.floor(s.time)){v.manaReceivedSecond=Math.floor(s.time);v.manaReceived=0;}const gain=Math.min(10,damage*.05,Math.max(0,20-v.manaReceived));v.manaReceived+=gain;mana(s,v,gain);if(u.omni&&!opts.item)heal(s,u,damage*u.omni*(opts.area?1/3:1));if(opts.skillHeal)heal(s,u,damage*opts.skillHeal*(opts.area?1/3:1));hitEquipment(s,u,v,damage,kind,opts,api,amount-remaining);if(v.hp<=0)v.killer??=u.id;event(s,'hit',u,v,{amount:Math.round(damage),kind,crit});}return damage;}
export function makeUnit(def,p,id){const star=Math.max(1,Math.min(3,p.star??1)),scale=def.special?1:[1,1.8,3.24][star-1],perm={ad:0,ap:0,hp:0,armor:0,mr:0,kills:0,...p.permanent};return {id,instanceId:p.instanceId??p.id,name:def.name,displayName:def.displayName??def.name,cost:def.cost,traits:[...def.traits,...(p.items??[]).filter(n=>n.endsWith('纹章')).map(n=>n.slice(0,-2))].filter((v,i,a)=>a.indexOf(v)===i),def,star,side:p.side,x:p.x,y:p.y,items:[...(p.items??[])],permanent:perm,baseHp:def.hp*scale,hp:def.hp*scale+perm.hp,maxHp:def.hp*scale+perm.hp,baseAd:def.ad*scale+perm.ad,baseAs:def.as,armor:def.armor+perm.armor,mr:def.mr+perm.mr,range:def.range,ap:100+perm.ap,adBonus:0,asBonus:0,amp:0,dr:0,omni:0,shields:[],buffs:[],mana:def.mana?.[0]??0,maxMana:def.mana?.[1]??0,lockUntil:0,stunUntil:0,busyUntil:0,dead:false,special:Boolean(def.special),neutral:Boolean(def.neutral),attacks:0,castCount:0,attackClock:.35,moveClock:0,damageDone:0,healingDone:0,hero:p.hero??false,matchEffects:p.matchEffects??{},nextSecond:1,effects:[]};}
const point=p=>({x:p.x+.5*(p.y&1),y:p.y*Math.sqrt(3)/2});
export function lineTargets(s,u,target){const p=point(u),q=point(target),dx=q.x-p.x,dy=q.y-p.y,l=Math.hypot(dx,dy)||1;return enemies(s,u).filter(w=>{const r=point(w),x=r.x-p.x,y=r.y-p.y;return(x*dx+y*dy)/l>=-.01&&Math.abs(x*dy-y*dx)/l<=.5;});}
export function coneTargets(s,u,target){const p=point(u),q=point(target),dx=q.x-p.x,dy=q.y-p.y,l=Math.hypot(dx,dy)||1;return enemies(s,u).filter(w=>{const r=point(w),x=r.x-p.x,y=r.y-p.y;return distance(u,w)<=2&&(x*dx+y*dy)/(l*(Math.hypot(x,y)||1))>=.5;});}
export const magic=(u,n)=>n*stats(u).ap/100;
export const api={makeUnit,stats,hit,buff,shield,heal,mana,event,lookup:(s,id)=>s.units.find(u=>u.id===id),nearest,distance,neighbors,tier:rank,lineTargets,coneTargets,stun,magic,enemies,allies,live};
export function spawn(s,owner,def,desired){const tiles=[];for(let y=owner.side?0:4;y<(owner.side?4:8);y++)for(let x=0;x<7;x++)if(!s.units.some(u=>live(u)&&u.x===x&&u.y===y))tiles.push({x,y});tiles.sort((a,b)=>distance(owner,a)-distance(owner,b)||a.y-b.y||a.x-b.x);const tile=tiles.find(t=>t.x===desired?.x&&t.y===desired?.y)??tiles[0];if(!tile)return null;const u=makeUnit({cost:0,traits:[],mr:def.armor??30,mana:null,...def,special:true},{...tile,side:owner.side,star:1},'special-'+(++s.counter));u.owner=owner.id;s.units.push(u);event(s,'summon',owner,u);return u;}
export function createBattle(defs=catalog,placements,seed=4317){if(!placements||![0,1].every(side=>placements.some(p=>p.side===side)))throw Error('双方需要棋子');const s={season:'ocean-2',tick:0,time:0,random:rng(seed),seed,counter:0,units:[],events:[],queue:[],traits:[{counts:{},justice:-1},{counts:{},justice:-1}],finished:false,winner:null,normalEquipment:new Set(items.map(i=>i[0])),itemCategory:category,copyGear(s,u,name){u.items.push(name);}};const occupied=new Set();for(const p of placements){if(!Number.isInteger(p.x)||!Number.isInteger(p.y)||p.x<0||p.x>6||p.y<0||p.y>7||occupied.has(p.x+','+p.y))throw Error('非法或重叠站位');occupied.add(p.x+','+p.y);const d=defs.find(d=>d.name===p.name);if(!d)throw Error('未接入棋子：'+p.name);s.units.push(makeUnit(effectiveDefinition({nexusCost:p.nexusCost},d),p,'unit-'+(++s.counter)));}for(const side of [0,1])s.traits[side].counts=counts(s.units.filter(u=>u.side===side));initPassives(s,api);initEquipment(s,api);initTraits(s,api,spawn);for(const u of s.units)if(u.terminal)u.immuneUntil=60;event(s,'start',null,null);return s;}
function move(s,u,v){const used=new Set(s.units.filter(live).filter(w=>w!==u).map(w=>w.x+','+w.y)),seen=new Set([u.x+','+u.y]),q=neighbors(u).filter(p=>!used.has(p.x+','+p.y)).map(p=>({p,first:p}));while(q.length){const {p,first}=q.shift(),key=p.x+','+p.y;if(seen.has(key))continue;seen.add(key);if(distance(p,v)<=u.range){Object.assign(u,first);event(s,'move',u,v,first);break;}for(const next of neighbors(p))if(!seen.has(next.x+','+next.y)&&!used.has(next.x+','+next.y))q.push({p:next,first});}u.moveClock=.35;}
export function attack(s,u,v,extra=false){if(!live(u)||!live(v))return;const previous=u.attackTarget;u.attackTarget=v.id;if(previous!==v.id){u.sameHits=0;u.privateAmp=0;u.buffs=u.buffs.filter(b=>!['private-focus','imperial-focus'].includes(b.key));}if(!extra){u.attacks++;u.sameHits=(u.sameHits??0)+1;mana(s,u,10);}let coefficient=attackPassive(s,u,v,api,extra);if(extra&&u.items.includes('征潮战刃')&&(u.matchEffects.energy??0)>=300)coefficient*=1.25;hit(s,u,v,stats(u).ad*coefficient,'physical',{attack:true});attackTraits(s,u,v,api,extra);if(!extra)attackEquipment(s,u,v,api);event(s,'attack',u,v,{extra});}
export function cast(s,u,v,second=false,artifact=false){if(!live(u)||!v)return;if(!second&&!artifact){u.mana=0;u.castCount++;u.lockUntil=s.time+1.3;u.busyUntil=s.time+.3;}if(u.id===s.traits[u.side].crown&&(s.traits[u.side].starFull||s.traits[u.side].starWeak))hit(s,u,v,180*s.traits[u.side].starPower,'magic');const spellFactor=u.spellFactor;u.spellFactor=artifact?1:(u.items.includes('黄金罗盘')&&u.matchEffects.energy>=300&&(u.matchEffects.energy>=600||u.castCount%3===0)?1.35:1);castSkill(s,u,v,api);u.spellFactor=spellFactor;const itemMana=u.pendingItemMana??0;castEquipment(s,u,api,!second);if(second||artifact)u.pendingItemMana=itemMana;if(u.items.includes('黄金罗盘')&&(u.matchEffects.energy??0)>=100&&!second&&!artifact)u.compassMana=(u.compassMana??0)+8*(u.artifactMultiplier??1);const cannon=rank(s.traits[u.side].counts,'炮手');if(cannon>=0&&u.traits.includes('炮手'))buff(s,u,'cannon-cast',4,{amp:[.08,.15,.25][cannon]});if(u.name==='银河')for(const w of allies(s,u).filter(w=>w!==u))mana(s,w,[6,10,100][u.star-1]);if(u.parasiteUntil>s.time){const owner=api.lookup(s,u.parasiteOwner);if(owner){hit(s,owner,u,magic(owner,[80,120,200][owner.star-1]),'magic');mana(s,owner,[8,12,20][owner.star-1]);}}if(u.items.includes('潮汐圣典')){const e=u.matchEffects.energy??0,targets=allies(s,u).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp).slice(0,e>=300?2:1);if(e>=100)for(const w of targets){shield(s,w,magic(u,180)*(u.artifactMultiplier??1),4,'tome-'+u.id);if(e>=300)mana(s,w,8*(u.artifactMultiplier??1));}if(e>=600&&!second&&u.castCount%3===0)for(const w of allies(s,u)){shield(s,w,magic(u,250)*(u.artifactMultiplier??1),4,'tome-team');buff(s,w,'tome-speed',4,{as:.25*(u.artifactMultiplier??1)});}}if(!second&&!artifact&&rank(s.traits[u.side].counts,'法师')>=0&&u.traits.includes('法师'))s.queue.push({at:s.time+.35,type:'cast',source:u.id,target:v.id,second:true});if(!second&&!artifact&&u.items.includes('黄金火铳')&&u.castCount%3===0)s.queue.push({at:s.time+.7,type:'cast',source:u.id,target:v.id,artifact:true});event(s,'cast',u,v,{second,artifact});}
function deaths(s){for(const u of [...s.units]){if(u.dead||u.hp>0||u.fused)continue;if(deathPassive(s,u,api))continue;u.dead=true;u.diedAt=s.time;u.shields=[];event(s,'death',api.lookup(s,u.killer),u);deathTraits(s,u,api);if(u.neutral)event(s,'loot-drop',null,u,{loot:u.def.loot??[],x:u.x,y:u.y});}}
export function step(s){if(s.finished)return s;s.tick++;s.time=s.tick*STEP;for(const u of s.units){u.buffs=u.buffs.filter(b=>b.until>s.time);u.shields=u.shields.filter(b=>b.until>s.time&&b.amount>0);}tickTraits(s,api);tickPassives(s,api);tickEquipment(s,api);const pending=s.queue.filter(a=>a.at<=s.time+1e-8);s.queue=s.queue.filter(a=>a.at>s.time+1e-8);for(const a of pending){const u=api.lookup(s,a.source);if(!u||!live(u)||u.stunUntil>s.time)continue;const v=api.lookup(s,a.target);if(a.type==='cast')cast(s,u,live(v??{})?v:nearest(s,u),a.second,a.artifact);else if(a.type==='extra'){const next=live(v??{})?v:enemies(s,u).find(w=>distance(u,w)<=u.range);if(next)attack(s,u,next,true)};}deaths(s);for(const u of [...s.units].filter(live)){if(u.stunUntil>s.time)continue;const v=nearest(s,u);if(!v)continue;u.moveClock-=STEP;u.attackClock-=STEP;if(s.time<u.busyUntil)continue;if(u.maxMana&&u.mana>=u.maxMana&&s.time>=u.lockUntil){cast(s,u,v);continue;}if(distance(u,v)>u.range){if(u.moveClock<=0)move(s,u,v);continue;}if(u.attackClock<=0){attack(s,u,v);u.attackClock=1/stats(u).as;}}deaths(s);const sides=[0,1].map(side=>s.units.some(u=>u.side===side&&live(u)));if(!sides[0]||!sides[1]||s.time>=60){s.finished=true;s.winner=sides[0]&&!sides[1]?0:sides[1]&&!sides[0]?1:null;event(s,'end',null,null,{winner:s.winner});}return s;}
export function runBattle(s){while(!s.finished)step(s);return s;}
export const summary=s=>({winner:s.winner,time:s.time,units:s.units.map(u=>({name:u.name,side:u.side,hp:u.hp,damage:u.damageDone}))});
