import {components,items} from '../equipment-data.mjs';
import {radiants,artifacts,rareItem} from '../rare-equipment.mjs';
import {ancient,legendary,tiers} from './content.mjs';
export {components,items,radiants,artifacts};
export const specials={征潮战刃:'攻击力+20%，攻速+15%。100能量每四次普攻双击；300能量第二击伤害+25%、全能吸血15%；600能量改为每三次双击，参与击杀获得30%攻速4秒。',黄金罗盘:'法强+25，初始蓝量+15。100能量施法后回蓝8；300能量每第三次释放技能时，技能的伤害、治疗和护盾提高35%；600能量每次技能都获得此增益，法强额外+35。',深海壁垒:'生命+300，双抗+25。100能量首次低于50%生命获得35%最大生命护盾；300能量减伤15%、每5秒对周围一格敌人造成自身最大生命6%的魔法伤害；600能量可每10秒触发一次护盾，并为附近生命比例最低的友军提供其最大生命20%的护盾。',潮汐圣典:'法强+30，初始蓝量+15。100能量施法给低血友军180护盾；300能量改为保护两人，并为他们恢复8蓝量；600能量每第三次释放技能为全队提供250护盾和25%攻速，持续4秒。',不沉之旗:'生命+1200，双抗+60。开局自身300%最大生命护盾、其他友军100%；自身护盾首次破裂后完整补充一次。',船长佩刀:'攻击力+80%，攻速+80%，全能吸血35%。普攻双击，第二击追加50%攻击力真实伤害；参与击杀回复20%生命并增加10%本场攻击力。',黄金火铳:'攻击力+60%，法强+80，初始蓝量+20，技能伤害+35%。每第三次释放技能时，额外释放一次该技能。额外技能不会再次触发法师双重施法。'};
const light=['海盗','皇家海军','岛屿卫士','探险家','私掠者','商人','海怪猎手','星宿'],dark=['食腐者','远灵教会','幽灵','海洋巨灵','遗迹守护者','战士','法师','决斗大师'];
export function recipe(a,b){const ca=components.find(c=>c[1]===a),cb=components.find(c=>c[1]===b),badge=n=>['光徽','暗徽'].includes(n);if(badge(a)&&badge(b))return '统帅冠冕';if(badge(a)&&cb||badge(b)&&ca){const token=badge(a)?a:b,c=badge(a)?cb:ca;return (token==='光徽'?light:dark)[components.indexOf(c)]+'纹章';}if(!ca||!cb)return null;const key=[ca[0],cb[0]].sort().join('');return items.find(i=>i[1].split('').sort().join('')===key)?.[0]??null;}
export function itemInfo(name){if(['光徽','暗徽'].includes(name))return {name,stats:'',effect:'与普通组件合成第二赛季纹章，与另一枚徽记合成人口冠冕。',recipe:components.map(c=>c[1]+'＋'+name+'＝'+recipe(name,c[1])).join('；')};const d=items.find(i=>i[0]===name);if(d){const recipeText=d[1].split('').map(code=>components.find(c=>c[0]===code)?.[1]).join('＋');return {name,stats:d[3],effect:d[4],recipe:recipeText};}const c=components.find(c=>c[1]===name);if(c)return {name,stats:c[3],effect:'可与其他组件合成装备。',recipe:items.filter(i=>i[1].includes(c[0])).map(i=>i[0]).join('、')};const rare=rareItem(name);if(rare)return {...rare,recipe:'特殊奖励'};if(specials[name])return {name,stats:'',effect:specials[name],recipe:ancient.includes(name)?'探险家路线':'传奇海盗战利品'};if(name.endsWith('纹章'))return {name,stats:'',effect:'获得'+name.slice(0,-2)+'羁绊。',recipe:'徽记与组件，或强化奖励'};return {name,stats:'',effect:name==='统帅冠冕'?'队伍人口+1。':'准备阶段点击使用或选择目标。',recipe:''};}
export const equipment=n=>components.some(c=>c[1]===n)||items.some(i=>i[0]===n)||Boolean(rareItem(n))||ancient.includes(n)||legendary.includes(n)||n==='统帅冠冕'||n.endsWith('纹章')&&Object.hasOwn(tiers,n.slice(0,-2));
export function category(name){const d=items.find(i=>i[0]===name);if(!d)return 'utility';if(d[1].includes('A')||d[1].includes('C')||d[1]==='HH')return 'defense';if(d[1].includes('B'))return 'speed';if(d[1].includes('R'))return 'magic';if(d[1].includes('S'))return 'physical';return 'utility';}
