import {buildNeutralLoot,settleNeutralLoot,reservedNeutralCopies,neutralBossItem} from '../neutral-loot.mjs';
import {carouselCosts,carouselItem,carouselState,recordPick} from '../carousel-rules.mjs';
import {focusFor,selectBoard,positionBoard,purchaseScore,economyPlan,gearScore,bestCraft,power} from '../ai-planner.mjs';
import {catalog,tiers,SEASON,SAVE_KEY,counts,effectiveCost,effectiveDefinition,constellations,rank} from './content.mjs';
import {createBattle,runBattle,rng} from './engine.mjs';
import {components,items,recipe,equipment,artifacts,radiants} from './items.mjs';
import {offer,reroll,accept,has,augments} from './augments.mjs';
import {prepareSystems,settleSystems,chooseRoute,chooseTask,redeem,invest,withdraw,gamble,buyMarket,refreshMarket} from './systems.mjs';
export {chooseRoute,chooseTask,redeem,invest,withdraw,gamble,buyMarket,refreshMarket};
export const COPIES=[0,30,25,18,10,9],XP=[0,2,2,6,10,20,36,48,80,84,100];
export const ODDS=[[100,0,0,0,0],[100,0,0,0,0],[75,25,0,0,0],[55,30,15,0,0],[45,33,20,2,0],[30,40,25,5,0],[19,30,40,10,1],[18,25,32,22,3],[10,20,25,35,10],[5,10,20,40,25]];
export const roundName=g=>g.stage+'-'+g.round;
export const roundKind=g=>g.stage===1?(g.round===1?'initial':'neutral'):g.round===4?'carousel':g.round===7?'neutral':'pvp';
export const population=p=>Math.min(14,p.level+p.extraPopulation+p.items.filter(n=>n==='统帅冠冕').length+p.units.reduce((n,u)=>n+u.items.filter(i=>i==='统帅冠冕').length,0));
export function random(g){g.rngState=(g.rngState+0x6D2B79F5)>>>0;let t=g.rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}
export const pick=(g,a)=>a[Math.floor(random(g)*a.length)];
export const def=(g,name)=>g.catalog.find(d=>d.name===name);
export const boardCounts=(g,p)=>counts(p.units.filter(u=>u.location==='board').map(u=>({...u,traits:def(g,u.name).traits})));
export function editable(g,id){const p=g.players[id];if(g.phase!=='prepare'||!p||p.hp<=0||g.finished)throw Error('当前不能操作');return p;}
export function log(g,text){g.log.unshift(roundName(g)+' · '+text);g.log=g.log.slice(0,100);}
export const levelCap=p=>has(p,'升级咯')?11:10;
export function giveXP(p,amount){const cap=levelCap(p);p.xp+=amount;while(p.level<cap&&p.xp>=XP[p.level]){p.xp-=XP[p.level];p.level++;}if(p.level===cap)p.xp=0;}
function returnShop(g,p){for(const name of p.shop)if(name)g.pool[name]++;p.shop=Array(5).fill(null);}
export function draw(g,p,cost){const candidates=g.catalog.filter(d=>g.pool[d.name]>0&&(!cost||effectiveCost(p,d)===cost)&&!p.units.some(u=>u.name===d.name&&u.star===3));const odds=ODDS[Math.min(10,p.level)-1];const costs=[1,2,3,4,5].filter(c=>candidates.some(d=>effectiveCost(p,d)===c)&&odds[c-1]>0);if(!candidates.length||!cost&&!costs.length)return null;let chosen=cost;if(!chosen){let roll=random(g)*costs.reduce((n,c)=>n+odds[c-1],0);chosen=costs.at(-1);for(const c of costs){roll-=odds[c-1];if(roll<0){chosen=c;break;}}}const subset=candidates.filter(d=>effectiveCost(p,d)===chosen);if(!subset.length)return null;let roll=random(g)*subset.reduce((n,d)=>n+g.pool[d.name],0),d=subset.at(-1);for(const item of subset){roll-=g.pool[item.name];if(roll<0){d=item;break;}}g.pool[d.name]--;return d.name;}
export function shop(g,p){returnShop(g,p);p.shop=Array.from({length:5},()=>draw(g,p));}
const raw=u=>3**(u.star-1);
export function combine(g,p){for(let star=1;star<3;star++)for(const d of g.catalog){let same=p.units.filter(u=>u.name===d.name&&u.star===star);while(same.length>=3){same.sort((a,b)=>(a.location==='board'?-1:0)-(b.location==='board'?-1:0)||a.id-b.id);const parts=same.slice(0,3),keep=parts[0],nexusKills=Math.max(...parts.map(u=>u.permanent.nexusKills??0));keep.star++;keep.hero=parts.some(u=>u.hero);const merged={};for(const u of parts)for(const [key,v] of Object.entries(u.permanent))merged[key]=(merged[key]??0)+v;merged.nexusKills=nexusKills;keep.permanent=merged;const allItems=parts.flatMap(u=>u.items);keep.items=allItems.splice(0,3);p.items.push(...allItems);p.units=p.units.filter(u=>!parts.slice(1).includes(u));if(parts.some(u=>u.id===p.supreme))p.supreme=keep.id;if(parts.some(u=>u.id===p.crown))p.crown=keep.id;log(g,keep.name+'升至'+keep.star+'星');same=p.units.filter(u=>u.name===d.name&&u.star===star);}}claimPending(p);}
function claimPending(p){for(const u of p.units.filter(u=>u.location==='pending'))if(p.units.filter(w=>w.location==='bench').length<9)u.location='bench';}
export function grant(g,p,name,reserved=false,star=1){const d=def(g,name);if(!d)return false;const amount=3**(star-1);if(!reserved){if(g.pool[name]<amount){p.gold+=effectiveCost(p,d);return false;}g.pool[name]-=amount;}const u={id:++g.counter,name,star,location:p.units.filter(u=>u.location==='bench').length<9?'bench':'pending',x:0,y:4,items:[],permanent:{},hero:false};p.units.push(u);combine(g,p);return p.units.find(w=>w.id===u.id)??p.units.find(w=>w.name===name);}
export function createMatch(seed=4317,options={}){const g={version:1,season:SEASON,catalog:structuredClone(catalog),seed:seed>>>0,rngState:seed>>>0,counter:0,stage:1,round:1,phase:'draft',finished:false,settled:false,pool:Object.fromEntries(catalog.map(d=>[d.name,COPIES[d.cost]])),players:Array.from({length:8},(_,id)=>({id,name:id===0?'你':'航海者'+id,hp:100,gold:0,level:1,xp:0,extraPopulation:0,units:[],items:[],shop:Array(5).fill(null),locked:false,streak:0,rank:null,history:[],augments:[],augmentNodes:[],teamBonus:{},merchantBought:{},taskProgress:{},tasks:[],prestige:0,energy:0,bank:null,bounty:0,nexusCost:3,completedPvP:0})),log:[],battles:[]};g.constellation=pick(g,constellations);g.sequence=options.sequence??Array.from({length:3},()=>pick(g,['银','金','金','彩']));g.encounter=options.encounter??pick(g,['平静海面','新兵集结','精锐启航','远航同伴','头彩','尾彩','全彩','全金','古代馈赠']);const sequences={头彩:['彩','金','金'],尾彩:['金','金','彩'],全彩:['彩','彩','彩'],全金:['金','金','金']};if(sequences[g.encounter])g.sequence=sequences[g.encounter];for(const p of g.players){if(g.encounter==='新兵集结')grant(g,p,pick(g,catalog.filter(d=>d.cost===1)).name,false,2);if(g.encounter==='精锐启航')grant(g,p,pick(g,catalog.filter(d=>d.cost===2)).name);if(g.encounter==='远航同伴')grant(g,p,pick(g,catalog.filter(d=>d.cost===3)).name);if(g.encounter==='古代馈赠')p.items.push('神器选择器');}const optionsList=[];for(let i=0;i<3;i++){const name=draw(g,g.players[0],1);if(name)optionsList.push({name,item:pick(g,components)[1]});}g.draft=optionsList;const receipts=[];for(const p of g.players.slice(1)){const name=draw(g,p,1);if(name){const u=grant(g,p,name,true);u.location='board';u.x=3;u.y=4;const item=pick(g,components)[1];p.items.push(item);receipts.push({player:p.id,name,item,index:3+p.id-1});}}g.carousel=carouselState(g,[...g.draft,...receipts.map(r=>({name:r.name,item:r.item}))],'initial',[0,1,2,3,4,5,6,7],receipts);return g;}
function takeDraft(g,p,index){const o=g.draft[index];if(!o)throw Error('选项已领取');const u=o.name?grant(g,p,o.name,true):null;p.items.push(o.item);recordPick(g,p,o,index);g.draft[index]=null;return u;}
export function chooseDraft(g,index,{defer=false}={}){if(g.phase!=='draft')throw Error('不是选秀阶段');if(g.carousel?.receipts.some(r=>r.player===0))throw Error('已领取');const u=takeDraft(g,g.players[0],index);if(g.stage===1&&u){u.location='board';u.x=3;u.y=4;}for(const id of g.carousel?.after??[])autoDraft(g,g.players[id]);if(!defer)finishDraft(g);}
export function finishDraft(g){if(g.phase!=='draft'||!g.carousel?.receipts.some(r=>r.player===0))throw Error('请先领取');for(const item of g.draft)if(item?.name)g.pool[item.name]++;g.draft=null;g.phase='settled';advance(g);}
function autoDraft(g,p){const options=g.draft.map((o,i)=>({o,i})).filter(r=>r.o);options.sort((a,b)=>draftScore(g,p,b.o)-draftScore(g,p,a.o));if(options.length)takeDraft(g,p,options[0].i);}
function draftScore(g,p,o){return(o.name?effectiveCost(p,def(g,o.name))*3+p.units.filter(u=>u.name===o.name).length*5:0);}
function carousel(g){const order=g.players.filter(p=>p.hp>0).sort((a,b)=>a.hp-b.hp||a.id-b.id),costs=carouselCosts(g.stage);g.draft=[];for(let i=0;i<order.length+1;i++){let name=null;const start=Math.floor(random(g)*costs.length);for(let j=0;j<costs.length&&!name;j++)name=draw(g,{...g.players[0],units:[]},costs[(start+j)%costs.length]);g.draft.push({name,item:carouselItem(g.stage,i,()=>random(g),components.map(c=>c[1]),items.map(i=>i[0]).filter(n=>n!=='奇袭手套'),radiants.map(i=>i.name),artifacts.map(i=>i.name))});}g.carousel=carouselState(g,g.draft,'carousel',order.map(p=>p.id));g.carousel.after=[];let after=false;for(const p of order){if(p.id===0){after=true;continue;}if(after)g.carousel.after.push(p.id);else autoDraft(g,p);}g.phase='draft';if(g.players[0].hp<=0){for(const o of g.draft)if(o?.name)g.pool[o.name]++;g.draft=null;g.phase='settled';advance(g);}}
export function buy(g,id,index){const p=editable(g,id),name=p.shop[index],d=def(g,name);if(!d)throw Error('商品已售出');const cost=effectiveCost(p,d);if(p.gold<cost)throw Error('金币不足');if(p.units.filter(u=>u.location==='bench').length>=9&&p.units.filter(u=>u.name===name&&u.star===1).length<2)throw Error('备战席已满');p.gold-=cost;p.shop[index]=null;grant(g,p,name,true);prepareSystems(g,p);}
export function sell(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);if(!u)throw Error('找不到棋子');g.pool[u.name]+=raw(u);p.gold+=Math.max(1,effectiveCost(p,def(g,u.name))*raw(u)-(u.star===1?0:u.star===2?1:3));p.items.push(...u.items);p.units=p.units.filter(w=>w!==u);claimPending(p);prepareSystems(g,p);}
export function refresh(g,id){const p=editable(g,id),free=has(p,'刷新储备')&&p.freeRefreshRound!==roundName(g),price=free?0:2;if(p.gold<price)throw Error('金币不足');if(free)p.freeRefreshRound=roundName(g);p.gold-=price;shop(g,p);}
export function buyXP(g,id){const p=editable(g,id);if(p.level>=levelCap(p))throw Error('已经满级');if(p.gold<4)throw Error('金币不足');p.gold-=4;giveXP(p,has(p,'升级咯')?7:4);prepareSystems(g,p);}
export function deploy(g,id,uid,x,y){const p=editable(g,id),u=p.units.find(u=>u.id===uid);if(!u||!Number.isInteger(x)||!Number.isInteger(y)||x<0||x>6||y<4||y>7)throw Error('请选择己方棋盘');const occupant=p.units.find(w=>w!==u&&w.location==='board'&&w.x===x&&w.y===y);if(u.location!=='board'&&!occupant&&p.units.filter(w=>w.location==='board').length>=population(p))throw Error('上场人口已满');if(occupant){if(u.location==='board'){occupant.x=u.x;occupant.y=u.y;}else occupant.location=u.location;}u.location='board';u.x=x;u.y=y;prepareSystems(g,p);}
export function bench(g,id,uid){const p=editable(g,id),u=p.units.find(u=>u.id===uid);if(!u)throw Error('找不到棋子');if(p.units.filter(u=>u.location==='bench').length>=9)throw Error('备战席已满');u.location='bench';prepareSystems(g,p);}
export function equip(g,id,uid,index){const p=editable(g,id),u=p.units.find(u=>u.id===uid),name=p.items[index];if(!u||!equipment(name))throw Error('请选择装备与棋子');if(name==='统帅冠冕')throw Error('冠冕留在装备栏即可增加人口');if(u.items.includes('奇袭手套'))throw Error('先拆下奇袭手套');const component=components.some(c=>c[1]===name),existing=u.items.findIndex(i=>components.some(c=>c[1]===i));if(component&&existing>=0){const result=recipe(u.items[existing],name);if(result){u.items[existing]=result;p.items.splice(index,1);if(rank(boardCounts(g,p),'海盗')>=0)p.taskProgress.gear=(p.taskProgress.gear??0)+1;prepareSystems(g,p);return;}}if(u.items.length>=3||name==='奇袭手套'&&u.items.length)throw Error('装备栏已满');u.items.push(name);p.items.splice(index,1);prepareSystems(g,p);}
export function combineItems(g,id,i,j){const p=editable(g,id);if(i===j)throw Error('请选择两件不同组件');const next=recipe(p.items[i],p.items[j]);if(!next)throw Error('不能合成');p.items.splice(Math.max(i,j),1);p.items.splice(Math.min(i,j),1);p.items.push(next);p.taskProgress.gear=(p.taskProgress.gear??0)+1;return next;}
export function useTool(g,id,index,uid){const p=editable(g,id),tool=p.items[index],u=p.units.find(u=>u.id===uid);if(tool==='拆卸器'&&u){p.items.splice(index,1);p.items.push(...u.items);u.items=[];}else if(tool==='重铸器'&&u&&u.items.length){const name=u.items[0];if(!items.some(i=>i[0]===name)&&!components.some(c=>c[1]===name))throw Error('特殊装备不能重铸');p.items.splice(index,1);u.items[0]=pick(g,items.some(i=>i[0]===name)?items:components)[items.some(i=>i[0]===name)?0:1];}else if(tool==='普通复制器'&&u){if(g.pool[u.name]<=0)throw Error('卡池不足');p.items.splice(index,1);grant(g,p,u.name);}else if(tool==='光明升级器'&&u){const slot=u.items.findIndex(i=>radiants.some(r=>r.base===i));if(slot<0)throw Error('没有可升级装备');p.items.splice(index,1);u.items[slot]=radiants.find(r=>r.base===u.items[slot]).name;}else throw Error('请选择有效目标');prepareSystems(g,p);}
export function openSelector(g,id,index){const p=editable(g,id),name=p.items[index],choices=name.includes('光明')?radiants.map(i=>i.name):name.includes('神器')?artifacts.map(i=>i.name):name.includes('成装')?items.map(i=>i[0]):name.includes('组件')?components.map(i=>i[1]):name.includes('纹章')?Object.keys(tiers).filter(n=>n!=='海怪').map(n=>n+'纹章'):null;if(!choices)throw Error('不是选择器');if(p.selector)return p.selector;p.selector={index,name,offers:[]};const list=[...choices];for(let i=0;i<3;i++)p.selector.offers.push(list.splice(Math.floor(random(g)*list.length),1)[0]);return p.selector;}
export function selectItem(g,id,i){const p=editable(g,id),ch=p.selector;if(!ch||!ch.offers[i]||p.items[ch.index]!==ch.name)throw Error('选择器状态已变化');p.items.splice(ch.index,1);p.items.push(ch.offers[i]);p.selector=null;}
export function selectAugment(g,id,i){const p=editable(g,id);accept(g,p,i,name=>grant(g,p,name),()=>pick(g,components)[1]);if(p.pendingXP){giveXP(p,p.pendingXP);p.pendingXP=0;}prepareSystems(g,p);}
export function rerollAugment(g,id,i){const p=editable(g,id);reroll(g,p,i,()=>random(g));}
export function evolveNexus(g,p){if(!has(p,'光的传承'))return;const kills=Math.max(0,...p.units.filter(u=>u.name==='奈克瑟斯').map(u=>u.permanent.nexusKills??0)),next=kills>=70?5:kills>=25?4:3;if(next>p.nexusCost){p.nexusCost=next;log(g,p.name+'的奈克瑟斯进化为'+next+'费，商店同步升级');}}
export function preparations(g,p,side){const c=boardCounts(g,p),ef={augments:p.augments,gold:p.gold,energy:p.energy,teamBonus:p.teamBonus,nextBuff:p.nextBuff,constellation:g.constellation,cores:p.cores??[],guards:p.guards??[],starCells:p.starCells??[],supreme:p.supreme,crown:p.crown,command:p.command??'突击'};const mirror=pos=>side?{x:6-pos.x,y:7-pos.y}:pos;ef.cores=ef.cores.map(mirror);ef.guards=ef.guards.map(mirror);ef.starCells=ef.starCells.map(mirror);return p.units.filter(u=>u.location==='board').map(u=>({name:u.name,star:u.star,items:u.items,hero:u.hero,permanent:u.permanent,instanceId:u.id,nexusCost:p.nexusCost,side,...mirror(u),matchEffects:ef}));}
export function neutralDefinitions(g){const count=g.stage===1?Math.min(3,Math.max(1,g.round-1)):g.stage<5?3:1,hp=g.stage===1?[0,0,200,260,300][g.round]:500+g.stage*300;return Array.from({length:count},(_,i)=>({name:g.stage===1?'海岸幼兽'+(i+1):g.stage<5?'深海守卫'+(i+1):'深海巨兽',cost:0,traits:[],hp,ad:g.stage===1?15:30+g.stage*8,as:.55,armor:g.stage===1?5:20,mr:g.stage===1?5:20,range:1,mana:[0,80],special:true,neutral:true,spell:60+g.stage*35,loot:[],heldItem:g.stage>=5?neutralBossItem(g,0):null}));}
export function startCombat(g){if(g.phase!=='prepare')throw Error('不在准备阶段');if(g.players[0].augmentChoice)throw Error('请先选择强化');if(g.players[0].hp>0&&!g.players[0].units.some(u=>u.location==='board'))throw Error('请先部署棋子');for(const p of g.players.filter(p=>p.hp>0)){if(p.id)aiTurn(g,p.id);prepareSystems(g,p);evolveNexus(g,p);}g.phase='combat';g.settled=false;g.battles=[];const alive=g.players.filter(p=>p.hp>0);if(roundKind(g)==='neutral'){const npc=neutralDefinitions(g);for(const p of alive){const neutralLoot=buildNeutralLoot(g,p,npc,{reserve:(g,p,cost)=>draw(g,p,cost)}),catalog=[...g.catalog,...npc.map((d,i)=>({...d,loot:neutralLoot[i]}))];const placements=[...preparations(g,p,0),...npc.map((d,i)=>({name:d.name,side:1,x:[3,2,4][i],y:2,star:1,items:g.stage>=5?[neutralBossItem(g,p.id)]:[]}))];if(!placements.some(p=>p.side===0)){g.battles.push({a:p.id,b:null,winner:1,empty:true,neutralLoot});continue;}const state=createBattle(catalog,placements,g.seed+g.stage*113+g.round*17+p.id);g.battles.push({a:p.id,b:null,state,neutralLoot});}}else{const order=[...alive].sort(()=>0);for(let i=order.length-1;i>0;i--){const j=Math.floor(random(g)*(i+1));[order[i],order[j]]=[order[j],order[i]];}for(let i=0;i<order.length;i+=2){let a=order[i],b=order[i+1]??order[0];const ghost=!order[i+1];if(b.id===0&&!ghost)[a,b]=[b,a];const placements=[...preparations(g,a,0),...preparations(g,b,1)];if(![0,1].every(side=>placements.some(p=>p.side===side))){g.battles.push({a:a.id,b:b.id,ghost,empty:true,winner:placements.some(p=>p.side===0)?0:1});continue;}g.battles.push({a:a.id,b:b.id,ghost,state:createBattle(g.catalog,placements,g.seed+g.stage*113+g.round*17+a.id)});}}const human=g.battles.find(b=>b.a===0||b.b===0&&!b.ghost);for(const b of g.battles)if(b!==human&&!b.empty)runBattle(b.state);g.humanBattle=human??null;return human;}
function persist(g,p,b,side){if(!b.state)return;for(const u of b.state.units.filter(u=>u.side===side&&!u.special)){const original=p.units.find(w=>w.id===u.instanceId);if(original)original.permanent={...u.permanent};}evolveNexus(g,p);}
export function settleRound(g){if(g.phase!=='combat'||g.settled)throw Error('本轮已经结算');for(const b of g.battles)if(!b.empty&&!b.state.finished)throw Error('战斗尚未结束');const eliminated=[];for(const b of g.battles)for(const side of [0,1]){if(side===1&&(b.b===null||b.ghost))continue;const p=g.players[side?b.b:b.a],winner=b.empty?b.winner:b.state.winner,outcome=winner===null?null:winner===side?0:1,neutral=b.b===null,survivors=(b.state?.units??[]).filter(u=>u.side!==side&&!u.dead&&!u.fused&&!u.special).length,loss=outcome===0?0:neutral?2:Math.max(1,Math.min(15,Math.max(0,g.stage-2)*3)+survivors);p.hp=Math.max(0,p.hp-loss);persist(g,p,b,side);if(!neutral){p.streak=outcome===0?Math.max(0,p.streak)+1:outcome===1?Math.min(0,p.streak)-1:0;p.completedPvP++;}const interest=Math.min(has(p,'利滚利')?7:5,Math.floor(p.gold/10)),streak=neutral?0:Math.min(3,Math.floor(Math.abs(p.streak)/2)),income=5+interest+streak+(outcome===0&&!neutral?1:0);p.gold+=income;p.lastIncome={interest,streak,total:income};p.lastBattle={outcome,loss,opponent:side?b.a:b.b};if(neutral){settleNeutralLoot(g,p,b,outcome,{grant:(g,p,name)=>grant(g,p,name,true)});}else{settleSystems(g,p,b.state,side,outcome,loss);if(has(p,'休眠锻炉')&&!p.dormantForgePaid&&p.completedPvP-(p.dormantForgeStart??0)>=10){p.dormantForgePaid=true;p.items.push('神器选择器');}if(has(p,'活体锻炉')){const due=Math.floor((p.completedPvP-(p.livingForgeStart??0))/9);while((p.livingForgePaid??0)<due){p.livingForgePaid=(p.livingForgePaid??0)+1;p.items.push('神器选择器');}}}p.nextBuff=null;if(p.hp===0)eliminated.push(p);log(g,p.name+(outcome===0?'获胜':outcome===1?'落败':'平局')+(loss?'，损失'+loss+'生命':''));}eliminated.sort((a,b)=>a.id-b.id);let nextRank=8-g.players.filter(p=>p.rank!==null).length;for(const p of eliminated){p.rank=nextRank--;returnShop(g,p);for(const u of p.units)g.pool[u.name]+=raw(u);p.units=[];for(const o of p.market??[])if(o?.unit)g.pool[o.unit]++;p.market=null;}const alive=g.players.filter(p=>p.hp>0);if(alive.length<=1){if(alive[0])alive[0].rank=1;g.finished=true;}g.phase='settled';g.settled=true;}
export function advance(g){if(g.phase!=='settled')throw Error('请先结算');if(g.finished)return;if(g.stage===1){if(g.round<4)g.round++;else{g.stage=2;g.round=1;}}else if(g.round<7)g.round++;else{g.stage++;g.round=1;}g.phase='prepare';g.battles=[];g.humanBattle=null;g.settled=false;for(const p of g.players.filter(p=>p.hp>0)){giveXP(p,2);if(!p.locked)shop(g,p);prepareSystems(g,p);if(['2-1','3-2','4-2'].includes(roundName(g)))offer(g,p,roundName(g),()=>random(g));if(has(p,'照护者之选')){p.caretaker??=[];for(const [level,item] of [[4,'组件选择器'],[6,'普通成装选择器'],[8,'光明装备选择器']])if(p.level>=level&&!p.caretaker.includes(level)){p.caretaker.push(level);p.items.push(item);}}}if(roundKind(g)==='carousel')carousel(g);}
export function aiTurn(g,id){const p=editable(g,id);if(id===0)throw Error('不操作玩家阵容');const catalog=g.catalog.map(d=>effectiveDefinition(p,d)),defs=new Map(catalog.map(d=>[d.name,d]));p.aiFocus=focusFor(p,defs,tiers);if(p.augmentChoice){const options=p.augmentChoice.offers;const scores=options.map((name,i)=>{const d=augments.find(d=>d.name===name);return {i,score:(d.hero&&p.units.some(u=>u.name===d.hero)?40:0)+(d.trait&&p.aiFocus.includes(d.trait)?25:0)+(d.tier==='彩'?5:0)};});scores.sort((a,b)=>b.score-a.score);selectAugment(g,id,scores[0].i);}const plan=economyPlan(g,p),reserve=plan.reserve,target=plan.rerollTarget?Math.max(5,p.level):plan.targetLevel;for(let i=0;i<15&&p.level<target&&p.gold>=4+reserve;i++)buyXP(g,id);const arrange=()=>{const board=selectBoard(p,catalog,tiers,population(p));positionBoard(board,catalog,p);return board;};arrange();for(let attempt=0;attempt<=plan.rolls;attempt++){const offers=p.shop.map((name,i)=>({name,i})).filter(o=>o.name).sort((a,b)=>purchaseScore(p,defs.get(b.name),defs,tiers)-purchaseScore(p,defs.get(a.name),defs,tiers));for(const o of offers){const d=defs.get(o.name),score=purchaseScore(p,d,defs,tiers);if(score<0||p.gold<d.cost+reserve)continue;if(!p.units.some(u=>u.name===o.name)&&!d.traits.some(t=>p.aiFocus.includes(t))&&p.units.length>=population(p)+2&&score<35)continue;try{buy(g,id,o.i);}catch{const spare=p.units.filter(u=>u.location==='bench'&&u.star===1&&!u.items.length&&p.units.filter(w=>w.name===u.name).length===1).sort((a,b)=>purchaseScore(p,defs.get(a.name),defs,tiers)-purchaseScore(p,defs.get(b.name),defs,tiers))[0];if(spare&&purchaseScore(p,defs.get(spare.name),defs,tiers)<score){sell(g,id,spare.id);if(p.units.filter(u=>u.location==='bench').length<9||p.units.filter(u=>u.name===o.name&&u.star===1).length>=2)buy(g,id,o.i);}}}arrange();if(attempt===plan.rolls||p.gold<reserve+6)break;refresh(g,id);}const board=arrange(),score=u=>power(u,defs.get(u.name),p);if(p.heroName){for(const u of p.units)u.hero=false;const u=board.find(u=>u.name===p.heroName);if(u)u.hero=true;}
prepareSystems(g,p);if(p.legendaryChoice)p.items.push(p.legendaryChoice[0]),p.legendaryChoice=null;if(p.routeOffers?.length&&!p.route&&rank(boardCounts(g,p),'探险家')>=0)chooseRoute(g,id,0);if(p.taskOffers?.length&&!p.tasks.length&&rank(boardCounts(g,p),'海盗')>=0)chooseTask(g,id,0);if(p.prestige>=70)redeem(g,id);if((boardCounts(g,p).商人??0)>=2){if(!p.bank&&p.gold>=30)invest(g,id,10,false);if(p.market?.length){const affordable=p.market.findIndex(o=>o&&p.gold>=o.price+reserve);if(affordable>=0)try{buyMarket(g,id,affordable);}catch{}}}for(let i=p.items.length-1;i>=0;i--)if(p.items[i].includes('选择器')){openSelector(g,id,i);selectItem(g,id,0);}
for(let n=0;n<8;n++){const craft=bestCraft(p,catalog,recipe,components,items);if(!craft)break;combineItems(g,id,craft.i,craft.j);}for(let i=p.items.length-1;i>=0;i--)if(equipment(p.items[i])&&p.items[i]!=='统帅冠冕'){const name=p.items[i],u=board.filter(u=>u.items.length<3).sort((a,b)=>gearScore(name,b,defs.get(b.name),p,components,items)-gearScore(name,a,defs.get(a.name),p,components,items))[0];if(u)try{equip(g,id,u.id,i);}catch{}}if(!p.supreme)p.supreme=board.filter(u=>def(g,u.name).traits.includes('海洋巨灵')).sort((a,b)=>score(b)-score(a))[0]?.id;}
export function serialize(g){return JSON.stringify(g,(key,v)=>['random','normalEquipment','copyGear','itemCategory'].includes(key)?undefined:v);}
export function restore(text){const g=JSON.parse(text);if(g.season!==SEASON||g.version!==1)throw Error('这不是第二赛季存档');if(g.phase==='combat')throw Error('战斗存档需从开战前恢复');if(!Array.isArray(g.players)||g.players.length!==8||!g.pool)throw Error('存档损坏');g.catalog=structuredClone(catalog);for(const p of g.players){if(has(p,'升级咯')&&!p.levelUpInitialPaid){giveXP(p,12);p.levelUpInitialPaid=true;}if(has(p,'休眠锻炉'))p.dormantForgeStart??=p.completedPvP;if(has(p,'活体锻炉'))p.livingForgeStart??=p.completedPvP;p.taskProgress??={};p.tasks??=[];}return g;}
export const saveKey=SAVE_KEY;
export function poolInvariant(g){return g.catalog.every(d=>{const owned=g.players.reduce((n,p)=>n+p.units.filter(u=>u.name===d.name).reduce((n,u)=>n+raw(u),0)+p.shop.filter(n=>n===d.name).length+(p.market??[]).filter(o=>o?.unit===d.name).length,0)+(g.draft??[]).filter(o=>o?.name===d.name).length+reservedNeutralCopies(g).filter(n=>n===d.name).length;return g.pool[d.name]>=0&&g.pool[d.name]+owned===COPIES[d.cost];});}
