import {catalog,rank,routes,ancient,legendary,effectiveCost} from './content.mjs';
import {components,items} from './items.mjs';
import {editable,boardCounts,random,pick,roundName,grant,def,log} from './match.mjs';
import {has} from './augments.mjs';
export const tasks=[
{name:'登船作战',key:'pirateKills',goal:8,reward:12},{name:'船长战绩',key:'triple',goal:1,reward:10},{name:'抢夺军备',key:'equippedKills',goal:3,reward:16},{name:'连战连捷',key:'streakWin',goal:2,reward:14},{name:'制霸航线',key:'opponents',goal:3,reward:20},{name:'绝境突围',key:'lastMan',goal:1,reward:18},{name:'以少胜多',key:'underdog',goal:1,reward:16},{name:'新船员',key:'pirateTwo',goal:2,reward:12},{name:'精锐船员',key:'pirateThree',goal:1,reward:24},{name:'全副武装',key:'pirateGear',goal:3,reward:20},{name:'军备升级',key:'gear',goal:2,reward:10},{name:'满载而归',key:'fullGear',goal:1,reward:10},{name:'稳定贸易',key:'interest',goal:10,reward:14},{name:'积蓄财富',key:'rich',goal:2,reward:16},{name:'孤注一掷',key:'poor',goal:2,reward:18,risk:true},{name:'风暴航程',key:'loss',goal:20,reward:20,risk:true},{name:'整装突破',key:'levelWin',goal:1,reward:14},{name:'炮火洗礼',key:'pirateDamage',goal:12000,reward:16}];
export const merchants=[
{name:'长期军备',price:8,quality:0,attr:'hp',value:20,limit:10},{name:'精准训练',price:10,quality:1,attr:'ad',value:.02,limit:5},{name:'秘法训练',price:10,quality:1,attr:'ap',value:2,limit:5},{name:'决战物资',price:5,quality:0,next:true},{name:'防御物资',price:5,quality:0,next:true},{name:'战术加速',price:5,quality:1,next:true},{name:'装备重铸器',price:4,quality:0,item:'重铸器'},{name:'装备拆卸器',price:3,quality:0,item:'拆卸器'},{name:'普通组件选择器',price:10,quality:1,item:'组件选择器'},{name:'普通复制器',price:18,quality:1,item:'普通复制器'},{name:'光明装备选择器',price:30,quality:2,item:'光明装备选择器',limit:1},{name:'神器选择器',price:25,quality:2,item:'神器选择器',limit:1}];
export const rewardThresholds=[20,40,70,110,160,230];
function freeTiles(p,count,existing=[],back=false){const used=new Set(p.units.filter(u=>u.location==='board').map(u=>u.x+','+u.y));const result=[];for(let i=0;i<count;i++){const old=existing[i];if(old&&old.x>=0&&old.x<=6&&old.y>=4&&old.y<=7&&!result.some(t=>t.x===old.x&&t.y===old.y)&&(!used.has(old.x+','+old.y)||back)){result.push(old);continue;}let chosen;for(const y of back?[6,7,5,4]:[4,5,6,7]){const x=[3,2,4,1,5,0,6].find(x=>!used.has(x+','+y)&&!result.some(t=>t.x===x&&t.y===y));if(x!==undefined){chosen={x,y};break;}}if(chosen)result.push(chosen);}return result;}
export function prepareSystems(g,p){const c=boardCounts(g,p),explore=rank(c,'探险家'),ruin=rank(c,'遗迹守护者'),pirates=rank(c,'海盗');p.cores=ruin>=0?freeTiles(p,ruin+1,p.cores??[],true):[];p.guards=ruin>=0?freeTiles(p,ruin+1,p.guards??[]):[];p.starCells=rank(c,'星宿')>=0?freeTiles(p,Math.min(3,rank(c,'星宿')+1),p.starCells??[],true):[];if(explore>=0&&!p.route&&!p.routeOffers)p.routeOffers=[...routes].sort(()=>0).filter(()=>true);if(p.routeOffers?.length===4){const index=Math.floor(random(g)*4);p.routeOffers.splice(index,1);}if(pirates>=0&&p.tasks.length<(pirates>=2?2:1)&&(!p.taskOffers||p.taskOffers.length===0)){const list=tasks.filter(t=>!p.tasks.some(active=>active.name===t.name)&&(!has(p,'船长的赌注')||t.risk));p.taskOffers=[];for(let i=0;i<3&&list.length;i++)p.taskOffers.push(list.splice(Math.floor(random(g)*list.length),1)[0].name);}if((c.商人??0)>=2&&p.marketRound!==roundName(g)){returnMarket(g,p);p.marketRound=roundName(g);generateMarket(g,p);}else if((c.商人??0)<2&&p.market){returnMarket(g,p);}if(has(p,'照护者之选')){p.caretaker??=[];for(const [level,item]of [[4,'组件选择器'],[6,'普通成装选择器'],[8,'光明装备选择器']])if(p.level>=level&&!p.caretaker.includes(level)){p.caretaker.push(level);p.items.push(item);}}}
export function chooseRoute(g,id,index){const p=editable(g,id);if(rank(boardCounts(g,p),'探险家')<0||p.route||!p.routeOffers?.[index])throw Error('路线不可更换');p.route=p.routeOffers[index];p.items.push(ancient[routes.indexOf(p.route)]);p.energy=0;p.routeOffers=null;log(g,p.name+'选择'+p.route+'之路');}
export function chooseTask(g,id,index){const p=editable(g,id),q=rank(boardCounts(g,p),'海盗'),slots=q>=2?2:1,name=p.taskOffers?.[index];if(q<0||!name||p.tasks.length>=slots)throw Error('没有可用任务栏');const d=tasks.find(d=>d.name===name);p.tasks.push({...d,start:{...p.taskProgress},startRound:p.completedPvP,startLevel:p.level,seen:[],streakWins:0,roundsElapsed:0});p.taskOffers=[];prepareSystems(g,p);}
export function taskValue(p,t){if(['pirateTwo','pirateThree','pirateGear','fullGear'].includes(t.key)){const pirates=p.units.filter(u=>u.location==='board'&&(catalog.find(d=>d.name===u.name)?.traits.includes('海盗')||u.items.includes('海盗纹章')));if(t.key==='pirateTwo')return new Set(pirates.filter(u=>u.star>=2).map(u=>u.name)).size;if(t.key==='pirateThree')return pirates.some(u=>u.star===3)?1:0;if(t.key==='pirateGear')return new Set(pirates.filter(u=>u.items.length>=2).map(u=>u.name)).size;return pirates.some(u=>u.items.length===3)?1:0;}if(t.key==='opponents')return t.seen.length;if(t.key==='streakWin')return t.streakWins??0;return Math.max(0,(p.taskProgress[t.key]??0)-(t.start[t.key]??0));}
export function redeem(g,id){const p=editable(g,id),eligible=rewardThresholds.filter(n=>p.prestige>=n);if(!eligible.length)throw Error('至少需要20声望');const level=eligible.length;const saved=p.prestige;p.prestige=has(p,'满载归航')?Math.floor(saved*.25):0;reward(g,p,level);log(g,p.name+'兑换'+level+'级海盗战利品');return level;}
export function reward(g,p,level){const gold=[8,12,18,25,35,50][level-1];p.gold+=gold;if(level===1)p.items.push(pick(g,components)[1]);if(level===2){p.items.push(pick(g,components)[1],pick(g,components)[1]);grant(g,p,pick(g,catalog.filter(d=>d.cost===2)).name);}if(level===3)p.items.push('普通成装选择器','普通复制器',pick(g,['光徽','暗徽']));if(level===4){p.items.push('光明装备选择器');for(let i=0;i<2;i++)grant(g,p,pick(g,catalog.filter(d=>d.cost===4)).name);}if(level===5)p.items.push('神器选择器','光明装备选择器','普通复制器');if(level===6){p.items.push('光明装备选择器','神器选择器');p.legendaryChoice=[...legendary];for(let i=0;i<2;i++)grant(g,p,pick(g,catalog.filter(d=>d.cost===5)).name);}}
export function chooseLegendary(g,id,index){const p=editable(g,id),name=p.legendaryChoice?.[index];if(!name)throw Error('没有传奇战利品');p.items.push(name);p.legendaryChoice=null;}
export function invest(g,id,amount,risk){const p=editable(g,id),q=rank(boardCounts(g,p),'商人');if(q<0||p.bank||![10,20].includes(amount)||p.gold<amount)throw Error('不能进行投资');p.gold-=amount;p.bank={amount,risk,rank:q,due:p.completedPvP+3};}
export function withdraw(g,id){const p=editable(g,id);if(!p.bank)throw Error('没有投资');p.gold+=Math.floor(p.bank.amount*.8);p.bank=null;}
export function gamble(g,id){const p=editable(g,id),q=rank(boardCounts(g,p),'商人');if(q<0||p.gold<5||p.gambleRound===roundName(g))throw Error('本轮不能赌彩');p.gold-=5;p.gambleRound=roundName(g);const weights=[[35,30,20,10,5],[25,30,25,12,8],[15,30,30,15,10]][q];let roll=random(g)*100,index=4;for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<0){index=i;break;}}if(index===1)p.gold+=5;if(index===2)p.gold+=8;if(index===3)p.items.push(pick(g,components)[1]);if(index===4)grant(g,p,pick(g,catalog.filter(d=>d.cost===3)).name);return ['没有奖赏','返还5金币','获得8金币','获得组件','获得三费棋子'][index];}
function returnMarket(g,p){for(const o of p.market??[])if(o?.unit)g.pool[o.unit]++;p.market=null;}
function generateMarket(g,p){const q=rank(boardCounts(g,p),'商人'),weights=[[70,25,5],[50,40,10],[30,50,20]][q];p.market=[];for(let slot=0;slot<3;slot++){let roll=random(g)*100,quality=2;for(let i=0;i<3;i++){roll-=weights[i];if(roll<0){quality=i;break;}}if(random(g)<.35){const list=g.catalog.filter(d=>g.pool[d.name]>0&&effectiveCost(p,d)<=Math.min(5,quality*2+2));const d=pick(g,list);if(d){g.pool[d.name]--;p.market.push({name:d.name,unit:d.name,price:effectiveCost(p,d),quality});continue;}}const choices=merchants.filter(d=>d.quality===quality&&(p.merchantBought[d.name]??0)<(d.limit??Infinity)&&(!d.next||p.nextBuff!==d.name));p.market.push(choices.length?{...pick(g,choices)}:{name:'军费补充',price:2,gold:3});}}
export function refreshMarket(g,id){const p=editable(g,id);if(rank(boardCounts(g,p),'商人')<0||p.gold<2)throw Error('不能刷新商人商店');p.gold-=2;returnMarket(g,p);generateMarket(g,p);}
export function buyMarket(g,id,index){const p=editable(g,id),o=p.market?.[index];if(rank(boardCounts(g,p),'商人')<0||!o)throw Error('商品不存在');const price=o.unit?effectiveCost(p,def(g,o.unit)):o.price;if(p.gold<price)throw Error('金币不足');if(o.next&&p.nextBuff===o.name)throw Error('已拥有相同战斗物资');if(o.limit&&(p.merchantBought[o.name]??0)>=o.limit)throw Error('达到购买上限');p.gold-=price;if(o.unit)grant(g,p,o.unit,true);if(o.item)p.items.push(o.item);if(o.attr)p.teamBonus[o.attr]=(p.teamBonus[o.attr]??0)+o.value;if(o.next)p.nextBuff=o.name;if(o.gold)p.gold+=o.gold;p.merchantBought[o.name]=(p.merchantBought[o.name]??0)+1;p.market[index]=null;}
export function moveSpecial(g,id,kind,index,x,y){const p=editable(g,id),key={核心:'cores',守卫:'guards',星格:'starCells'}[kind];if(!key||!p[key]?.[index]||!Number.isInteger(x)||!Number.isInteger(y)||x<0||x>6||y<4||y>7)throw Error('无效站位');if(p[key].some((pos,i)=>i!==index&&pos.x===x&&pos.y===y)||kind==='守卫'&&p.units.some(u=>u.location==='board'&&u.x===x&&u.y===y))throw Error('该位置已占用');p[key][index]={x,y};}
export function settleSystems(g,p,state,side,outcome,loss){if(p.systemsSettled===roundName(g))return;p.systemsSettled=roundName(g);const before={...p.taskProgress};const c=state?.traits[side]?.counts??boardCounts(g,p),q=rank(c,'海盗'),us=state?.units.filter(u=>u.side===side&&!u.special&&!u.fused)??[],opponent=state?.units.filter(u=>u.side!==side&&!u.special&&!u.fused)??[],dead=opponent.filter(u=>u.dead),pstats=p.taskProgress;
 if(p.bank&&p.completedPvP>=p.bank.due){const b=p.bank;let value;if(!b.risk)value=b.amount*[1.2,1.3,1.4][b.rank];else{const weights=[[25,30,35,10],[20,25,40,15],[15,20,45,20]][b.rank];let roll=random(g)*100,i=3;for(let j=0;j<4;j++){roll-=weights[j];if(roll<0){i=j;break;}}value=b.amount*[.6,1,1.5,2.2][i];}p.gold+=Math.floor(value);p.bank=null;}
 if(q<0)for(const t of p.tasks)t.streakWins=0;const hunter=rank(c,'海怪猎手');if(hunter>=0){p.bounty+=state?.traits[side].bounty??0;const threshold=[8,7,6][hunter];while(p.bounty>=threshold){p.bounty-=threshold;p.gold+=[2,3,4][hunter];}}
 if(rank(c,'探险家')>=0&&p.route){const e=rank(c,'探险家'),base=p.route==='战斗'?dead.length*4+(outcome===0?12+Math.min(12,Math.max(0,p.streak-1)*3):outcome===null?6:0):p.route==='繁荣'?Math.min(21,6+3*p.lastIncome.interest):p.route==='坚守'?Math.min(35,Math.floor((state?.units.filter(u=>u.side!==side).reduce((n,u)=>n+u.damageDone,0)??0)/100)):Math.min(35,us.reduce((n,u)=>n+u.castCount*2,0));p.energy=Math.min(has(p,'永恒航路')?1100:600,p.energy+Math.floor(base*[1,1.25,1.5][e]));}
 if(q>=0){pstats.pirateKills=(pstats.pirateKills??0)+(state?.traits[side].pirateKills??0);pstats.pirateDamage=(pstats.pirateDamage??0)+us.filter(u=>u.traits.includes('海盗')).reduce((n,u)=>n+u.damageDone,0);pstats.triple=(pstats.triple??0)+(us.some(u=>u.traits.includes('海盗')&&(u.participations??0)>=3)?1:0);pstats.equippedKills=(pstats.equippedKills??0)+dead.filter(u=>u.items.length>=2&&us.some(w=>w.traits.includes('海盗')&&u.participants?.[w.id]>=(u.diedAt??state.time)-5)).length;pstats.lastMan=(pstats.lastMan??0)+(outcome===0&&us.filter(u=>!u.dead).length===1?1:0);pstats.underdog=(pstats.underdog??0)+(outcome===0&&us.length<opponent.length?1:0);pstats.interest=(pstats.interest??0)+p.lastIncome.interest;pstats.rich=(pstats.rich??0)+(us[0]?.matchEffects.gold>=40?1:0);pstats.poor=(pstats.poor??0)+(us[0]?.matchEffects.gold<=5?1:0);pstats.loss=(pstats.loss??0)+loss;}
 if(us.some(u=>u.name==='巴罗萨星人')&&outcome===0){p.barossaWins=(p.barossaWins??0)+1;if(p.barossaWins%3===0)p.items.push(pick(g,components)[1]);}
 if(q>=0){if(q===3&&!p.legendaryGranted){p.legendaryGranted=true;reward(g,p,6);}const done=[];for(const [index,t] of p.tasks.entries()){t.start??={};if(index>=(q>=2?2:1)){for(const key of Object.keys(pstats))t.start[key]=(t.start[key]??0)+(pstats[key]??0)-(before[key]??0);t.streakWins=0;continue;}t.roundsElapsed=(t.roundsElapsed??0)+1;t.streakWins=outcome===0?(t.streakWins??0)+1:0;if(t.key==='opponents'&&outcome===0){const enemy=g.battles.find(b=>!b.ghost&&(b.a===p.id||b.b===p.id));const id=enemy?.a===p.id?enemy.b:enemy?.a;if(id!==null&&id!==undefined&&!t.seen.includes(id))t.seen.push(id);}if(t.key==='levelWin'&&outcome===0&&p.level>t.startLevel&&t.roundsElapsed<=4){pstats.levelWin=(pstats.levelWin??0)+1;}if(taskValue(p,t)>=t.goal){const gain=Math.floor(t.reward*[1,1.25,1.5,2][q]*(has(p,'船长的赌注')?1.4:1));p.prestige+=gain;done.push(t);log(g,p.name+'完成'+t.name+'，声望+'+gain);}}for(const t of p.tasks)if(!done.includes(t)&&t.key==='levelWin'&&(t.roundsElapsed??0)>=4)log(g,p.name+'的整装突破任务已到期');p.tasks=p.tasks.filter(t=>!done.includes(t)&&!(t.key==='levelWin'&&(t.roundsElapsed??0)>=4));p.taskOffers=[];}
 if(has(p,'残骸盛宴')&&dead.some(u=>u.items.some(name=>items.some(d=>d[0]===name)))&&rank(c,'食腐者')>=0){for(const u of p.units.filter(u=>u.location==='board'&&(def(g,u.name).traits.includes('食腐者')||u.items.includes('食腐者纹章')))){const star=u.star-1,attrs=u.name==='古敦'?{armor:[.3,.5,.8][star],mr:[.3,.5,.8][star]}:u.name==='双尾怪'?{ap:[.5,.8,1.2][star]}:u.name==='萨德拉'?{ad:[.4,.7,1.1][star]}:{hp:[6,9,14][star]};for(const[k,v]of Object.entries(attrs))u.permanent[k]=(u.permanent[k]??0)+v*2;u.permanent.remains=(u.permanent.remains??0)+2;}}
}
