import {rank,ancient} from './content.mjs';
const pick=(u,v)=>v[Math.min(3,u.star)-1];
const augment=(u,n)=>u.matchEffects?.augments?.includes(n);
export function initTraits(s,a,spawn){for(const side of [0,1]){const team=s.units.filter(u=>u.side===side&&!u.special),c=s.traits[side].counts,r=n=>rank(c,n),tr=s.traits[side];tr.navyNext=r('皇家海军')===4?0:r('皇家海军')>=3?4:6;tr.oracleNext=3;tr.starNext=4;tr.ships=team.filter(u=>u.traits.includes('皇家海军'));tr.starSum=[...new Map(tr.ships.map(u=>[u.name,u.star])).values()].reduce((n,v)=>n+v,0);for(const u of team){const give=(t,fn)=>{const q=r(t);if(q>=0&&u.traits.includes(t))fn(q);};const b=r('斗士');if(b>=0){u.maxHp+=[100,180,300][b];if(u.traits.includes('斗士'))u.maxHp*=1+[.15,.3,.5][b];}const mystic=r('秘术师');if(mystic>=0)u.mr+=[20,35,60][mystic];give('重装战士',q=>{u.armor+=[20,40,70][q];u.mr+=[20,40,70][q];a.buff(s,u,'heavy-open',8,{armor:[20,40,70][q],mr:[20,40,70][q]});});give('战士',q=>{u.omni+=[.1,.15,.22][q];u.amp+=[.08,.15,.25][q];});give('刺客',q=>{u.skillCrit=true;u.extraCrit=(u.extraCrit??0)+[.15,.25,.4][q];u.extraCritDamage=(u.extraCritDamage??0)+[.1,.25,.45][q];});give('法师',q=>u.mageScale=[.75,.95,1.2][q]);give('神枪手',()=>u.range++);give('炮手',q=>u.amp+=[.08,.15,.25][q]);give('岛屿卫士',q=>u.dr=1-(1-u.dr)*(1-[.08,.14,.22][q]));give('皇家海军',q=>{a.shield(s,u,[150,250,250,400,400][q],60,'navy');if(q>=2){u.adBonus+=q>=3?.25:.15;u.ap+=q>=3?25:15;}});give('海怪猎手',q=>{u.adBonus+=[.12,.22,.35][q];u.asBonus+=[.12,.22,.35][q];});give('远灵教会',q=>{u.adBonus+=[.12,.22,.35][q];u.ap+=[12,22,35][q];});
 const ef=u.matchEffects,perma=ef.teamBonus??{};u.maxHp+=perma.hp??0;u.adBonus+=perma.ad??0;u.ap+=perma.ap??0;if(ef.nextBuff==='决战物资'){u.adBonus+=.15;u.ap+=15;}if(ef.nextBuff==='防御物资')a.shield(s,u,200,60,'merchant');if(ef.nextBuff==='战术加速')a.buff(s,u,'merchant-speed',8,{as:.2});
 for(const name of ef.augments??[]){if(name==='战备训练'){u.maxHp+=150;u.adBonus+=.1;}if(name==='法术研习')u.ap+=20;if(name==='先发制人')u.mana+=20;if(name==='持久战')u.omni+=.1;if(name==='铁壁防线'){u.armor+=20;u.mr+=20;}}
 if(u.hero&&augment(u,'深海猎食者'))u.omni+=.15;
 for(const item of u.items){if(ancient.includes(item)){const artifactMultiplier=(r('探险家')>=2?1.2:1)*(augment(u,'永恒航路')?1+Math.min(5,Math.floor(Math.max(0,(ef.energy??0)-600)/100))*.05:1);u.artifactMultiplier=artifactMultiplier;if(item==='征潮战刃'){u.adBonus+=.2*artifactMultiplier;u.asBonus+=.15*artifactMultiplier;if(ef.energy>=300)u.omni+=.15*artifactMultiplier;}if(item==='黄金罗盘'){u.ap+=(25+(ef.energy>=600?35:0))*artifactMultiplier;u.mana+=15;}if(item==='深海壁垒'){u.maxHp+=300*artifactMultiplier;u.armor+=25*artifactMultiplier;u.mr+=25*artifactMultiplier;if(ef.energy>=300)u.dr=1-(1-u.dr)*(1-.15*artifactMultiplier);}if(item==='潮汐圣典'){u.ap+=30*artifactMultiplier;u.mana+=15;}}
 if(item==='不沉之旗'){u.maxHp+=1200;u.armor+=60;u.mr+=60;}if(item==='船长佩刀'){u.adBonus+=.8;u.asBonus+=.8;u.omni+=.35;}if(item==='黄金火铳'){u.adBonus+=.6;u.ap+=80;u.mana+=20;u.amp+=.35;}}
 u.hp=u.maxHp;u.mana=Math.min(u.maxMana,u.mana);
 }
 const owner=team[0];if(!owner)continue;const relic=r('遗迹守护者');if(relic>=0){const cores=owner.matchEffects.cores??[];for(const u of team)if(cores.some(p=>a.distance(p,u)<=1)){const mult=u.traits.includes('遗迹守护者')?1.5:1;a.shield(s,u,[150,250,400][relic]*mult,60,'relic');u.armor+=[10,20,35][relic]*mult;u.mr+=[10,20,35][relic]*mult;}for(let i=0;i<=relic;i++)spawn(s,owner,{name:'遗迹守卫',hp:[650,1000,1500][relic],ad:[45,65,90][relic],as:.65,armor:[35,50,65][relic],range:1,spell:[100,160,250][relic]},owner.matchEffects.guards?.[i]);}
 const giants=team.filter(u=>u.traits.includes('海洋巨灵')),g=r('海洋巨灵');if(g>=0){const chosen=giants.find(u=>u.instanceId===owner.matchEffects.supreme)??[...giants].sort((x,y)=>y.cost-x.cost||y.star-x.star)[0],ratio=(g===0?.45:.65)+(chosen.name==='阿古茹'?.1:0);for(const u of giants.filter(u=>u!==chosen)){u.fused=true;u.dead=true;chosen.maxHp+=u.baseHp*ratio;chosen.baseAd+=u.def.ad*[1,1.8,3.24][u.star-1]*ratio;chosen.ap+=100*ratio;for(const item of u.items){const kind=s.itemCategory(item);if(kind==='physical')chosen.adBonus+=.08;else if(kind==='magic')chosen.ap+=12;else if(kind==='speed')chosen.asBonus+=.1;else if(kind==='defense'){chosen.maxHp+=120;chosen.armor+=8;chosen.mr+=8;}else chosen.mana+=8;}if(u.name==='乔尼亚斯')chosen.giantShield=true;if(u.name==='高斯')chosen.giantHeal=true;if(u.name==='阿古茹')chosen.amp+=.15;a.event(s,'fusion',u,chosen);}chosen.dr=1-(1-chosen.dr)*(1-[.12,.2][g]);chosen.hp=chosen.maxHp;chosen.supreme=true;chosen.giantSupportScale=augment(chosen,'巨灵之潮')?1.5:1;if(augment(chosen,'巨灵之潮')){chosen.maxHp*=1.15;chosen.hp=chosen.maxHp;chosen.omni+=.15;}}
 const star=r('星宿');if(star>=0)initStar(s,team,star,a);
 for(const u of team.filter(a.live)){const q=r('海盗'),mult=q===3?1.2:1;if(u.traits.includes('星宿')&&r('星宿')===3&&augment(u,'星辰共鸣')){u.maxHp*=1.15;u.hp=u.maxHp;}if(u.items.includes('不沉之旗')){a.shield(s,u,u.maxHp*3*mult,Infinity,'legendary-flag');u.flagRefresh=true;for(const w of team.filter(w=>w!==u&&a.live(w)))a.shield(s,w,w.maxHp*mult,Infinity,'flag-'+u.id);}}
 }}
function initStar(s,team,q,a){const source=team[0],kind=source.matchEffects.constellation,tr=s.traits[source.side];tr.constellation=kind;tr.starRank=q;tr.starFull=q===3;tr.starWeak=!tr.starFull&&q>=2&&augment(source,'星辰共鸣');tr.starPower=tr.starFull?1:tr.starWeak?.5:0;const stars=team.filter(u=>u.traits.includes('星宿')),i=Math.min(q,2);if(kind==='罗盘座'){tr.mark=a.enemies(s,source).sort((x,y)=>y.maxHp-x.maxHp||a.distance(x,{x:3,y:source.side?1:6})-a.distance(y,{x:3,y:source.side?1:6})||x.y-y.y||x.x-y.x)[0]?.id;}if(kind==='北冕座'){const crown=stars.find(u=>u.instanceId===source.matchEffects.crown)??[...stars].sort((x,y)=>y.cost-x.cost||y.star-x.star)[0];tr.crown=crown?.id;if(crown){crown.maxHp+=[150,250,400][i];crown.hp=crown.maxHp;crown.adBonus+=[.15,.25,.4][i];crown.ap+=[15,25,40][i];if(tr.starFull||tr.starWeak)crown.dr=1-(1-crown.dr)*(tr.starFull?.75:.875);}}if(kind==='鲸鱼座'&&(tr.starFull||tr.starWeak))for(const u of team)a.shield(s,u,u.maxHp*.25*tr.starPower,60,'whale-open');if(kind==='猎户座')for(const u of team)if(stars.includes(u)||tr.starFull||tr.starWeak){u.extraCrit=(u.extraCrit??0)+(stars.includes(u)?[.15,.25,.35][i]:0);if(tr.starFull||tr.starWeak){u.skillCrit=true;if(stars.includes(u))u.extraCritDamage=(u.extraCritDamage??0)+.5*tr.starPower;}}}
export function attackTraits(s,u,v,a,extra){const c=s.traits[u.side].counts,r=n=>rank(c,n),tr=s.traits[u.side],has=t=>u.traits.includes(t)&&r(t)>=0;if(has('私掠者')){const q=r('私掠者');a.hit(s,u,v,a.stats(u).ad*[.08,.14,.22][q],'true',{noCrit:true});a.buff(s,u,'private-focus',60,{amp:(u.sameHits??0)>=6?[.1,.18,.3][q]:0});}if(has('决斗大师')&&!extra&&(u.duelStacks??0)<10){u.duelStacks=(u.duelStacks??0)+1;u.asBonus+=[.05,.08,.12][r('决斗大师')];}if(has('远灵教会')){const q=r('远灵教会');v.church={owner:u.id,stacks:Math.min(5,(v.church?.until>s.time?v.church.stacks:0)+1),until:s.time+4,next:v.church?.next??s.time+1,value:[6,10,15][q]};if(!extra)u.fervor=(u.fervor??0)+1;if(!u.fanatic&&u.fervor>=[18,15,12][q]){u.fanatic=true;u.asBonus+=[.35,.6,1][q];if(augment(u,'狂热传道'))for(const w of a.allies(s,u).filter(w=>w!==u).sort((x,y)=>a.distance(u,x)-a.distance(u,y)).slice(0,2))a.buff(s,w,'fervor-'+u.id,60,{as:.2});}if(u.hero&&augment(u,'远灵圣歌')&&u.fervor%5===0)u.hymn=true;}
 if(augment(u,'舰队集结')&&u.navyHit){u.navyHit=false;a.hit(s,u,v,40,'magic');}
 if(has('星宿')&&tr.constellation==='天蝎座'){v.poison={owner:u.id,until:s.time+4,next:v.poison?.next??s.time+1,stacks:tr.starFull||tr.starWeak?Math.min(3,(v.poison?.stacks??0)+1):1,value:[15,25,40][Math.min(tr.starRank,2)]};v.woundUntil=s.time+4;}
 if(has('星宿')&&tr.constellation==='猎户座'&&v.hp/v.maxHp>.7)a.hit(s,u,v,a.stats(u).ad*[.1,.2,.3][Math.min(tr.starRank,2)],'physical',{noCrit:true});
 if(!extra){if(u.items.includes('征潮战刃')&&(u.matchEffects.energy??0)>=100&&u.attacks%((u.matchEffects.energy??0)>=600?3:4)===0)s.queue.push({at:s.time+.1,type:'extra',source:u.id,target:v.id});if(u.items.includes('船长佩刀')){s.queue.push({at:s.time+.1,type:'extra',source:u.id,target:v.id});a.hit(s,u,v,a.stats(u).ad*.5,'true',{noCrit:true});}if(has('星宿')&&(tr.starFull||tr.starWeak)&&tr.constellation==='船帆座'&&u.attacks%4===0)a.hit(s,u,v,a.stats(u).ad*.6*tr.starPower,'physical');if(u.id===tr.crown&&(tr.starFull||tr.starWeak)&&u.attacks%3===0)a.hit(s,u,v,180*tr.starPower,'magic');}}
export function deathTraits(s,v,a){if(!v.special&&!v.rewarded){v.rewarded=true;const credited=s.units.filter(u=>u.side!==v.side&&!u.special&&v.participants?.[u.id]>=s.time-5);for(const u of credited){u.permanent.kills++;u.participations=(u.participations??0)+1;if(u.name==='奈克瑟斯'){const gain=u.cost===5?pick(u,[1,1.6,3]):u.cost===4?pick(u,[.8,1.3,2]):pick(u,[.6,1,1.6]);u.permanent.ad=(u.permanent.ad??0)+gain;u.baseAd+=gain;u.permanent.nexusKills=(u.permanent.nexusKills??0)+1;}
 const q=rank(s.traits[u.side].counts,'食腐者');if(q>=0&&u.traits.includes('食腐者')){const amount=q+1,mult=u.hero&&augment(u,'深海猎食者')?1.3:1;u.permanent.remains=(u.permanent.remains??0)+amount;const attrs=u.name==='古敦'?{armor:pick(u,[.3,.5,.8]),mr:pick(u,[.3,.5,.8])}:u.name==='双尾怪'?{ap:pick(u,[.5,.8,1.2])}:u.name==='萨德拉'?{ad:pick(u,[.4,.7,1.1])*mult}:{hp:pick(u,[6,9,14])};for(const [key,n] of Object.entries(attrs)){u.permanent[key]=(u.permanent[key]??0)+n*amount;if(key==='ad')u.baseAd+=n*amount;else if(key==='hp'){u.maxHp+=n*amount;u.hp+=n*amount;}else u[key]+=n*amount;}}
 if(u.name==='巴巴尔星人'&&(u.killCooldown??0)<=s.time){u.killCooldown=s.time+2;a.mana(s,u,pick(u,[12,18,30]));u.omniBase??=u.omni;u.omni=u.omniBase+pick(u,[.15,.2,.3]);u.omniUntil=s.time+3;u.skillOmniBase=u.omniBase;}
 if(['芹泽和也','伊格尼斯'].includes(u.name)&&u.killCast!==u.castCount&&s.time<u.busyUntil+3){u.killCast=u.castCount;a.mana(s,u,pick(u,u.name==='伊格尼斯'?[15,20,30]:[10,15,25]));if(u.name==='伊格尼斯')a.buff(s,u,'ignis-kill',3,{as:pick(u,[.25,.35,.55])});}
 if(u.items.includes('船长佩刀')){a.heal(s,u,u.maxHp*.2);u.adBonus+=.1;}if(u.items.includes('征潮战刃')&&u.matchEffects.energy>=600)a.buff(s,u,'blade-kill',4,{as:.3});
 }for(const side of [0,1]){const members=credited.filter(u=>u.side===side);if(members.some(u=>u.traits.includes('海怪猎手')))s.traits[side].bounty=(s.traits[side].bounty??0)+1;if(members.some(u=>u.traits.includes('海盗')))s.traits[side].pirateKills=(s.traits[side].pirateKills??0)+1;}
 }
 if(v.poison&&(s.traits[v.side?0:1].starFull||s.traits[v.side?0:1].starWeak)){const poison=v.poison;for(const w of s.units.filter(w=>w.side===v.side&&a.live(w)&&a.distance(w,v)<=1))w.poison={...poison,until:s.time+4,next:s.time+1};}
 for(const u of creditedForStar(s,v,a)){const tr=s.traits[u.side];if((tr.starFull||tr.starWeak)&&tr.constellation==='猎户座'){const target=a.enemies(s,u).sort((x,y)=>a.distance(u,x)-a.distance(u,y))[0];if(target)a.hit(s,u,target,a.stats(u).ad*.8*tr.starPower,'physical');}}
 if(v.name==='亡灵宙达')v.effects.push({kind:'remnant',until:v.star===3?60:s.time+6,next:s.time+2});
 
 for(const u of s.units.filter(a.live)){if(u.contract===v.id){a.heal(s,u,u.maxHp*.2);u.ap+=pick(u,[20,30,500]);}const tr=s.traits[u.side];if(tr.mark===v.id){tr.mark=a.enemies(s,u).sort((x,y)=>y.maxHp-x.maxHp||x.id.localeCompare(y.id))[0]?.id;if(tr.starFull||tr.starWeak)for(const w of a.allies(s,u))a.buff(s,w,'compass-kill',4,{as:.4*tr.starPower});}}
 const q=rank(s.traits[v.side].counts,'幽灵');if(q>=0&&v.traits.includes('幽灵')&&!v.fused){const host=a.allies(s,v).sort((x,y)=>a.distance(v,x)-a.distance(v,y)||x.id.localeCompare(y.id))[0];if(host){const mult=[1,1.3,1.7][q],attrs=v.name==='西博兹'?{armor:pick(v,[15,25,40])*mult,mr:pick(v,[15,25,40])*mult}:v.name==='卡蜜拉'?{omni:pick(v,[.15,.2,.3])*mult}:{ap:pick(v,[20,30,50])*mult,amp:pick(v,[.1,.15,.25])*mult};host.ghosts??=[];host.ghosts.push({attrs,migrate:augment(v,'亡者同行')});for(const [k,n]of Object.entries(attrs))if(k==='omni')host.omni+=n;else a.buff(s,host,'ghost-'+v.id,60,{[k]:n,...Object.fromEntries(Object.entries(attrs).filter(([key])=>key!=='omni'))});if(augment(v,'亡者同行'))a.shield(s,host,host.maxHp*.15,60,'ghost-shield-'+v.id);a.event(s,'possession',v,host);}}
 if(v.ghosts)for(const ghost of v.ghosts.filter(g=>g.migrate)){const host=a.allies(s,v).sort((x,y)=>a.distance(v,x)-a.distance(v,y))[0];if(host){const attrs=Object.fromEntries(Object.entries(ghost.attrs).map(([k,n])=>[k,n*.5]));if(attrs.omni)host.omni+=attrs.omni;delete attrs.omni;a.buff(s,host,'migrated-'+v.id,60,attrs);}}
 if(v.name==='遗迹守卫'&&augment(v,'遗迹复苏'))for(const w of a.enemies(s,v).filter(w=>a.distance(v,w)<=1))a.hit(s,v,w,200,'magic');
}
function creditedForStar(s,v,a){return s.units.filter(u=>u.side!==v.side&&a.live(u)&&!u.special&&v.participants?.[u.id]>=s.time-5);}
export function tickTraits(s,a){for(const side of [0,1]){const tr=s.traits[side],team=s.units.filter(u=>u.side===side&&!u.special&&!u.fused),c=tr.counts,r=n=>rank(c,n),owner=team.find(a.live);if(!owner)continue;const navy=r('皇家海军');if(navy>=0&&s.time>=tr.navyNext){tr.navyNext=s.time+(navy===4?2:navy>=3?4:6);const candidates=a.enemies(s,owner),target=candidates[0];const targets=navy===4?candidates:navy>=1?candidates.filter(w=>target&&a.distance(w,target)<=1):target?[target]:[];for(const v of targets){a.hit(s,owner,v,(navy===4?160+18*tr.starSum:100+12*tr.starSum)*(augment(owner,'不沉舰队')?1.2:1),'physical',{noCrit:true,area:navy>0});if(navy>=2)a.buff(s,v,'navy-shred',4,{armorPct:.2});}for(const u of tr.ships)u.navyHit=true;a.event(s,'bombardment',owner,null,{count:targets.length});}
 const oracle=r('神谕');if(oracle>=0&&s.time>=tr.oracleNext){tr.oracleNext+=3;for(const u of a.allies(s,owner))a.mana(s,u,[2,4,6][oracle]+(u.traits.includes('神谕')?[4,6,9][oracle]:0));}
 const sr=tr.starRank;if(sr>=0){const stars=team.filter(u=>u.traits.includes('星宿')&&a.live(u)),i=Math.min(sr,2),full=tr.starFull||tr.starWeak;if(tr.constellation==='船帆座'&&s.tick%120===0||tr.constellation==='船帆座'&&full&&s.tick===1)for(const u of stars)a.buff(s,u,'star-wind',full?60:3,{as:[.2,.35,.55][i]});if(tr.constellation==='鲸鱼座'&&s.tick%20===0){const cells=owner.matchEffects.starCells??[];for(const u of team.filter(a.live))if(full||cells.slice(0,i+1).some(p=>p.x===u.x&&p.y===u.y)){const value=u.maxHp*[.02,.03,.04][i]*(u.traits.includes('星宿')?1.5:1),missing=u.maxHp-u.hp;a.heal(s,u,value);if(full&&value>missing)a.shield(s,u,Math.min(u.maxHp*.5,(u.shields.find(sh=>sh.key==='whale-overheal')?.amount??0)+(value-missing)*tr.starPower),60,'whale-overheal');}}if(tr.constellation==='天琴座'&&s.time>=tr.starNext){tr.starNext+=4;for(const u of a.allies(s,owner))if(full||stars.some(w=>a.distance(u,w)<=1))a.mana(s,u,[4,7,10][i]);if(full)for(const v of a.enemies(s,owner)){a.hit(s,owner,v,80*tr.starPower,'magic');a.buff(s,v,'lyra-slow',2,{as:-.2});}}if(full&&tr.constellation==='罗盘座'){const target=a.lookup(s,tr.mark);if(target)a.buff(s,target,'star-shred',.1,{armorPct:.3*tr.starPower,mrPct:.3*tr.starPower});}}
 for(const u of team.filter(a.live)){if(u.traits.includes('私掠者')&&r('私掠者')>=0&&u.attackTarget&&!a.live(a.lookup(s,u.attackTarget)??{}))u.buffs=u.buffs.filter(b=>b.key!=='private-focus');const island=r('岛屿卫士');if(island>=0&&u.traits.includes('岛屿卫士')&&!u.islandTriggered&&u.hp/u.maxHp<.4){u.islandTriggered=true;for(const w of a.allies(s,u))a.shield(s,w,Math.min(w.maxHp*.5,[80,150,250][island]),4,'island-'+u.id);a.buff(s,u,'island-save',4,{dr:[.1,.15,.2][island]});}if(u.traits.includes('战士')&&r('战士')>=0)a.buff(s,u,'warrior-low',.1,{amp:u.hp/u.maxHp<.5?[.08,.15,.25][r('战士')]*.5:0});if(u.items.includes('不沉之旗')&&u.flagRefresh&&!u.shields.some(sh=>sh.key==='legendary-flag'&&sh.amount>0)){u.flagRefresh=false;a.shield(s,u,u.maxHp*3*(r('海盗')===3?1.2:1),Infinity,'legendary-flag-2');}
 if(u.items.includes('深海壁垒')&&u.matchEffects.energy>=100&&u.hp/u.maxHp<.5&&s.time>=(u.wallNext??0)){u.wallNext=u.matchEffects.energy>=600?s.time+10:Infinity;a.shield(s,u,u.maxHp*.35*(u.artifactMultiplier??1),6,'wall');if(u.matchEffects.energy>=600){const target=a.allies(s,u).filter(w=>w!==u&&a.distance(u,w)<=1).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];if(target)a.shield(s,target,target.maxHp*.2*(u.artifactMultiplier??1),6,'wall-save');}}if(u.items.includes('深海壁垒')&&u.matchEffects.energy>=300&&s.tick%100===0)for(const v of a.enemies(s,u).filter(w=>a.distance(u,w)<=1))a.hit(s,u,v,u.maxHp*.06,'magic',{artifact:true});
 if(u.giantHeal&&s.tick%120===0)a.heal(s,u,u.maxHp*.08*(u.giantSupportScale??1));if(u.giantShield&&u.castCount&&!u.giantShieldUsed){u.giantShieldUsed=true;a.shield(s,u,u.maxHp*.2*(u.giantSupportScale??1),5,'giant-first');}
 if(augment(u,'不沉舰队')&&u.traits.includes('皇家海军')&&!u.navySave&&u.hp/u.maxHp<.3){u.navySave=true;a.shield(s,u,u.maxHp*.25,5,'navy-save');}
 if(augment(u,'遗迹复苏')&&s.tick%100===0&&(u.matchEffects.cores??[]).some(c=>a.distance(c,u)<=1))a.shield(s,u,100,5,'relic-renew');
 }
 }for(const v of s.units.filter(a.live))for(const key of ['church','poison']){const b=v[key];if(b&&s.time<=b.until+1e-8&&s.time>=b.next){b.next+=1;const u=a.lookup(s,b.owner);if(u)a.hit(s,u,v,b.value*b.stacks,'magic',{noCrit:true});}}
}
